---
sidebar: sidebar 
permalink: concept_about_applications.html 
keywords: applications, asset, cost 
summary: 会社の環境で使用されているアプリケーションを理解することは、資産の使用状況とコストを追跡するのに役立ちます。 
---
= アプリケーション別の資産使用状況の追跡
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
会社の環境で使用されているアプリケーションを理解することは、資産の使用状況とコストを追跡するのに役立ちます。

テナントで実行されているアプリケーションに関連付けられたデータを追跡する前に、まずそれらのアプリケーションを定義し、適切なアセットに関連付ける必要があります。アプリケーションは、ホスト、仮想マシン、ボリューム、内部ボリューム、qtree、共有、ハイパーバイザーなどの資産に関連付けることができます。

このトピックでは、マーケティング チームが Exchange 電子メールに使用する仮想マシンの使用状況を追跡する例を示します。

次のような表を作成して、テナントで使用されるアプリケーションを識別し、各アプリケーションを使用しているグループまたはビジネス ユニットを記録することをお勧めします。

[cols="5*"]
|===


| テナント | 事業分野 | Business Unit（ビジネス ユニット） | プロジェクト | アプリケーション 


| NetApp | データストレージ | 法律上の | 特許 | Oracle Identity Manager、Oracle On Demand、PatentWiz 


| NetApp | データストレージ | マーケティング | 販売イベント | Exchange、Oracle 共有データベース、BlastOff イベント プランナー 
|===
表は、マーケティング チームが Exchange アプリケーションを使用していることを示しています。  Exchange の仮想マシンの使用率を追跡して、いつストレージを追加する必要があるかを予測できるようにしたいと考えています。  Exchange アプリケーションをマーケティング部門のすべての仮想マシンに関連付けることができます。

. _Exchange_という名前のアプリケーションを作成します
. *クエリ > + 新しいクエリ* に移動して、仮想マシンの新しいクエリを作成します (または、該当する場合は既存の VM クエリを選択します)。
+
マーケティング チームの VM の名前にはすべて「*mkt*」という文字列が含まれていると仮定して、VM 名を「mkt」でフィルターするクエリを作成します。

. VMを選択します。
. *一括操作 > アプリケーションの追加* を使用して、VM を _Exchange_ アプリケーションに関連付けます。
. 目的のアプリケーションを選択し、[*保存*] をクリックします。
. 完了したら、クエリを*保存*します。

