---
sidebar: sidebar 
permalink: concept_asset_user_data_section.html 
summary: アセット ページのユーザー データ セクションでは、現在のアセットに注釈またはアプリケーションを割り当てることができます。 
keywords: asset page, user data, applications, annotations 
---
= ユーザーデータセクション
:hardbreaks:
:allow-uri-read: 


[role="lead"]
アセット ページのユーザー データ セクションには、アプリケーションや注釈などのユーザー定義データが表示され、変更できます。



== ユーザーデータセクションを使用してアプリケーションの割り当てまたは変更を行う

テナント上で実行されているアプリケーションを特定の資産 (ホスト、仮想マシン、ボリューム、内部ボリューム、qtree、ハイパーバイザー) に割り当てることができます。ユーザー データ セクションでは、資産に割り当てられたアプリケーションを追加、変更、または削除できます。ボリュームを除くすべての資産タイプに対して、複数のアプリケーションを割り当てることができます。

.手順
. 次のいずれかの方法でアセット ページを見つけます。
+
.. 資産のリストを照会し、リストから 1 つを選択します。
.. ダッシュボードでアセット名を見つけてクリックします。
.. 検索を実行し、結果から資産を選択します。
+
資産ページが表示されます。このページの「ユーザー データ」セクションには、現在割り当てられているアプリケーションまたは注釈が表示されます。





割り当てられたアプリケーションを変更するか、アプリケーションまたは追加のアプリケーションを割り当てるには、[*アプリケーション*] リストをドロップダウンし、資産に割り当てるアプリケーションを選択します。アプリケーションを入力して検索するか、リストから選択することができます。

アプリケーションを削除するには、アプリケーション リストをドロップダウンし、アプリケーションのチェックを外します。



== ユーザーデータセクションを使用して注釈を割り当てたり変更したりする

企業の要件に合わせてデータを追跡するためにData Infrastructure Insightsをカスタマイズする場合、注釈と呼ばれる特殊なメモを定義し、それを資産に割り当てることができます。アセット ページのユーザー データ セクションには、アセットに割り当てられた注釈が表示され、そのアセットに割り当てられた注釈を変更することもできます。

.手順
. アセットに注釈を追加するには、アセット ページの [ユーザー データ] セクションで [*+ 注釈*] をクリックします。
. リストから注釈を選択します。
. [値] をクリックし、選択した注釈の種類に応じて次のいずれかを実行します。
+
.. 注釈タイプがリスト、日付、またはブール値の場合は、リストから値を選択します。
.. 注釈タイプがテキストの場合は、値を入力します。


. [Save]をクリックします。


注釈がアセットに割り当てられます。後でクエリを使用して、アノテーションによってアセットをフィルタリングできます。

注釈を割り当てた後にその値を変更する場合は、注釈リストをドロップダウンして別の値を入力します。

注釈がリスト タイプで、[新しい値をオンザフライで追加] オプションが選択されている場合は、既存の値を選択するだけでなく、入力して新しい値を追加できます。
