---
sidebar: sidebar 
permalink: concept_cs_event_rate_checker.html 
summary: Workload Security データ コレクターを展開する前に、SVM イベント レート チェッカーを使用して NFS/SMB イベント レートを測定し、最適なエージェントのサイズを決定します。 
keywords: event, checker, rate, sizing, cloud secure 
---
= イベントレートチェッカー：エージェントサイジングガイド
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
データコレクタを導入する前に、SVM によって生成される NFS および SMB イベントレートを測定することで、最適な Agent マシンのサイジングを決定します。Event Rate Checker スクリプトは、容量制限（Agent あたり最大 50 のデータコレクタ）を理解し、Agent インフラストラクチャが予想されるイベント量を処理して信頼性の高い脅威検出を実現できることを確認するのに役立ちます。



== 要件：

* クラスターIP
* クラスター管理者のユーザー名とパスワード



NOTE: このスクリプトを実行するときは、イベント レートを決定する SVM に対してONTAP SVM データ コレクターが実行されていない必要があります。

手順：

. CloudSecure の指示に従ってエージェントをインストールします。
. エージェントがインストールされたら、sudo ユーザーとして _server_data_rate_checker.sh_ スクリプトを実行します。
+
 /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
. このスクリプトを実行するには、Linux マシンに _sshpass_ がインストールされている必要があります。インストール方法は 2 つあります。
+
.. 次のコマンドを実行します。
+
 linux_prompt> yum install sshpass
.. それでも問題が解決しない場合は、Web から Linux マシンに _sshpass_ をダウンロードし、次のコマンドを実行します。
+
 linux_prompt> rpm -i sshpass


. プロンプトが表示されたら正しい値を入力してください。例については以下を参照してください。
. スクリプトの実行には約 5 分かかります。
. 実行が完了すると、スクリプトは SVM からのイベント レートを出力します。コンソール出力で SVM ごとのイベント レートを確認できます。
+
 “Svm svm_rate is generating 100 events/sec”.


各 Ontap SVM データ コレクターは単一の SVM に関連付けることができます。つまり、各データ コレクターは単一の SVM が生成するイベントの数を受信できるようになります。

次の事項に注意してください。

A) この表を一般的なサイズガイドとして使用してください。コア数やメモリ数を増やすと、サポートされるデータ コレクターの数を最大 50 個まで増やすことができます。

|===


| エージェントマシン構成 | SVMデータコレクターの数 | エージェントマシンが処理できる最大イベントレート 


| 4コア、16GB | 10人のデータ収集者 | 20Kイベント/秒 


| 4コア、32GB | 20人のデータ収集者 | 20Kイベント/秒 
|===
B) 合計イベント数を計算するには、そのエージェントのすべての SVM に対して生成されたイベントを追加します。

C) スクリプトがピーク時間帯に実行されない場合、またはピークトラフィックを予測することが難しい場合は、イベント レート バッファを 30% に維持します。

B + C は A より小さくなければなりません。そうでない場合、エージェント マシンは監視に失敗します。

つまり、単一のエージェント マシンに追加できるデータ コレクターの数は、次の式に従う必要があります。

 Sum of all Event rate of all Data Source Collectors + Buffer Event rate of 30% < 20000 events/second
参照link:concept_cs_agent_requirements.html["エージェントの要件"]追加の前提条件と要件については、ページをご覧ください。



== 例

それぞれ 1 秒あたり 100、200、300 イベントのイベント レートを生成する 3 つの SVMS があるとします。

次の式を適用します。

....
 (100+200+300) + [(100+200+300)*30%] = 600+180 = 780events/sec
780 events/second is < 20000 events/second, so the 3 SVMs can be monitored via one agent box.
....
コンソール出力は、エージェント マシンの現在の作業ディレクトリにあるファイル名 __fpolicy_stat_<SVM 名>.log__ で確認できます。

次の場合には、スクリプトによって誤った結果が返される可能性があります。

* 不正な資格情報、IP、または SVM 名が指定されています。
* 同じ名前、シーケンス番号などを持つ既存の fpolicy はエラーになります。
* スクリプトは実行中に突然停止します。


スクリプトの実行例を以下に示します。

 [root@ci-cs-data agent]# /opt/netapp/cloudsecure/agent/install/svm_event_rate_checker.sh
....
Enter the cluster ip: 10.192.139.166
Enter the username to SSH: admin
Enter the password:
Getting event rate for NFS and SMB events.
Available SVMs in the Cluster
-----------------------------
QA_SVM
Stage_SVM
Qa-fas8020
Qa-fas8020-01
Qa-fas8020-02
audit_svm
svm_rate
vs_new
vs_new2
....
....
-----------------------------
Enter [1/5] SVM name to check (press enter to skip): svm_rate
Enter [2/5] SVM name to check (press enter to skip): audit_svm
Enter [3/5] SVM name to check (press enter to skip):
Enter [4/5] SVM name to check (press enter to skip):
Enter [5/5] SVM name to check (press enter to skip):
Running check for svm svm_rate...
Running check for svm audit_svm...
Waiting 5 minutes for stat collection
Stopping sample svm_rate_sample
Stopping sample audit_svm_sample
fpolicy stats of svm svm_rate is saved in fpolicy_stat_svm_rate.log
Svm svm_rate is generating 100 SMB events/sec and 100 NFS events/sec
Overall svm svm_rate is generating 200 events/sec
fpolicy stats of svm audit_svm is saved in fpolicy_stat_audit_svm.log
Svm audit_svm is generating 200 SMB events/sec and 100 NFS events/sec
Overall svm audit_svm is generating 300 events/sec
....
 [root@ci-cs-data agent]#


== トラブルシューティング

|===


| 質問 | 回答 


| Workload Security 用にすでに設定されている SVM でこのスクリプトを実行すると、SVM 上の既存の fpolicy 設定がそのまま使用されるのでしょうか、それとも一時的な設定が設定されてプロセスが実行されるのでしょうか? | イベント レート チェッカーは、すでに Workload Security 用に設定されている SVM でも正常に実行できます。影響はないはずです。 


| スクリプトを実行できる SVM の数を増やすことはできますか? | ○スクリプトを編集して、SVM の最大数を 5 から任意の数に変更するだけです。 


| SVM の数を増やすと、スクリプトの実行時間も長くなりますか? | いいえ。SVM の数が増えても、スクリプトは最大 5 分間実行されます。 


| スクリプトを実行できる SVM の数を増やすことはできますか? | ○スクリプトを編集し、SVM の最大数を 5 から任意の数に変更する必要があります。 


| SVM の数を増やすと、スクリプトの実行時間も長くなりますか? | いいえ。SVM の数が増えても、スクリプトは最大 5 分間実行されます。 


| 既存のエージェントでイベント レート チェッカーを実行するとどうなりますか? | 既存のエージェントに対してイベント レート チェッカーを実行すると、SVM のレイテンシが増加する可能性があります。イベント レート チェッカーの実行中、この増加は一時的なものになります。 
|===