---
sidebar: sidebar 
permalink: concept_searching_assets.html 
summary: 高度な検索テクニックを使用すると、探している資産を見つけることができます。 
keywords: asset page, objects, search, advanced, alerts 
---
= 資産とアラートを検索するためのヒントとコツ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
監視対象環境内のデータやオブジェクトを検索するには、複数の検索手法を使用できます。

* *ワイルドカード検索*
+
* 文字を使用して複数文字のワイルドカード検索を実行できます。たとえば、_applic*n_ は _application_ を返します。

* *検索に使用したフレーズ*
+
フレーズとは、二重引用符で囲まれた単語のグループです。たとえば、「VNX LUN 5」などです。名前または属性にスペースが含まれるドキュメントを検索するには、二重引用符を使用できます。

* *ブール演算子*
+
ブール演算子 OR、AND、NOT を使用すると、複数の用語を組み合わせてより複雑なクエリを作成できます。

+
または

+
OR 演算子はデフォルトの結合演算子です。

+
2 つの用語の間にブール演算子がない場合、OR 演算子が使用されます。

+
OR 演算子は 2 つの用語をリンクし、いずれかの用語がドキュメント内に存在する場合に一致するドキュメントを検索します。

+
たとえば、_storage OR netapp_ は、_storage_ または _netapp_ のいずれかを含むドキュメントを検索します。

+
ほとんどの用語に一致するドキュメントには高いスコアが与えられます。

+
および

+
AND 演算子を使用すると、1 つのドキュメント内に両方の検索用語が存在するドキュメントを見つけることができます。たとえば、_storage AND netapp_ は、_storage_ と _netapp_ の両方を含むドキュメントを検索します。

+
AND という単語の代わりに、記号 *&&* を使用できます。

+
ない

+
NOT 演算子を使用すると、NOT の後の用語を含むすべてのドキュメントが検索結果から除外されます。たとえば、_storage NOT netapp_ は、_storage_ のみが含まれ、_netapp_ が含まれないドキュメントを検索します。

+
NOT という単語の代わりに記号 *!* を使用できます。



検索では大文字と小文字は区別されません。



== インデックスされた用語を使用して検索する

インデックスされた用語に一致する検索が多いほど、スコアが高くなります。

検索文字列はスペースによって個別の検索用語に分割されます。たとえば、検索文字列「storage aurora netapp」は、「storage」、「aurora」、「netapp」の 3 つのキーワードに分割されます。検索は 3 つの用語すべてを使用して実行されます。これらの用語のほとんどに一致するドキュメントのスコアが最高になります。提供する情報が多ければ多いほど、検索結果は良くなります。たとえば、ストレージを名前とモデルで検索できます。

UI には、カテゴリ全体の検索結果が表示され、カテゴリごとに上位 3 つの結果が表示されます。期待したオブジェクトが見つからなかった場合は、検索文字列にさらに多くの用語を含めることで、検索結果を向上させることができます。

次の表は、検索文字列に追加できるインデックス用語の一覧を示しています。

|===
| カテゴリ | 索引用語 


| ストレージ | 「ストレージ」名ベンダーモデル 


| ストレージプール | 「ストレージプール」名、ストレージの名前、ストレージのIPアドレス、ストレージのシリアル番号、ストレージベンダー、ストレージモデル、関連付けられているすべての内部ボリュームの名前、関連付けられているすべてのディスクの名前 


| 内部容積 | 「internalvolume」名、ストレージ名、ストレージのIPアドレス、ストレージのシリアル番号、ストレージベンダー、ストレージモデル、ストレージプール名、関連付けられているすべての共有名、関連付けられているすべてのアプリケーション名 


| Volume | 「ボリューム」名ラベル、すべての内部ボリュームの名前、ストレージプールの名前、ストレージの名前、ストレージのIPアドレス、ストレージのシリアル番号、ストレージベンダー、ストレージモデル 


| ストレージ ノード | 「storagenode」名 ストレージ名 ストレージのIPアドレス ストレージのシリアル番号 ストレージベンダー ストレージモデル 


| ホスト | 「ホスト」名 IPアドレス 関連するすべてのアプリケーションの名前 


| データストア | 「データストア」名 仮想センターIP すべてのボリュームの名前 すべての内部ボリュームの名前 


| 仮想マシン | 「仮想マシン」名 DNS名 IPアドレス ホストの名前 ホスト名のIPアドレス すべてのデータストアの名前 関連付けられたすべてのアプリケーションの名前 


| スイッチ（通常およびNPV） | 「スイッチ」IPアドレス WWN名 シリアル番号 モデル ドメインID ファブリック名 ファブリックのWWN 


| Application | 「アプリケーション」名 テナント 事業部門 プロジェクト 


| Tape | 「テープ」IPアドレス名シリアル番号ベンダー 


| ポート | 「ポート」WWN名 


| ファブリック | 「ファブリック」WWN名 


| Storage Virtual Machine（SVM） | 「storagevirtualmachine」の名前UUID 
|===