---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: ビジネス洞察に関する質問への回答を支援するために、推奨ダッシュボードをインポートできます。以前にエクスポートしたカスタム ダッシュボードをインポートすることもできます。 
keywords: dashboard, gallery, import, export 
---
= ダッシュボードのインポート
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insights は、データに関するビジネス分析情報を提供するための推奨ダッシュボードを多数提供します。各ダッシュボードには、テナントで現在収集されているデータに関連する特定の質問に答えたり、特定の問題を解決したりするために設計されたウィジェットが含まれています。  DII を使用すると、便利なダッシュボードをエクスポートして別のテナントにインポートすることもできます。



== ダッシュボードギャラリーからインポートする

ギャラリーからダッシュボードをインポートするには、次の操作を行います。

. *オブザーバビリティ > 探索 > すべてのダッシュボード*を選択します
. *+ダッシュボードのインポート*をクリックし、_ギャラリーからのインポート_を選択します。
+
環境内のデータ コレクターに基づいて、*推奨ダッシュボード* のリストが表示されます。ダッシュボードは、AWS、 NetApp、ストレージ、VMware など、さまざまな種類のオブジェクトに関する質問に答えるのに役立ちます。

. リストから 1 つ以上のダッシュボードを選択し、「*ダッシュボードの追加*」をクリックします。これらのダッシュボードはダッシュボード リストに表示されます。


推奨されるダッシュボードに加えて、現在のデータに関連しない追加のダッシュボード * をインポートすることもできます。たとえば、現在ストレージデータコレクタがインストールされていないが、将来の設定を計画している場合でも、ストレージに関連するダッシュボードをインポートできます。これらのダッシュボードは表示可能ですが、少なくとも 1 つのストレージデータコレクタが設定されるまでは、関連するデータは表示されません。

ダッシュボードギャラリーからのインポートは、管理者ロールまたはアカウント所有者ロールを持つユーザーが使用できます。



== エクスポートしたダッシュボードのインポート

ダッシュボードを*エクスポート*するには、*[Observability] > [Explore] > [All Dashboards]* ページで、ダッシュボードの右側にあるメニューをクリックし、[_Export_] を選択します。複数のダッシュボードを選択し、「一括操作」ドロップダウンから「エクスポート」を選択することもできます。ダッシュボードは、ローカル システム上の .ZIP ファイルに保存されます。

ダッシュボードを*インポート*するには、目的のテナントに移動して次の操作を行います。

. *オブザーバビリティ > 探索 > すべてのダッシュボード*を選択します
. *+ダッシュボードのインポート*をクリックし、_ファイルからインポート_を選択します。以前にエクスポートしたファイルの .ZIP を選択します。ダッシュボードがインポートされ、ダッシュボード リストに表示されます。既存のダッシュボードと同じ名前のダッシュボードをインポートする場合は、ダッシュボード名に「(2)」が追加されることに注意してください。

