---
sidebar: sidebar 
permalink: cs_notifications_email.html 
summary: Workload Security Alerts の通知用の電子メール アドレスを追加します。 
keywords: email, notifications, alerts, warnings, attacks 
---
= アラート、警告、エージェント/データソースコレクターの正常性に関する電子メール通知の構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security アラートの受信者を設定するには、*管理 > 通知* をクリックし、各受信者の適切なセクションに電子メール アドレスを入力します。



== 潜在的な攻撃の警告と警告

_潜在的な攻撃_ アラート通知を送信するには、[_潜在的な攻撃アラートの送信_] セクションに受信者のメール アドレスを入力します。アラートのすべてのアクションについて、アラート受信者リストに電子メール通知が送信されます。

_警告_ 通知を送信するには、[_警告アラートの送信_] セクションに受信者のメール アドレスを入力します。



== エージェントとデータコレクターのヘルスモニタリング

通知を通じてエージェントとデータ ソースの正常性を監視できます。

エージェントまたはデータ ソース コレクターが機能していない場合に通知を受信するには、[_データ収集ヘルス アラート_] セクションに受信者の電子メール アドレスを入力します。

次の事項に注意してください。

* ヘルスアラートは、エージェント/コレクターが少なくとも 1 時間レポートを停止した後にのみ送信されます。
* エージェントまたはデータ コレクターが長期間切断された場合でも、指定された 24 時間以内に対象の受信者に送信される電子メール通知は 1 件のみです。
* エージェントに障害が発生した場合、1 つのアラートが送信されます (コレクターごとに 1 つではありません)。電子メールには、影響を受けるすべての SVM のリストが含まれます。
* Active Directory 収集の失敗は警告として報告されますが、ランサムウェアの検出には影響しません。
* 「はじめに」セットアップ リストに、新しい「電子メール通知の構成」フェーズが追加されました。




== エージェントとデータコレクターのアップグレード通知の受信

* 「データ収集ヘルスアラート」にメール ID を入力します。
* 「アップグレード通知を有効にする」チェックボックスが有効になります。
* エージェントおよびデータ コレクターのアップグレードに関する電子メール通知は、計画されたアップグレードの 1 日前に電子メール ID に送信されます。




== トラブルシューティング

|===
| *問題：* | *これを試してみてください:* 


| 「データ コレクターのヘルス アラート」に電子メール ID が表示されますが、通知を受信できません。 | 通知メールは、 NetApp Data Infrastructure Insightsドメイン (_accounts@service.cloudinsights.netapp.com_) から送信されます。一部の企業では、外部ドメインからの受信メールをブロックします。  NetApp Data Infrastructure Insightsドメインからの外部通知がホワイトリストに登録されていることを確認します。 
|===