---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= 構成とサポートされるデバイス
:hardbreaks:
:allow-uri-read: 


[role="lead"]
この FAQ では、Data Infrastructure Insights の構成とサポートされているデバイスに関するよくある質問に回答します。



== Data Infrastructure Insights は環境に変更を加えますか?

いいえ。Data Data Infrastructure Insights は、環境に関する情報を収集する読み取り専用ツールです。  Data Infrastructure Insights は、資産や構成に一切変更を加えません。



== Data Infrastructure Insightsにはデバイスに対してどのような権限レベルのアクセスが必要ですか?

デバイスがサポートしている場合は、ほとんどの場合、読み取り専用アクセスのみが必要です。読み取り専用アクセスを許可しないソリューションもあり、その場合は適切な昇格された権限が必要になります。



== Data Infrastructure Insights はどのくらいの頻度で情報を収集しますか?

Data Infrastructure Insights は通常、5 分ごとにパフォーマンス データを収集し、30 分ごとに論理的および物理的な構造を検出します。  Data Infrastructure Insights は、推奨されるベスト プラクティスとスケーラビリティに従ってデフォルトのポーリング間隔を設定しますが、ユーザーはこれらの間隔を完全に制御できます。



== Data Infrastructure Insights は環境にどのような影響を与えますか?

Data Infrastructure Insights のエージェントレス、帯域外、パッシブ IP 通信は、セットアップ、メンテナンス、およびデータセンター エコシステムへの影響を最小限に抑えるのに役立ちます。 Data Infrastructure Insights のパフォーマンス開発チームは、パフォーマンス自体の監視活動において、データセンターのパフォーマンスへの影響を最小限に抑えるために多大な対策を講じています。通常の動作環境では影響は無視できるほど小さいと考えられており、使用率の高い、またはパフォーマンスが低いテクノロジー プラットフォームでは、影響を緩和したり強化したりできます。詳細については、「 Data Infrastructure Insightsインストール ガイド」を参照してください。



== Data Infrastructure Insightsですべてのホスト/VM を一覧表示するにはどうすればいいですか?

Data Infrastructure Insights のウィジェットとクエリ リスト機能を使用すると、データ センター資産のインベントリ スタイル リストを提供できます。仮想マシンのリストは、スピンドルに至るまで、またその間の多数の構成要素に至るまで、すべてクエリ、ウィジェット、ダッシュボード、およびデータ ウェアハウス レポートで利用できるようになり、RESTful API を通じてアクセスできます。



== Data Infrastructure Insights は、関連する非ハイパーバイザー ホスト (物理サーバーなど) にも同じタイプのサポートを提供しますか?

VMware などのハイパーバイザーは、ESXi ホストとその仮想マシン (VM) に関する詳細情報を提供します。物理サーバーの場合、 Data Infrastructure Insights はホスト HBA までのメトリックを収集します。 Data Infrastructure Insights は、特許出願中のテクノロジーを使用して物理サーバーを検出する独自の方法を採用しています。ストレージやスイッチが検出されると、物理サーバーのホスト名がファブリック エイリアス情報内に含まれるようになります。 Data Infrastructure Insights はこれらのホスト名を選択し、DNS で照合して、ホストを自動的にData Infrastructure Insightsに取り込みます。この技術により、手動によるエントリの更新とツール在庫のメンテナンスの必要性が大幅に軽減されます。



== Data Infrastructure Insights は、異機種環境間で同じデバイス メトリック深度 (パリティ) を提供しますか?

サードパーティのプラットフォームおよびベンダーのテクノロジーには、標準化、共通化、命名法の程度が異なります。  Data Infrastructure Insights は、容量とパフォーマンス情報を一貫したフレームワークに正規化しようとします。 IOPS、レイテンシ、生の容量など、一部の容量とパフォーマンスのメトリックは、デバイスのカウンターからネイティブに提供されます。カウンターが提供されていない場合、 Data Infrastructure Insights は値の要約を試みることができます (たとえば、基礎となるボリュームの IOPS または容量を合計するなど)。また、どちらも利用できない場合は、 Data Infrastructure Insights はさまざまな計算アルゴリズムを通じてメトリック値を導出しようとします。  Data Infrastructure Insights は、現在Data Infrastructure Insightsによって収集されていない追加のメトリックを組み込むための汎用 SNMP 統合機能を提供します。



== Data Infrastructure Insights はファイバー チャネル スイッチをサポートしていますか?

はい。ストレージ資産からデータを収集するだけでなく、 Data Infrastructure Insights はテナント上のCisco、 Brocade 、QLogic スイッチからインベントリとパフォーマンスのデータも取得します。



== インフラストラクチャ全体のトポロジービューは利用できますか?  Data Infrastructure Insights は「エンドツーエンドの可視性」を示しますか?

はい、 Data Infrastructure Insights は論理構造と物理構造を動的に検出してマッピングし、コンピューティング、ファブリック、バーチャライザー、バックエンド ストレージのインタラクティブなエンドツーエンドのトポロジ ビューを提供します。トポロジ アイコンを使用すると、影響を受けるリソースへのナビゲーションをすばやく起動でき、共有ストレージ環境におけるワークロードと違反の識別に役立ちます。
