---
sidebar: sidebar 
permalink: insights_overview.html 
keywords: insight, greedy, degraded, impacted, impacting, impactful, impact, resources, consuming, workload, ttf, time to full, k8s, kubernetes, namespace 
summary: Insights では、リソースの使用状況と傾向を確認できます。 
---
= 洞察
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Insights を使用すると、リソースの使用状況やそれが他のリソースに与える影響、またはフル稼働までの時間の分析などを調べることができます。

多数の Insights が利用可能です。詳細を確認するには、*ダッシュボード > インサイト* に移動します。アクティブなインサイト (現在発生しているインサイト) はメイン タブに表示され、非アクティブなインサイトは [非アクティブなインサイト] タブに表示されます。非アクティブなインサイトとは、以前はアクティブだったが、現在は発生していないインサイトです。



== インサイトの種類



=== ストレス下における共有リソース

影響の大きいワークロードは、共有リソース内の他のワークロードのパフォーマンスを低下させる可能性があります。これにより、共有リソースにストレスがかかります。  Data Infrastructure Insights は、リソースの飽和状態とテナントへの影響を調査するのに役立つツールを提供します。link:insights_shared_resources_under_stress.html["詳細情報"]



=== Kubernetes 名前空間のスペース不足

Kubernetes 名前空間のスペース不足インサイトでは、スペース不足になるリスクがある Kubernetes 名前空間のワークロードが表示され、各スペースがいっぱいになるまでの残り日数の見積もりも表示されます。link:insights_k8s_namespaces_running_out_of_space.html["詳細情報"]



=== ONTAPコールド ストレージの再利用

_Reclaim ONTAP Cold Storage_ Insight は、 ONTAPシステム上のボリュームのコールド容量、潜在的なコスト/電力節約、推奨されるアクション項目に関するデータを提供します。link:insights_reclaim_ontap_cold_storage.html["詳細情報"]


NOTE: これはプレビュー機能であり、改善が進むにつれて変更される可能性があります。link:/concept_preview_features.html["詳細情報"] Data Infrastructure Insightsプレビュー機能について。
