---
settings:
  name: Data Infrastructure Insights
  harmony_integration: maestro
  rss_page: concept_whats_new.html
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ja-jp,us-en,de-de,es-es,fr-fr,it-it,pt-br,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Data Infrastructure Insightsのドキュメント
    url: "/index.html"
  - title: 最新情報
    url: "/concept_whats_new.html"
  - title: Data Infrastructure Insightsへのサインアップ
    url: "/task_cloud_insights_onboarding_1.html"
  - title: セキュリティ
    entries:
    - title: セキュリティプラクティス
      url: "/security_overview.html"
    - title: 何をどこに保管するか
      url: "/security_information_and_region.html"
    - title: セキュリティ管理ツール
      url: "/security_admin_tool.html"
  - title: はじめに
    entries:
    - title: データの収集
      entries:
      - title: 概要
        url: "/task_getting_started_with_cloud_insights.html"
      - title: 取得ユニットの要件
        url: "/concept_acquisition_unit_requirements.html"
      - title: 取得ユニットの設定
        url: "/task_configure_acquisition_unit.html"
      - title: Windows/Linux でのエージェントの設定
        url: "/task_config_telegraf_agent.html"
      - title: データコレクターの構成
        url: "/task_configure_data_collectors.html"
      - title: データコレクターの取得ステータスの決定
        url: "/concept_determining_data_collector_acq_status.html"
      - title: 構成されたデータコレクターの管理
        url: "/task_view_configured_data_collectors.html"
      - title: 研究データ収集エラー
        url: "/task_research_failed_collector.html"
    - title: 推奨ダッシュボードのインポート
      url: "/concept_import_from_dashboard_gallery.html"
    - title: ユーザーアカウントとロール
      url: "/concept_user_roles.html"
  - title: データ収集者リスト
    url: "/data_collector_list.html"
  - title: Data Infrastructure Insightsの購読
    url: "/concept_subscribing_to_cloud_insights.html"
  - title: 可観測性
    entries:
    - title: ダッシュボードの作成
      entries:
      - title: ダッシュボードの概要
        url: "/concept_dashboards_overview.html"
      - title: ダッシュボードの機能
        url: "/concept_dashboard_features.html"
      - title: サンプルダッシュボード
        entries:
        - title: 仮想マシンのパフォーマンス
          url: "/task_dashboard_example_VM_performance.html"
      - title: ダッシュボードのベストプラクティス
        url: "/concept_dashboard_best_practices.html"
    - title: クエリの操作
      entries:
      - title: アセットのクエリ
        url: "/concept_querying_assets.html"
      - title: クエリの作成
        url: "/task_create_query.html"
      - title: 利用可能なクエリの表示
        url: "/task_view_queries.html"
      - title: クエリ結果を.CSVにエクスポートする
        url: "/task_export_query_results.html"
      - title: クエリの変更または削除
        url: "/task_modify_delete_query.html"
      - title: オブジェクトに複数のアプリケーション/注釈を割り当てる
        url: "/task_query_assign_multiple_applications.html"
      - title: テーブルの値をクリップボードにコピーする
        url: "/task_query_copy_table_values.html"
      - title: ログのクエリ
        url: "/concept_log_explorer.html"
      - title: 非アクティブなデバイスの識別
        url: "/task_identify_inactive_devices.html"
    - title: 洞察
      entries:
      - title: 概要
        url: "/insights_overview.html"
      - title: ストレス下における共有リソース
        url: "/insights_shared_resources_under_stress.html"
      - title: Kubernetes 名前空間のスペース不足
        url: "/insights_k8s_namespaces_running_out_of_space.html"
      - title: ONTAPコールド ストレージの再利用
        url: "/insights_reclaim_ontap_cold_storage.html"
    - title: モニターとアラート
      entries:
      - title: モニターの作成
        url: "/task_create_monitor.html"
      - title: アラートの表示と管理
        url: "/task_view_and_manage_alerts.html"
      - title: 通知受信者の設定
        url: "/concept_notifications_email.html"
      - title: 異常検出モニター
        url: "/concept_anomaly_detection.html"
      - title: システム定義モニター
        url: "/task_system_monitors.html"
      - title: 通知受信者の設定
        url: "/concept_notifications_email.html"
      - title: Webhook通知
        entries:
        - title: Webhookの設定
          url: "/task_create_webhook.html"
        - title: Webhookの例 - Discord
          url: "/task_webhook_example_discord.html"
        - title: Webhookの例 - PagerDuty
          url: "/task_webhook_example_pagerduty.html"
        - title: Webhookの例 - Slack
          url: "/task_webhook_example_slack.html"
        - title: Webhook の例 - チーム
          url: "/task_webhook_example_teams.html"
    - title: 注釈の操作
      entries:
      - title: 注釈の定義
        url: "/task_defining_annotations.html"
      - title: 注釈の使用
        url: "/task_create_annotation.html"
      - title: 注釈ルールの使用
        url: "/task_create_annotation_rules.html"
      - title: APIを使用したアノテーションのインポート
        url: "/task_annotation_import.html"
    - title: アプリケーションの操作
      entries:
      - title: アプリケーションの概念
        url: "/concept_about_applications.html"
      - title: アプリケーションの構成
        url: "/task_create_application.html"
    - title: 自動デバイス解決
      entries:
      - title: デバイス解像度の概要
        url: "/concept_device_resolution_overview.html"
      - title: デバイス解決ルール
        url: "/task_device_resolution_rules.html"
      - title: ファイバーチャネルデバイスの解像度
        url: "/task_device_resolution_fibre_channel.html"
      - title: IPデバイスの解像度
        url: "/task_device_resolution_ip.html"
      - title: デバイスの解像度の設定
        url: "/task_device_resolution_preferences.html"
      - title: 正規表現の例
        url: "/concept_device_resolution_regex_examples.html"
    - title: 資産ページ情報
      entries:
      - title: 資産ページの概要
        url: "/concept_asset_page_overview.html"
      - title: オブジェクトのコンテキスト内フィルタリング
        url: "/concept_in_context_filters.html"
      - title: ストレージ仮想化
        url: "/concept_storage_virtualization.html"
      - title: 資産検索のヒントとコツ
        url: "/concept_searching_assets.html"
    - title: データの分析
      entries:
      - title: SANアナライザー
        url: "/san_analyzer_overview.html"
      - title: VMアナライザー
        url: "/vm_analyzer_overview.html"
      - title: インフラストラクチャの健全性を監視する
        url: "/monitor_infrastructure_health.html"
    - title: レポート
      entries:
      - title: レポートの概要
        url: "/reporting_overview.html"
      - title: ユーザーロールの報告
        url: "/reporting_user_roles.html"
      - title: 定義済みレポートの使用
        url: "/reporting_predefined_reports.html"
      - title: ストレージマネージャーダッシュボード
        url: "/reporting_storage_manager_dashboard.html"
      - title: サンプルレポートの作成
        url: "/reporting_create_example.html"
      - title: レポートの管理
        url: "/reporting_managing_reports.html"
      - title: カスタム レポート
        url: "/reporting_creating_custom_reports.html"
      - title: データモデル
        url: "/reporting_creating_custom_reports.html#reporting-data-models"
      - title: レポートデータベースAPI
        url: "/reporting_querying_database.html"
      - title: データ保持
        url: "/reporting_data_retention.html"
      - title: スキーマ図
        url: "/reporting_schema_diagrams.html"
      - title: スキーマテーブル
        url: "/reference_schemas.html"
  - title: Kubernetes
    entries:
    - title: Kubernetes 概要ページ
      url: "/kubernetes_landing_page.html"
    - title: オペレーターをインストールまたはアップグレードする前に
      url: "/pre-requisites_for_k8s_operator.html"
    - title: 監視オペレータのインストール
      url: "/task_config_telegraf_agent_k8s.html"
    - title: 監視オペレータオプション
      url: "/telegraf_agent_k8s_config_options.html"
    - title: Kubernetes クラスターページ
      url: "/kubernetes_cluster_detail.html"
    - title: ネットワーク監視とマップ
      url: "/concept_kubernetes_network_monitoring_and_map.html"
    - title: 変更分析
      url: "/kubernetes_change_analytics.html"
  - title: ONTAPエッセンシャル
    url: "/concept_ontap_essentials.html"
  - title: 管理およびその他のタスク
    entries:
    - title: APIの操作
      url: "/API_Overview.html"
    - title: 環境の監視
      entries:
      - title: 監査イベント
        url: "/concept_audit.html"
      - title: TTLとダウンサンプリング
        url: concept_ttl_and_downsampling.html
      - title: Active IQ
        url: "/concept_activeiq.html"
  - title: ワークロードセキュリティ
    entries:
    - title: ワークロードセキュリティについて
      url: "/cs_intro.html"
    - title: はじめに
      entries:
      - title: ワークロードセキュリティ入門
        url: "/task_cs_getting_started.html"
      - title: ワークロード セキュリティ エージェントの要件
        url: "/concept_cs_agent_requirements.html"
      - title: ワークロードセキュリティエージェントの設定
        url: "/task_cs_add_agent.html"
      - title: ワークロードセキュリティエージェントの削除
        url: "/task_cs_delete_agent.html"
      - title: ADディレクトリコレクターの構成
        url: "/task_config_user_dir_connect.html"
      - title: LDAPディレクトリコレクターの設定
        url: "/task_config_user_dir_connect_ldap.html"
      - title: ONTAP SVMデータコレクターの設定
        url: "/task_add_collector_svm.html"
      - title: SVMコレクターのトラブルシューティング
        url: "/troubleshooting_collector_svm.html"
      - title: Cloud ONTAPデータコレクターの設定
        url: "/task_config_cs_incloud.html"
      - title: ワークロードセキュリティユーザー管理
        url: "/task_cs_user_management.html"
      - title: イベント レート チェッカー (エージェント サイジング ガイド)
        url: "/concept_cs_event_rate_checker.html"
    - title: アラート
      url: "/cs_alert_data.html"
    - title: 法医学
      entries:
      - title: アクティビティフォレンジック - すべてのアクティビティ
        url: "/forensic_activity_history.html"
      - title: ユーザ
        url: "/forensic_user_overview.html"
    - title: 自動応答ポリシー
      url: "/cs_automated_response_policies.html"
    - title: 許可されるファイルタイプのポリシー
      url: "/ws_allowed_file_types.html"
    - title: ONTAP自律型ランサムウェア保護の統合
      url: "/concept_cs_integration_with_ontap_arp.html"
    - title: ONTAPアクセス拒否の統合
      url: "/concept_ws_integration_with_ontap_access_denied.html"
    - title: ユーザーアクセスのブロック
      url: "/cs_restrict_user_access.html"
    - title: ランサムウェア攻撃のシミュレーション
      url: "/concept_cs_attack_simulator.html"
    - title: メール通知
      url: "/cs_notifications_email.html"
    - title: Webhook通知
      entries:
      - title: Webhookの作成
        url: "/ws_notifications_using_webhooks.html"
      - title: Discord Webhookの例
        url: "/ws_webhook_example_discord.html"
      - title: PagerDuty Webhookの例
        url: "/ws_webhook_example_pagerduty.html"
      - title: Slack Webhookの例
        url: "/ws_webhook_example_slack.html"
      - title: チームWebhookの例
        url: "/ws_webhook_example_teams.html"
    - title: ワークロードセキュリティAPI
      url: "/concept_cs_api.html"
    - title: SVMコレクターのトラブルシューティング
      url: "/troubleshooting_collector_svm.html"
  - title: トラブルシューティング
    entries:
    - title: 一般的なトラブルシューティング
      url: "/task_troubleshooting_general_problems.html"
    - title: Linux 取得ユニットの問題のトラブルシューティング
      url: "/task_troubleshooting_linux_acquisition_unit_problems.html"
    - title: Windows 取得ユニットの問題のトラブルシューティング
      url: "/task_troubleshooting_windows_acquisition_unit_problems.html"
    - title: データコレクターのエラーの調査
      url: "/task_research_failed_collector.html"
  - title: データコレクターサポートマトリックス
    url: "/reference_data_collector_support_matrix.html"
  - title: リファレンスとサポート
    entries:
    - title: サポートのリクエスト
      url: "/concept_requesting_support.html"
    - title: データコレクターリファレンス - インフラストラクチャ
      entries:
      - title: ベンダーリファレンスの概要
        url: "/concept_data_collector_reference.html"
      - title: AWS
        url: "/task_dc_amazon_ec2.html"
      - title: Amazon FSx for NetApp ONTAP
        url: "/task_dc_na_amazon_fsx.html"
      - title: Azure
        url: "/task_dc_ms_azure.html"
      - title: Broadcom
        entries:
        - title: Brocadeネットワークアドバイザー
          url: "/task_dc_brocade_bna.html"
        - title: ファイバ チャネル スイッチ
          url: "/task_dc_brocade_fc_switch.html"
        - title: BrocadeFOS REST
          url: "/task_dc_brocade_rest.html"
      - title: Cisco
        url: "/task_dc_cisco_fc_switch.html"
      - title: Cohesity スマートファイル
        url: "/task_dc_cohesity_smartfiles.html"
      - title: Dell
        entries:
        - title: XCシリーズ
          url: "/task_dc_dell_xc_series.html"
      - title: Dell EMC
        entries:
        - title: データドメイン
          url: "/task_dc_emc_datadomain.html"
        - title: ECS
          url: "/task_dc_emc_ecs.html"
        - title: パワースケール
          url: "/task_dc_emc_isilon.html"
        - title: アイシロン / パワースケール REST
          url: "/task_dc_emc_isilon_rest.html"
        - title: パワーストア
          url: "/task_dc_emc_powerstore.html"
        - title: リカバリポイント
          url: "/task_dc_emc_recoverpoint.html"
        - title: スケールIO
          url: "/task_dc_emc_scaleio.html"
        - title: ユニティ（VNXe）
          url: "/task_dc_emc_unity.html"
        - title: VMAX/パワーマックス
          url: "/task_dc_emc_vmax_powermax.html"
        - title: VNX ブロック (Clariion)
          url: "/task_dc_emc_vnx_block.html"
        - title: VNX ファイル (Celerra)
          url: "/task_dc_emc_vnx_file.html"
        - title: VNX 統合
          url: "/task_dc_emc_vnx_unified.html"
        - title: VPLEX
          url: "/task_dc_emc_vplex.html"
        - title: エクストリームIO
          url: "/task_dc_emc_xio.html"
      - title: Fujitsu
        url: "/task_dc_fujitsu_eternus.html"
      - title: グーグル
        url: "/task_dc_google_cloud.html"
      - title: Google Cloud NetApp Volumes
        url: "/task_dc_google_cloud_netapp_volumes.html"
      - title: HPエンタープライズ
        entries:
        - title: HP Alletra 9000とPrimera
          url: "/task_dc_hp_3par.html"
        - title: HP コマンドビュー AE
          url: "/task_dc_hpe_commandview.html"
        - title: HPE アレトラ 6000
          url: "/task_dc_hpe_nimble.html"
      - title: 日立データシステムズ
        entries:
        - title: HDS コマンドスイート
          url: "/task_dc_hds_commandsuite.html"
        - title: HDS HNAS
          url: "/task_dc_hds_nas.html"
        - title: HDSオペレーションセンター
          url: "/task_dc_hds_ops_center.html"
      - title: インフィニダット
        url: "/task_dc_infinidat_infinibox.html"
      - title: ファーウェイ
        url: "/task_dc_huawei_oceanstor.html"
      - title: IBM
        entries:
        - title: クレバーセーフ
          url: "/task_dc_ibm_cleversafe.html"
        - title: CSシリーズ
          url: "/task_dc_ibm_cs.html"
        - title: システムストレージ DS8000 シリーズ
          url: "/task_dc_ibm_ds.html"
        - title: PowerVM
          url: "/task_dc_ibm_powervm.html"
        - title: Sanボリュームコントローラ（SVC）
          url: "/task_dc_ibm_svc.html"
        - title: XIV/A9000
          url: "/task_dc_ibm_xiv.html"
      - title: Lenovo
        url: "/task_dc_lenovo.html"
      - title: Microsoft
        entries:
        - title: Azure NetApp Files
          url: "/task_dc_ms_anf.html"
        - title: Hyper-V
          url: "/task_dc_ms_hyperv.html"
      - title: NetApp
        entries:
        - title: Cloud Volumes ONTAP
          url: "/task_dc_na_cloud_volumes_ontap.html"
        - title: AWS 向け Cloud Volumes サービス
          url: "/task_dc_na_cloud_volumes.html"
        - title: ONTAP AFX
          url: "/task_dc_na_ontap_afx.html"
        - title: ONTAP ASA （オールSANアレイ）r2
          url: "/task_dc_na_ontap_all_san_array.html"
        - title: ONTAPデータ管理ソフトウェア
          url: "/task_dc_na_cdot.html"
        - title: ONTAP RESTコレクター
          url: "/task_dc_na_ontap_rest.html"
        - title: Data ONTAP 7モード
          url: "/task_dc_na_7mode.html"
        - title: Eシリーズ
          url: "/task_dc_na_eseries.html"
        - title: EシリーズREST
          url: "/task_dc_netapp_eseries_rest.html"
        - title: NetApp HCI管理サーバー
          url: "/task_dc_na_hci.html"
        - title: SolidFire
          url: "/task_dc_na_solidfire.html"
        - title: StorageGRID
          url: "/task_dc_na_storagegrid.html"
      - title: Nutanix
        url: "/task_dc_nutanix.html"
      - title: Oracle
        url: "/task_dc_oracle_zfs.html"
      - title: Pure
        url: "/task_dc_pure_flasharray.html"
      - title: Red Hat
        url: "/task_dc_redhat_virtualization.html"
      - title: ルーブリックCDM
        url: "/task_dc_rubrik_cdm.html"
      - title: VMware
        url: "/task_dc_vmware.html"
    - title: データコレクターリファレンス - サービス
      entries:
      - title: ホスト/ノード
        url: "/task_config_telegraf_node.html"
      - title: アクティブMQ
        url: "/task_config_telegraf_activemq.html"
      - title: アパッチ
        url: "/task_config_telegraf_apache.html"
      - title: 領事
        url: "/task_config_telegraf_consul.html"
      - title: カウチベース
        url: "/task_config_telegraf_couchbase.html"
      - title: カウチDB
        url: "/task_config_telegraf_couchdb.html"
      - title: Docker
        url: "/task_config_telegraf_docker.html"
      - title: Elasticsearch
        url: "/task_config_telegraf_elasticsearch.html"
      - title: フリンク
        url: "/task_config_telegraf_flink.html"
      - title: Hadoop
        url: "/task_config_telegraf_hadoop.html"
      - title: HAプロキシ
        url: "/task_config_telegraf_haproxy.html"
      - title: Java
        url: "/task_config_telegraf_jvm.html"
      - title: カフカ
        url: "/task_config_telegraf_kafka.html"
      - title: カパシター
        url: task_config_telegraf_kapacitor.html
      - title: キバナ
        url: "/task_config_telegraf_kibana.html"
      - title: Kubernetes
        url: "/task_config_telegraf_agent_k8s.html"
      - title: メムキャッシュ
        url: "/task_config_telegraf_memcached.html"
      - title: MongoDB
        url: "/task_config_telegraf_mongodb.html"
      - title: MySQL
        url: "/task_config_telegraf_mysql.html"
      - title: ネットスタット
        url: "/task_config_telegraf_netstat.html"
      - title: Nginx
        url: "/task_config_telegraf_nginx.html"
      - title: オープンZFS
        url: task_config_telegraf_openzfs.html
      - title: PostgreSQL
        url: "/task_config_telegraf_postgresql.html"
      - title: 人形
        url: "/task_config_telegraf_puppetagent.html"
      - title: レディス
        url: "/task_config_telegraf_redis.html"
      - title: DBを再考する
        url: task_config_telegraf_rethinkdb.html
      - title: 動物園の飼育員
        url: task_config_telegraf_zookeeper.html
    - title: オブジェクトアイコンリファレンス
      url: "/reference_object_icons.html"
  - title: 法律上の表示
    url: "/legal-notices.html"
