---
sidebar: sidebar 
permalink: reporting_overview.html 
summary: Data Infrastructure Insightsを使用した、データの事前定義済みレポートとカスタム レポート。 
keywords: reporting, cognos, data warehouse, dwh 
---
= Data Infrastructure Insightsレポートの概要
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsレポートは、定義済みレポートを表示したり、カスタム レポートを作成したりできるビジネス インテリジェンス ツールです。


NOTE: レポート機能は、Data Infrastructure Insightsで利用できます。link:concept_subscribing_to_cloud_insights.html["プレミアムエディション"] 。レポート機能の利用には、最小フットプリント要件が適用されます。link:https://www.netapp.com/forms/cloud-insights-contact-us/["NetAppの営業担当者にお問い合わせください"]詳細についてはこちらをご覧ください。

Data Infrastructure Insightsレポートを使用すると、次のタスクを実行できます。

* 定義済みレポートを実行する
* カスタムレポートを作成する
* レポートの形式と配信方法をカスタマイズする
* レポートを自動的に実行するようにスケジュールする
* メールレポート
* データのしきい値を色で表す


Data Infrastructure Insights Reporting は、チャージバック、消費分析、予測などの領域に関するカスタム レポートを生成し、次のような質問に答えるのに役立ちます。

* どのような在庫がありますか?
* 私の在庫はどこにありますか?
* 私たちの資産を使っているのは誰ですか?
* ビジネス ユニットに割り当てられたストレージのチャージバックとは何ですか?
* 追加のストレージ容量を取得する必要があるまでどのくらいかかりますか?
* ビジネス ユニットは適切なストレージ層に沿って配置されていますか?
* ストレージの割り当ては、1 か月、四半期、または 1 年にわたってどのように変化していますか?




== Data Infrastructure Insightsサイトレポートへのアクセス

メニューの*レポート*リンクをクリックすると、 Data Infrastructure Insightsレポートにアクセスできます。

レポート インターフェースに移動します。  Data Infrastructure Insights は、レポート エンジンとして IBM Cognos Analytics を使用します。



== ETL とは何ですか?

レポートを扱うときには、「データ ウェアハウス」と「ETL」という用語を耳にするでしょう。  ETL は「抽出、変換、ロード」の略です。  ETL プロセスは、 Data Infrastructure Insightsで収集されたデータを取得し、そのデータをレポートで使用できる形式に変換します。  「データ ウェアハウス」とは、レポートに使用できる収集されたデータを指します。

ETL プロセスには、次の個別のプロセスが含まれます。

* *抽出*: Data Infrastructure Insightsからデータを取得します。
* *変換*: Data Infrastructure Insightsから抽出されたデータにビジネス ロジック ルールまたは関数を適用します。
* *ロード*: レポートで使用するために、変換されたデータをデータ ウェアハウスに保存します。

