---
sidebar: sidebar 
permalink: reporting_creating_custom_reports.html 
summary: レポート作成ツールを使用してカスタム（「アドホック」）レポートを作成する 
keywords: reporting, cognos, data warehouse, dwh, ad-hoc, custom 
---
= カスタムレポートの作成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
レポート作成ツールを使用してカスタム レポートを作成できます。レポートを作成したら、それを保存し、定期的に実行することができます。レポートの結果は、自分自身や他の人に電子メールで自動的に送信できます。


NOTE: レポート機能は、Data Infrastructure Insightsで利用できます。link:concept_subscribing_to_cloud_insights.html["プレミアムエディション"] 。

このセクションの例では、 Data Infrastructure Insights Reporting のデータ モデルのいずれかに使用できる次のプロセスを示します。

* レポートで回答すべき質問を特定する
* 結果を裏付けるために必要なデータの決定
* レポートのデータ要素の選択


カスタム レポートを設計する前に、いくつかの前提条件となるタスクを完了する必要があります。これらを完了しないと、レポートが不正確または不完全になる可能性があります。

たとえば、デバイス識別プロセスを完了しないと、容量レポートは正確ではなくなります。または、注釈 (層、ビジネス ユニット、データ センターなど) の設定を完了しないと、カスタム レポートでドメイン全体のデータが正確にレポートされなかったり、一部のデータ ポイントに「N/A」と表示されたりする可能性があります。

レポートを設計する前に、次のタスクを完了します。

* すべて設定link:task_configure_data_collectors.html["データ収集者"]きちんと。
* テナント上のデバイスとリソースに注釈 (階層、データ センター、ビジネス ユニットなど) を入力します。  Data Infrastructure Insights Reporting は履歴情報を収集するため、レポートを生成する前に注釈を安定させておくことは有益です。




== レポート作成プロセス

カスタム (「アドホック」とも呼ばれる) レポートを作成するプロセスには、いくつかのタスクが含まれます。

* レポートの結果を計画します。
* 結果を裏付けるデータを特定します。
* データが含まれているデータ モデル (たとえば、チャージバック データ モデル、インベントリ データ モデルなど) を選択します。
* レポートのデータ要素を選択します。
* 必要に応じて、レポートの結果をフォーマット、並べ替え、フィルタリングします。




=== カスタムレポートの結果を計画する

レポート作成ツールを開く前に、レポートから得たい結果を計画しておくとよいでしょう。レポート作成ツールを使用すると、レポートを簡単に作成でき、多くの計画を立てる必要がない場合もありますが、レポートの要求者からレポートの要件について把握しておくことをお勧めします。

* 回答したい質問を正確に特定します。例えば：
+
** どれくらいの容量が残っていますか?
** 事業単位あたりのチャージバックコストはいくらですか?
** ビジネス ユニットが適切なストレージ層に揃えられるようにするための層別の容量はどのくらいですか。
** 電力と冷却の要件を予測するにはどうすればよいでしょうか?  (リソースに注釈を追加して、カスタマイズされたメタデータを追加します。)


* 回答を裏付けるために必要なデータ要素を特定します。
* 回答で確認したいデータ間の関係を特定します。質問には非論理的な関係を含めないでください。たとえば、「容量に関連するポートを確認したい」などです。
* データに必要な計算を特定します。
* 結果を制限するために必要なフィルタリングの種類を決定します。
* 現在のデータまたは履歴データを使用する必要があるかどうかを決定します。
* データを特定の対象者に制限するためにレポートにアクセス権限を設定する必要があるかどうかを決定します。
* レポートの配布方法を特定します。たとえば、設定されたスケジュールに従って電子メールで送信するか、チームのコンテンツ フォルダー領域に含める必要がありますか?
* レポートを保守する担当者を決定します。これは設計の複雑さに影響する可能性があります。
* レポートのモックアップを作成します。




=== レポート設計のヒント

レポートを設計するときに役立つヒントがいくつかあります。

* 現在のデータまたは履歴データのどちらを使用する必要があるかを判断します。
+
ほとんどのレポートでは、Data Infrastructure Insightsで利用可能な最新のデータについてのみレポートする必要があります。

* Data Infrastructure Insightsサイト レポートでは、容量とパフォーマンスに関する履歴情報は提供されますが、インベントリに関する情報は提供されません。
* すべてのユーザーはすべてのデータを見ることができますが、特定の対象ユーザーにデータを制限する必要がある場合があります。
+
異なるユーザーの情報をセグメント化するには、レポートを作成し、それらにアクセス権限を設定できます。





== レポートデータモデル

Data Infrastructure Insightsには複数のデータ モデルが含まれており、そこから定義済みレポートを選択したり、独自のカスタム レポートを作成したりできます。

各データ モデルには、単純なデータ マートと高度なデータ マートが含まれています。

* シンプル データ マートは、最も一般的に使用されるデータ要素への迅速なアクセスを提供し、データ ウェアハウス データの最新のスナップショットのみを含み、履歴データは含みません。
* 高度なデータ マートは、単純なデータ マートから入手できるすべての値と詳細を提供し、履歴データ値へのアクセスも含まれます。




=== 容量データモデル

ストレージ容量、ファイル システムの使用率、内部ボリューム容量、ポート容量、qtree 容量、仮想マシン (VM) 容量に関する質問に答えることができます。容量データ モデルは、複数の容量データ モデルのコンテナーです。このデータ モデルを使用して、さまざまな種類の質問に答えるレポートを作成できます。



==== ストレージとストレージプール容量データモデル

ストレージおよびストレージ プールを含むストレージ容量リソース計画に関する質問に答えることができ、物理ストレージ プール データと仮想ストレージ プール データの両方が含まれます。このシンプルなデータ モデルは、フロア容量や、一定期間にわたる階層別およびデータ センター別のストレージ プールの容量使用状況に関する質問に答えるのに役立ちます。容量レポートを初めて使用する場合は、よりシンプルでターゲットを絞ったこのデータ モデルから始めることをお勧めします。このデータ モデルを使用すると、次のような質問に答えることができます。

* 物理ストレージの容量しきい値 80% に達する予定日はいつですか?
* 特定の層のアレイ上の物理的なストレージ容量はどれくらいですか?
* メーカー別、ファミリ別、データ センター別のストレージ容量はどれくらいですか?
* すべての層のアレイ上のストレージ使用率の傾向はどうですか?
* 使用率が最も高い上位 10 のストレージ システムは何ですか?
* ストレージ プールのストレージ使用率の傾向はどうですか?
* すでにどのくらいの容量が割り当てられていますか?
* 割り当て可能な容量はどれくらいですか?




==== ファイルシステム使用率データモデル

このデータ モデルは、ファイル システム レベルでのホストの容量使用率に関する可視性を提供します。管理者は、ファイル システムごとに割り当てられた容量と使用済み容量を決定し、ファイル システムのタイプを判別し、ファイル システム タイプ別の傾向統計を特定できます。このデータ モデルを使用すると、次の質問に答えることができます。

* ファイルシステムのサイズはどれくらいですか?
* データはどこに保存され、どのようにアクセスされますか (ローカル、SAN など)?
* ファイルシステム容量の過去の傾向は何ですか? それでは、これに基づいて、将来のニーズについて何を予測できるでしょうか?




==== 内部ボリューム容量データモデル

内部ボリュームの使用済み容量、割り当て済み容量、および時間の経過に伴う容量使用状況に関する質問に答えることができます。

* 事前定義されたしきい値よりも使用率が高い内部ボリュームはどれですか?
* 傾向に基づいて、どの内部ボリュームが容量不足になる危険がありますか?  8 内部ボリュームの使用容量と割り当て容量はどれくらいですか?




==== ポート容量データモデル

スイッチ ポートの接続性、ポートの状態、およびポート速度に関する質問に時間の経過とともに回答できるようになります。新しいスイッチの購入計画を立てる際に役立つ、次のような質問に答えることができます。リソース (ポート) の可用性 (データ センター、スイッチ ベンダー、ポート速度に応じて) を予測するポート消費予測を作成するにはどうすればよいですか?

* データ速度、データセンター、ベンダー、ホストおよびストレージ ポートの数を考慮すると、どのポートの容量が不足する可能性が高いですか。
* スイッチ ポート容量の傾向は時間とともにどう変化しますか?
* ポート速度はどれくらいですか?
* どのようなタイプのポート容量が必要であり、どの組織で特定のポート タイプまたはベンダーが不足しつつありますか。
* その容量を購入して利用可能にする最適な時期はいつでしょうか?




==== Qtree 容量データモデル

時間の経過に伴う qtree 使用率の傾向 (使用済み容量と割り当て済み容量などのデータ) を把握できます。ビジネス エンティティ、アプリケーション、層、サービス レベルなど、さまざまなディメンション別に情報を表示できます。このデータ モデルを使用すると、次の質問に答えることができます。

* アプリケーションまたはビジネス エンティティごとに設定された制限に対する qtree の使用容量はどれくらいですか?
* 容量計画を立てるために、使用済み容量と空き容量の傾向を把握してください。
* 最も多くの容量を使用している事業体はどれですか?
* 最も多くの容量を消費するアプリケーションはどれですか?




==== VM容量データモデル

仮想環境とその容量使用状況をレポートできます。このデータ モデルを使用すると、VM およびデータ ストアの容量使用量の経時的な変化をレポートできます。データ モデルは、シン プロビジョニングと仮想マシンのチャージバック データも提供します。

* VM およびデータ ストアにプロビジョニングされた容量に基づいて容量チャージバックを決定するにはどうすればよいですか?
* VM によって使用されていない容量はどれですか。また、未使用の容量のうち、空き容量、孤立容量、その他の容量はどれですか。
* 消費動向を踏まえて何を購入すべきでしょうか？
* ストレージ シン プロビジョニングと重複排除テクノロジを使用することで、どの程度のストレージ効率の節約が達成されますか?


VM 容量データ モデルの容量は、仮想ディスク (VMDK) から取得されます。つまり、VM 容量データ モデルを使用してプロビジョニングされた VM のサイズは、その仮想ディスクのサイズになります。これは、VM 自体のプロビジョニングされたサイズを表示する、 Data Infrastructure Insightsの仮想マシン ビューのプロビジョニングされた容量とは異なります。



==== ボリューム容量データモデル

テナント上のボリュームのあらゆる側面を分析し、ベンダー、モデル、層、サービス レベル、データ センターごとにデータを整理できます。

孤立ボリューム、未使用ボリューム、保護ボリューム (レプリケーションに使用) に関連する容量を表示できます。また、さまざまなボリューム テクノロジ (iSCSI または FC) を確認し、アレイ仮想化の問題について仮想ボリュームと非仮想ボリュームを比較することもできます。

このデータ モデルを使用すると、次のような質問に答えることができます。

* 事前定義されたしきい値よりも使用率が高いボリュームはどれですか?
* データセンターにおける孤立ボリュームの容量の傾向はどうなっていますか?
* データセンターの容量のうち、どれくらいが仮想化またはシンプロビジョニングされていますか?
* データセンターの容量のどれくらいをレプリケーション用に予約する必要がありますか?




=== チャージバックデータモデル

ストレージ リソース (ボリューム、内部ボリューム、qtree) の使用済み容量と割り当て済み容量に関する質問に答えることができます。このデータ モデルは、ホスト、アプリケーション、ビジネス エンティティ別のストレージ容量のチャージバックとアカウンタビリティ情報を提供し、現在のデータと履歴データの両方を含みます。レポート データは、サービス レベルとストレージ層別に分類できます。

このデータ モデルを使用すると、ビジネス エンティティによって使用されている容量の量を調べて、チャージバック レポートを生成できます。このデータ モデルを使用すると、複数のプロトコル (NAS、SAN、FC、iSCSI など) の統合レポートを作成できます。

* 内部ボリュームのないストレージの場合、チャージバック レポートにはボリュームごとのチャージバックが表示されます。
* 内部ボリュームを持つストレージの場合:
+
** ビジネス エンティティがボリュームに割り当てられている場合、チャージバック レポートにはボリューム別のチャージバックが表示されます。
** ビジネス エンティティがボリュームに割り当てられておらず、qtree に割り当てられている場合、チャージバック レポートには qtree ごとのチャージバックが表示されます。
** ビジネス エンティティがボリュームに割り当てられておらず、qtree にも割り当てられていない場合、チャージバック レポートには内部ボリュームが表示されます。
** チャージバックをボリューム、qtree、または内部ボリューム別に表示するかどうかの決定は各内部ボリュームごとに行われるため、同じストレージ プール内の異なる内部ボリュームに異なるレベルでチャージバックが表示される可能性があります。




容量ファクトは、デフォルトの時間間隔が経過すると消去されます。詳細については、データ ウェアハウス プロセスを参照してください。

チャージバック データ モデルを使用するレポートでは、ストレージ容量 データ モデルを使用するレポートとは異なる値が表示される場合があります。

* NetAppストレージ システム以外のストレージ アレイの場合、両方のデータ モデルのデータは同じです。
* NetAppおよび Celerra ストレージ システムの場合、チャージバック データ モデルは単一レイヤー (ボリューム、内部ボリューム、または qtree) を使用して料金を算出しますが、ストレージ容量データ モデルは複数レイヤー (ボリュームおよび内部ボリューム) を使用して料金を算出します。




=== 在庫データモデル

ホスト、ストレージ システム、スイッチ、ディスク、テープ、qtree、クォータ、仮想マシンとサーバー、汎用デバイスなどのインベントリ リソースに関する質問に答えることができます。インベントリ データ モデルには、レプリケーション、FC パス、iSCSI パス、NFS パス、違反に関する情報を表示できるサブマートがいくつか含まれています。在庫データ モデルには履歴データは含まれません。このデータで答えられる質問

* どのような資産を所有しており、それらはどこにあるのでしょうか?
* 資産を使用しているのは誰ですか?
* 所有しているデバイスの種類と、それらのデバイスのコンポーネントは何ですか?
* OS ごとにホストがいくつあり、それらのホストにはポートがいくつありますか?
* 各データ センターにはベンダーごとにどのようなストレージ アレイが存在しますか?
* 各データセンターにはベンダーごとにいくつのスイッチがありますか?
* ライセンスされていないポートはいくつありますか?
* どのベンダーのテープを使用していますか? また、各テープにはいくつのポートがありますか? レポートの作業を開始する前に、すべての汎用デバイスが識別されていますか?
* ホストとストレージ ボリュームまたはテープ間のパスは何ですか?
* 汎用デバイスとストレージ ボリュームまたはテープ間のパスは何ですか?
* データセンターごとに各タイプの違反がいくつありますか?
* 複製されたボリュームごとに、ソース ボリュームとターゲット ボリュームは何ですか?
* ファイバー チャネル ホスト HBA とスイッチ間でファームウェアの非互換性やポート速度の不一致はありますか?




=== パフォーマンスデータモデル

ボリューム、アプリケーション ボリューム、内部ボリューム、スイッチ、アプリケーション、VM、VMDK、ESX と VM、ホスト、およびアプリケーション ノードのパフォーマンスに関する質問に答えることができます。これらの多くは、_時間別_データ、_日別_データ、またはその両方を報告します。このデータ モデルを使用すると、パフォーマンス管理に関するさまざまな質問に答えるレポートを作成できます。

* 特定の期間に使用またはアクセスされていないボリュームまたは内部ボリュームはどれですか?
* アプリケーションのストレージ (未使用) の潜在的な構成ミスを特定できますか?
* アプリケーションの全体的なアクセス動作パターンは何でしたか?
* 階層化されたボリュームは特定のアプリケーションに適切に割り当てられていますか?
* アプリケーションのパフォーマンスに影響を与えずに、現在実行中のアプリケーションに安価なストレージを使用できますか?
* 現在構成されているストレージへのアクセスを多く生成しているアプリケーションは何ですか?


スイッチ パフォーマンス テーブルを使用すると、次の情報を取得できます。

* 接続されたポートを経由するホスト トラフィックはバランスが取れていますか?
* どのスイッチまたはポートでエラー数が多くなっていますか?
* ポートのパフォーマンスに基づいて最も使用されているスイッチは何ですか?
* ポートのパフォーマンスに基づいて、十分に活用されていないスイッチは何ですか?
* ポートのパフォーマンスに基づくホストのスループットの傾向は何ですか?
* 指定されたホスト、ストレージ システム、テープ、またはスイッチの過去 X 日間のパフォーマンス使用率はどれくらいですか?
* 特定のスイッチでトラフィックを生成しているデバイスはどれですか (たとえば、使用率の高いスイッチの使用に関与しているデバイスはどれですか)。
* 私たちの環境における特定のビジネス ユニットのスループットはどのくらいですか?


ディスク パフォーマンス テーブルを使用すると、次の情報を取得できます。

* ディスク パフォーマンス データに基づく、指定されたストレージ プールのスループットはどれくらいですか?
* 最も使用されているストレージ プールは何ですか?
* 特定のストレージの平均ディスク使用率はどれくらいですか?
* ディスク パフォーマンス データに基づくストレージ システムまたはストレージ プールの使用傾向はどのようなものですか?
* 特定のストレージ プールのディスク使用率の傾向はどうですか?


VM および VMDK パフォーマンス テーブルを使用すると、次の情報を取得できます。

* 仮想環境は最適に動作していますか?
* 最も高いワークロードを報告している VMDK はどれですか?
* 異なるデータストアにマップされた VMD から報告されたパフォーマンスを使用して、再階層化に関する決定を行うにはどうすればよいですか。


パフォーマンス データ モデルには、層の適切性、アプリケーションのストレージの誤った構成、ボリュームと内部ボリュームの最終アクセス時刻を判断するのに役立つ情報が含まれています。このデータ モデルは、応答時間、IOPS、スループット、保留中の書き込み数、アクセス状態などのデータを提供します。



=== ストレージ効率データモデル

ストレージ効率スコアと潜在能力を時間の経過とともに追跡できます。このデータ モデルには、プロビジョニングされた容量だけでなく、使用または消費された量 (物理測定) の測定値も保存されます。たとえば、シン プロビジョニングが有効になっている場合、 Data Infrastructure Insights はデバイスから取得される容量を示します。このモデルを使用して、重複排除が有効になっている場合の効率を判断することもできます。  Storage Efficiency データ マートを使用すると、さまざまな質問に答えることができます。

* シン プロビジョニングと重複排除テクノロジを実装した結果、ストレージ効率はどの程度節約できるでしょうか。
* データセンター全体のストレージ節約量はどのくらいですか?
* 過去の容量傾向に基づくと、いつ追加のストレージを購入する必要がありますか?
* シン プロビジョニングや重複排除などのテクノロジーを有効にした場合、容量はどの程度増加しますか?
* ストレージ容量に関しては、現在リスクがありますか?




=== データモデルのファクトテーブルとディメンションテーブル

各データ モデルには、ファクト テーブルとディメンション テーブルの両方が含まれます。

* ファクト テーブル: 数量、生容量、使用可能容量など、測定されたデータが含まれます。ディメンション テーブルへの外部キーが含まれます。
* ディメンション テーブル: データ センターやビジネス ユニットなどのファクトに関する説明情報が含まれます。ディメンションは、データを分類する構造であり、多くの場合、階層で構成されます。ディメンション属性はディメンション値を記述するのに役立ちます。


異なるまたは複数のディメンション属性 (レポートでは列として表示) を使用して、データ モデルに記述されている各ディメンションのデータにアクセスするレポートを作成します。



=== データモデル要素で使用される色

データ モデル要素の色にはさまざまな表示があります。

* 黄色のアセット: 測定値を表します。
* 黄色以外の資産: 属性を表します。これらの値は集計されません。




=== 1つのレポートで複数のデータモデルを使用する

通常、レポートごとに 1 つのデータ モデルを使用します。ただし、複数のデータ モデルのデータを組み合わせたレポートを作成することはできます。

複数のデータ モデルのデータを組み合わせたレポートを作成するには、ベースとして使用するデータ モデルの 1 つを選択し、追加のデータ マートのデータにアクセスするための SQL クエリを記述します。  SQL 結合機能を使用すると、さまざまなクエリからのデータを 1 つのクエリに結合し、レポートの作成に使用できます。

たとえば、各ストレージ アレイの現在の容量が必要で、アレイのカスタム注釈をキャプチャするとします。ストレージ容量データ モデルを使用してレポートを作成できます。現在の容量とディメンション テーブルの要素を使用し、別の SQL クエリを追加して、在庫データ モデル内の注釈情報にアクセスできます。最後に、ストレージ名と結合条件を使用して、在庫ストレージ データをストレージ ディメンション テーブルにリンクすることで、データを結合できます。
