---
sidebar: sidebar 
permalink: security_overview.html 
summary: Data Infrastructure Insightsは、リリースのライフサイクル全体を通じてセキュリティのベストプラクティスに準拠しています。 
keywords: security, risk, protection 
---
= データインフラ分析情報のセキュリティ
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ネットアップでは、製品とお客様にデータセキュリティを最大限に活用することが何よりも重要です。Data Infrastructure Insightsは、リリースのライフサイクル全体を通じてセキュリティのベストプラクティスに従い、可能な限り最善の方法でお客様の情報とデータを確実に保護します。



== セキュリティの概要



=== 物理的セキュリティ

Data Infrastructure Insightsの本番インフラは、Amazon Web Services（AWS）でホストされています。Data Infrastructure Insights本番サーバの物理的および環境的なセキュリティ関連の制御（建物やドアで使用されるロックやキーなど）は、AWSによって管理されます。AWS によると、「ビデオ監視、侵入検知システム、その他の電子的手段を利用して、専門のセキュリティスタッフが、境界と建物の両方で物理アクセスを制御します。認定スタッフは、多要素認証メカニズムを利用してデータセンターのフロアにアクセスします。」

Data Infrastructure Insightsは、link:https://aws.amazon.com/compliance/shared-responsibility-model/["共有責任モデル"]AWSで説明されているのベストプラクティスに従っています。



=== 製品のセキュリティ

Data Infrastructure Insightsは、アジャイルの原則に沿った開発ライフサイクルに従います。そのため、リリースサイクルの長い開発手法と比較して、セキュリティ志向のソフトウェアの不具合に迅速に対処することができます。継続的な統合手法を使用することで、機能とセキュリティの両方の変化に迅速に対応できます。変更管理手順とポリシーは、変更がいつどのように発生するかを定義し、本番環境の安定性を維持するのに役立ちます。インパクトのある変更は、正式に伝達され、調整され、適切にレビューされ、本番環境にリリースされる前に承認されます。



=== ネットワークセキュリティ

Data Infrastructure Insights環境内のリソースへのネットワークアクセスは、ホストベースのファイアウォールによって制御されます。各リソース（ロードバランサや仮想マシンインスタンスなど）にはホストベースのファイアウォールがあり、インバウンドトラフィックを、そのリソースが機能を実行するために必要なポートだけに制限します。

Data Infrastructure Insightsは、侵入検出サービスなどのさまざまなメカニズムを使用して、本番環境のセキュリティ異常を監視します。



=== リスク評価

Data Infrastructure Insightsチームは、形式化されたリスクアセスメントプロセスに従い、リスクを特定して評価する体系的で反復可能な方法を提供し、リスクをリスク治療計画を通じて適切に管理できるようにします。



=== データ保護

Data Infrastructure Insights本番環境は、すべてのサービスとコンポーネントに対して複数のアベイラビリティゾーンを使用して、非常に冗長なインフラ内にセットアップされます。可用性の高い冗長なコンピューティングインフラを利用するとともに、重要なデータを定期的にバックアップし、リストアを定期的にテストします。正式なバックアップ・ポリシーと手順により ' ビジネス・アクティビティの中断による影響を最小限に抑え ' 情報システムや災害の影響からビジネス・プロセスを保護し ' 適切なタイミングで適切な再開を実現します



=== 認証およびアクセス管理

Data Infrastructure Insightsへのすべてのアクセスは、HTTPSを介したブラウザUIの操作を通じて行われます。認証は、サードパーティのサービスである Auth0 を介して行われます。ネットアップでは、すべてのクラウドデータサービスの認証レイヤとして、この機能を一元化しています。

Data Infrastructure Insightsは、Data Infrastructure Insights本番環境への論理アクセスに関する「最小権限」や「ロールベースアクセス制御」など、業界のベストプラクティスに従っています。アクセスは厳密な必要性に基づいて制御され、多要素認証メカニズムを使用する一部の承認された担当者にのみ許可されます。



=== お客様のデータの収集と保護

すべてのお客様のデータは、パブリックネットワークを経由して転送中に暗号化され、保存中に暗号化されます。Data Infrastructure Insightsは、システム内のさまざまなポイントでの暗号化を利用して、Transport Layer Security（TLS）や業界標準のAES-256アルゴリズムなどのテクノロジを使用してお客様のデータを保護します。



=== 顧客のプロビジョニング解除

E メール通知はさまざまな間隔で送信され、お客様のサブスクリプションが期限切れになることを通知します。サブスクリプションの期限が切れると、 UI は制限され、データ収集の猶予期間が始まります。その後、お客様に E メールで通知します。トライアルサブスクリプションには 14 日間の猶予期間があり、有料サブスクリプションアカウントには 28 日間の猶予期間があります。猶予期間が終了すると、お客様にはアカウントが 2 日以内に削除されることを電子メールで通知します。有料のお客様は、サービスを利用しないよう直接リクエストすることもできます。

期限切れのテナントと関連するすべての顧客データは、猶予期間の終了時、またはお客様からアカウントの終了を要求されたことを確認した時点で、Data Infrastructure Insights Operations（SRE）チームによって削除されます。どちらの場合も、 SRE チームは API 呼び出しを実行してアカウントを削除します。API 呼び出しで、テナントインスタンスとすべての顧客データが削除されます。カスタマーの削除は、同じ API を呼び出し、カスタマーテナントのステータスが「削除済み」であることを確認することで確認できます。



=== セキュリティインシデント管理

Data Infrastructure Insightsは、NetAppの製品セキュリティインシデント対応チーム（PSIRT）プロセスと統合されており、既知の脆弱性を検出、評価、解決します。PSIRT は、カスタマーレポート、内部エンジニアリング、 CVE データベースなどの広く認識されているソースなど、複数のチャネルから脆弱性情報を取得します。

Data Infrastructure Insightsエンジニアリングチームが問題を検出した場合、チームはPSIRTプロセスを開始し、問題を評価し、潜在的に修正します。

また、Data Infrastructure Insightsのお客様やリサーチャーは、Data Infrastructure Insights製品のセキュリティ上の問題を特定し、テクニカルサポートまたはNetAppのインシデント対応チームに直接報告することもできます。このような場合は、Data Infrastructure InsightsチームがPSIRTプロセスを開始し、問題を評価して、潜在的に修正します。



=== 脆弱性および侵入テスト

Data Infrastructure Insightsは、業界のベストプラクティスに従い、社内外のセキュリティ専門家や企業を使用して定期的に脆弱性と侵入テストを実施します。



=== セキュリティ認識トレーニング

Data Infrastructure Insightsのすべての担当者は、それぞれの役割に応じて開発されたセキュリティトレーニングを受けています。これにより、各担当者は、それぞれの役割に固有のセキュリティ関連の課題に対処できるようになります。



=== コンプライアンス

Data Infrastructure Insightsは、セキュリティ、プロセス、サービスについて外部の公認会計士事務所から独立した第三者監査および検証を実施しています。これには、SOC 2監査の完了も含まれます。



=== NetAppセキュリティアドバイザリ

NetAppで利用可能なセキュリティアドバイザリを表示できますlink:https://security.netapp.com/advisory/["ここをクリック"]。
