---
sidebar: sidebar 
permalink: task_dc_amazon_ec2.html 
keywords: data collector, EC2, 
summary: Amazon EC2 データコレクターを構成します。 
---
= Amazon EC2 データコレクターの設定
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Amazon EC2 データコレクターを使用して、EC2 インスタンスからインベントリとパフォーマンスデータを取得します。



== 要件

Amazon EC2 デバイスからデータを収集するには、次の情報が必要です。

* 次のいずれかが必要です。
+
** IAM ロール認証を使用している場合は、Amazon EC2 クラウド アカウントの *IAM ロール*。  IAM ロールは、取得ユニットが AWS インスタンスにインストールされている場合にのみ適用されます。
** IAM アクセスキー認証を使用している場合は、Amazon EC2 クラウドアカウントの *IAM アクセスキー* ID とシークレットアクセスキー。


* 「リスト組織」権限が必要です
* ポート443 HTTPS
* EC2 インスタンスは、仮想マシン、または (あまり自然ではないが) ホストとして報告できます。  EBS ボリュームは、VM によって使用される仮想ディスクとしてだけでなく、仮想ディスクの容量を提供するデータストアとしても報告できます。


アクセス キーは、アクセス キー ID (例: AKIAIOSFODNN7EXAMPLE) とシークレット アクセス キー (例: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) で構成されます。 Amazon EC2 SDK、REST、またはクエリ API オペレーションを使用する場合は、アクセスキーを使用して EC2 に対して行うプログラムによるリクエストに署名します。これらのキーは、Amazon との契約で提供されます。



== 構成

以下の表に従って、データ コレクター フィールドにデータを入力します。

[cols="2*"]
|===
| フィールド | 説明 


| AWS Region | AWSリージョンを選択 


| IAM ロール | AWS の AU で取得した場合のみ使用できます。詳細については以下をご覧ください。<<iam-role,IAM ロール>> 。 


| AWS IAM Access Key ID | AWS IAM アクセスキー ID を入力します。  IAM ロールを使用しない場合は必須です。 


| AWS IAM シークレットアクセスキー | AWS IAM シークレットアクセスキーを入力します。  IAM ロールを使用しない場合は必須です。 


| AWSがAPIリクエストに対して料金を請求することを理解しています | これをチェックして、 Data Infrastructure Insightsポーリングによって行われた API リクエストに対して AWS が課金することを理解していることを確認します。 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 説明 


| 追加リージョンを含める | ポーリングに含める追加の地域を指定します。 


| クロスアカウントロール | 異なる AWS アカウントのリソースにアクセスするためのロール。 


| インベントリポーリング間隔（分） | デフォルトは60です 


| タグによる VM のフィルタリングを適用するには、「除外」または「含める」を選択します | データを収集するときに、タグによって VM を含めるか除外するかを指定します。  「含める」を選択した場合、タグ キー フィールドを空にすることはできません。 


| VM をフィルタリングするためのタグキーと値 | *+ フィルター タグ* をクリックし、VM 上のタグのキーと値に一致するキーと値をフィルターして、含める/除外する VM (および関連ディスク) を選択します。タグキーは必須ですが、タグ値はオプションです。タグ値が空の場合、タグ キーと一致する限り VM はフィルタリングされます。 


| パフォーマンスポーリング間隔（秒） | デフォルトは1800です 


| CloudWatch エージェントメトリクス名前空間 | データを収集する EC2/EBS 内の名前空間。この名前空間内のデフォルトのメトリックの名前が変更された場合、 Data Infrastructure Insights は名前が変更されたデータを収集できない可能性があることに注意してください。デフォルトのメトリック名のままにしておくことをお勧めします。 
|===


== IAMアクセス キー

アクセスキーは、IAM ユーザーまたは AWS アカウントのルートユーザーの長期的な認証情報です。アクセスキーは、AWS CLI または AWS API へのプログラムによるリクエスト (直接または AWS SDK を使用) に署名するために使用されます。

アクセス キーは、アクセス キー ID とシークレット アクセス キーの 2 つの部分で構成されます。 _IAM アクセスキー_ 認証を使用する場合 (_IAM ロール_ 認証ではなく)、リクエストの認証にアクセスキー ID とシークレットアクセスキーの両方を併用する必要があります。詳細については、Amazonのドキュメントをご覧ください。link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["アクセスキー"] 。



== IAM ロール

_IAM ロール_ 認証 (IAM アクセスキー認証ではなく) を使用する場合は、作成または指定するロールに、リソースにアクセスするために必要な適切な権限があることを確認する必要があります。

たとえば、_InstanceEc2ReadOnly_ という名前の IAM ロールを作成する場合は、この IAM ロールのすべての EC2 リソースに対する EC2 読み取り専用リストアクセス権限を付与するポリシーを設定する必要があります。さらに、このロールがアカウント間でロールを引き受けることができるように、STS (セキュリティ トークン サービス) アクセスを付与する必要があります。

IAM ロールを作成したら、新しい EC2 インスタンスまたは既存の EC2 インスタンスを作成するときにその IAM ロールをアタッチできます。

IAM ロール _InstanceEc2ReadOnly_ を EC2 インスタンスにアタッチすると、IAM ロール名でインスタンス メタデータを通じて一時的な認証情報を取得し、それを使用してこの EC2 インスタンスで実行されている任意のアプリケーションから AWS リソースにアクセスできるようになります。

詳細については、Amazonのドキュメントをご覧ください。link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles.html["IAM ロール"] 。

注意: IAM ロールは、Acquisition Unit が AWS インスタンスで実行されている場合にのみ使用できます。



== Amazon タグをData Infrastructure Insightsアノテーションにマッピングする

Amazon EC2 データコレクターには、EC2 で設定されたタグを使用してData Infrastructure Insights の注釈を入力できるオプションが含まれています。アノテーションの名前は EC2 タグとまったく同じにする必要があります。 Data Infrastructure Insights は、常に同じ名前のテキスト タイプの注釈を入力し、他のタイプ (数値、ブール値など) の注釈を入力するように「最善の試み」を行います。注釈が別のタイプであり、データ コレクターが注釈を入力できない場合は、注釈を削除してテキスト タイプとして再作成する必要がある場合があります。

AWS では大文字と小文字が区別されますが、 Data Infrastructure Insightsでは大文字と小文字は区別されないことに注意してください。したがって、 Data Infrastructure Insightsで「OWNER」という名前のアノテーションを作成し、EC2 で「OWNER」、「Owner」、「owner」という名前のタグを作成すると、EC2 の「owner」のすべてのバリエーションが Cloud Insight の「OWNER」アノテーションにマッピングされます。



== 追加リージョンを含める

AWS データコレクターの *詳細設定* セクションで、*追加のリージョンを含める* フィールドを設定して、コンマまたはセミコロンで区切られた追加のリージョンを含めることができます。デフォルトでは、このフィールドは *_us-.*_* に設定されており、すべての米国 AWS リージョンで収集されます。すべての地域で収集するには、このフィールドを *_.*_* に設定します。  *追加のリージョンを含める*フィールドが空の場合、データコレクターは*構成*セクションで指定された*AWSリージョン*フィールドで指定されたアセットを収集します。



== AWS子アカウントからの収集

Data Infrastructure Insights は、単一の AWS データコレクター内での AWS の子アカウントの収集をサポートします。このコレクションの構成は、AWS 環境で実行されます。

* メインアカウント ID が子アカウントの EC2 の詳細にアクセスできるようにする AWS ロールを各子アカウントに設定する必要があります。
* 各子アカウントのロール名は、同じ文字列として設定されている必要があります。
* このロール名文字列を、 Data Infrastructure Insights AWS Data Collector の *詳細設定* セクションの *クロスアカウントロール* フィールドに入力します。
* コレクターがインストールされているアカウントには、_代理アクセス管理者_ 権限が必要です。詳細については、link:https://docs.aws.amazon.com/accounts/latest/reference/using-orgs-delegated-admin.html["AWS ドキュメント"]を参照してください。


ベスト プラクティス: AWS で事前定義された _AmazonEC2ReadOnlyAccess_ ポリシーを EC2 メイン アカウントに割り当てることを強くお勧めします。また、AWS をクエリするには、データ ソースで構成されたユーザーには、少なくとも事前定義された _AWSOrganizationsReadOnlyAccess_ ポリシーが割り当てられている必要があります。

Data Infrastructure Insights がAWS 子アカウントから収集できるように環境を構成する方法については、以下を参照してください。

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["チュートリアル: IAM ロールを使用して AWS アカウント間でアクセスを委任する"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS のセットアップ: 自分が所有する別の AWS アカウントの IAM ユーザーにアクセスを許可する"]

link:https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["IAM ユーザーに権限を委任するロールの作成"]



== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
