---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: 'DELL EMC VNX ブロック ストレージ (旧 CLARiiON) の構成。' 
---
= Dell EMC VNX ブロック ストレージ (NaviCLI) データ コレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Dell EMC VNX Block Storage (NaviSec) データ コレクター (旧 CLARiiON) を使用して、インベントリとパフォーマンス データを取得します。



== 用語

Data Infrastructure Insights は、 EMC VNX ブロック ストレージ データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| ストレージ | ストレージ 


| ストレージプロセッサ | ストレージ ノード 


| このプール、RAIDグループ | ストレージ プール 


| LUN | Volume 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ ソースのすべてのケースを反映しているわけではありません。



== 要件

データを収集するには、次の要件を満たす必要があります。

* 各VNXブロックストレージプロセッサのIPアドレス
* VNXブロックストレージアレイへの読み取り専用のNavisphereユーザー名とパスワード
* NaviSecCliはData Infrastructure Insights AUにインストールする必要があります
* アクセス検証: ユーザー名とパスワードを使用して、Data Infrastructure Insights AU から各アレイに対して NaviSecCLI を実行します。
* ポート要件: 80, 443
* NaviSecCLIのバージョンは、アレイ上の最新のFLAREコードに対応している必要があります。
* パフォーマンスを確保するには、統計ログを有効にする必要があります。




== NaviSphere コマンドラインインターフェース構文

naviseccli.exe -h <IPアドレス> -user <ユーザー> -password <パスワード> -scope <スコープ、グローバルスコープの場合は0を使用> -port <デフォルトでは443を使用> コマンド



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| VNX ブロック ストレージ IP アドレス | VNXブロックストレージのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNX ブロック ストレージ デバイスにログインするために使用される名前。 


| パスワード | VNX ブロック ストレージ デバイスにログインするために使用されるパスワード。 


| naviseccli.exe への CLI パス | _naviseccli.exe_ 実行ファイルを含むフォルダへのフルパス 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは40分です。 


| Scope | 安全なクライアントスコープ。デフォルトはグローバルです。 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。デフォルトは300秒です。 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2a, 2a"]
|===
| 問題： | これを試してください: 


 a| 
エラー：

* エージェントが実行されていません
* naviseccli が見つかりませんでした
* コマンドの実行に失敗しました

 a| 
* NaviSphere CLIがCloud Insight Acquisition Unitにインストールされていることを確認します。
* データ コレクター構成ウィザードで「セキュア クライアントを使用する」オプションを選択しておらず、Naviphere CLI の非セキュア バージョンがインストールされていません。
* データコレクタ構成でNaviSphere CLIのインストールディレクトリが正しいことを確認します。
* データ コレクター構成で VNX ブロック ストレージの IP が正しいことを確認します。
* Data Infrastructure Insights取得ユニットより:
+
** CMDを開きます。
** 設定されたインストールディレクトリにディレクトリを変更します
** 「navicli -h {ip} getagent」と入力して、VNXブロックストレージデバイスとの接続を試みます（{ip}を実際のIPに置き換えてください）。






 a| 
エラー: 4.29 emc235848 emc241018 getall ホストエイリアス情報の解析に失敗しました
 a| 
これは、アレイ自体のホスト イニシエーター データベースの FLARE 29 破損問題によって発生したものと考えられます。 EMC ナレッジベースの記事 emc235848、emc241018 を参照してください。確認することもできます https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
エラー: メタ LUN を取得できません。  java -jar navicli.jar の実行中にエラーが発生しました
 a| 
* セキュア クライアントを使用するようにデータ コレクターの構成を変更します (推奨)
* navicli.exe または naviseccli.exe の CLI パスに navicli.jar をインストールします。
* 注意: navicli.jar は EMC Navisphere バージョン 6.26 以降では非推奨です。
* navicli.jarは\http://powerlink.emc.comで入手できるかもしれない。




 a| 
エラー: ストレージ プールが、構成された IP アドレスのサービス プロセッサ上のディスクを報告していません
 a| 
両方のサービスプロセッサIPをコンマで区切ってデータコレクターを構成します。



 a| 
エラー: リビジョン不一致エラー
 a| 
* これは通常、VNX ブロック ストレージ デバイスのファームウェアを更新したが、NaviCLI.exe のインストールを更新していないために発生します。これは、異なるファームウェアを搭載したさまざまなデバイスがあるにもかかわらず、(異なるファームウェア バージョンを備えた) 1 つの CLI のみがインストールされていることが原因である可能性もあります。
* デバイスとホストの両方で同じバージョンのソフトウェアが実行されていることを確認します。
+
** Data Infrastructure Insights取得ユニットからコマンドラインウィンドウを開きます
** 設定されたインストールディレクトリにディレクトリを変更します
** 「navicli -h <ip> getagent」と入力してCLARiiONデバイスに接続します。
** 最初の数行のバージョン番号を探します。例:「エージェント Rev: 6.16.2 (0.1)」
** 最初の行のバージョンを探して比較します。例:「Navisphere CLI リビジョン 6.07.00.04.07」






 a| 
エラー: サポートされていない構成 - ファイバーチャネルポートがありません
 a| 
デバイスにはファイバー チャネル ポートが構成されていません。現在、FC 構成のみがサポートされています。このバージョン/ファームウェアがサポートされていることを確認してください。

|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
