---
sidebar: sidebar 
permalink: task_dc_emc_xio.html 
keywords: data collector, XtremeIO, EMC 
summary: XtremeIO データ コレクターを構成します。 
---
= Dell EMC XtremeIO データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC XtremIO データ コレクターは、EMC XtremIO ストレージ システムからインベントリ データとパフォーマンス データを取得します。



== 要件

EMC XtremIO (HTTP) データ コレクターを構成するには、次のものが必要です。

* XtremIO 管理サーバー (XMS) ホスト アドレス
* 管理者権限を持つアカウント
* ポート443（HTTPS）へのアクセス




== 用語

Data Infrastructure Insights は、 EMC XtremIO データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ ソースを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク（SSD） | ディスク 


| クラスタ | ストレージ 


| コントローラ | ストレージ ノード 


| Volume | Volume 


| LUN マップ | ボリュームマップ 


| ターゲットFCイニシエーター | ボリュームマスク 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ ソースのすべてのケースを反映しているわけではありません。



== 要件

* XtremIO 管理サーバー (XMS) ホストの IP アドレス
* XtremIOの管理者ユーザー名とパスワード




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| XMSホスト | XtremIO 管理サーバーの IP アドレスまたは完全修飾ドメイン名 


| ユーザ名 | XtremIO管理サーバーのユーザー名 


| パスワード | XtremIO管理サーバーのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCP ポート | XTremIO 管理サーバーに接続するために使用される TCP ポート。デフォルトは 443 です。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。デフォルトは300秒です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
