---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Dell EMC Celerra データコレクタの設定 
---
= Dell EMC VNX File （旧 Celerra Unified Storage System ）データコレクタ
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このデータコレクタは、 VNX File Storage System からインベントリ情報を取得します。このデータコレクタを設定するには、ストレージプロセッサの IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。



== 用語

Data Infrastructure Insightsは、VNX Fileデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| Celerra Network Server/Celerra ストレージ・プール | ストレージプール 


| File System の略 | 内部ボリューム 


| データムーバー | コントローラ 


| データムーバーにマウントされたファイルシステム | ファイル共有 


| CIFS および NFS エクスポート | 共有 


| ディスクボリューム | バックエンド LUN 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

このデータコレクタを設定するには、次の情報が必要です。

* ストレージプロセッサの IP アドレス
* 読み取り専用のユーザ名とパスワード
* SSHポート22




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| VNX ファイルの IP アドレス | VNX File デバイスの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNX File デバイスへのログインに使用する名前 


| パスワード | VNX File デバイスへのログインに使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは20分です。 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== インベントリ

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー： DART の更新の実行中は処理を続行できません | Possible 解決策：データコレクタを一時停止し、 DART のアップグレードが完了するのを待ってから、別の取得要求を実行します。 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
