---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: 注釈を作成する方法。 
---
= 注釈の使用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
注釈を作成し、監視する資産に割り当てます。注釈は、物理的な場所、耐用年数、ストレージ層、ボリューム サービス レベルなど、資産に関する情報を提供するメモです。



== 注釈の定義

注釈を使用すると、ビジネスニーズに合ったカスタムのビジネス固有のデータをアセットに追加できます。  Data Infrastructure Insightsでは、資産のライフ サイクル (誕生日または寿命)、建物またはデータ センターの場所、階層などの一連のデフォルトの注釈が提供されますが、他の方法でデータを表示することが必要になる場合があります。

カスタム注釈のデータは、スイッチの製造元、ポート数、パフォーマンス統計など、すでに収集されているデバイス データを補足します。注釈を使用して追加したデータは、Data Infrastructure Insightsによって検出されません。

.開始する前に
* 環境データを関連付ける必要がある業界用語をリストします。
* 環境データを関連付ける必要がある企業用語をリストします。
* 使用できる可能性のあるデフォルトの注釈タイプを特定します。
* 作成する必要があるカスタム注釈を特定します。注釈をアセットに割り当てる前に、注釈を作成する必要があります。


注釈を作成するには、次の手順に従います。

.手順
. Data Infrastructure Insightsサイト メニューで、*オブザーバビリティ > エンリッチ > アノテーション* をクリックします。
. 新しい注釈を作成するには、[*+ 注釈*] をクリックします。
. 新しい注釈の名前、説明、およびタイプを入力します。
+
たとえば、データセンター 4 内の資産の物理的な場所を定義するテキスト注釈を作成するには、次のように入力します。

+
** 「場所」などの注釈の名前を入力します
** 「物理的な場所はデータセンター4です」など、注釈が説明している内容の説明を入力します。
** 「テキスト」など、注釈の「タイプ」を入力します。






== アセットに手動で注釈を割り当てる

アセットに注釈を割り当てると、ビジネスに関連した方法でアセットを並べ替え、グループ化し、レポートすることができます。注釈ルールを使用して特定のタイプのアセットに注釈を自動的に割り当てることができますが、アセット ページを使用して個々のアセットに注釈を割り当てることもできます。

.開始する前に
* 割り当てる注釈を作成しておく必要があります。


.手順
. Data Infrastructure Insights環境にログインします。
. 注釈を適用するアセットを見つけます。
+
** クエリを実行したり、ダッシュボード ウィジェットから選択したり、検索したりして、アセットを見つけることができます。必要なアセットが見つかったら、リンクをクリックしてアセットのランディング ページを開きます。


. アセット ページの [ユーザー データ] セクションで、[*+ 注釈*] をクリックします。
. [注釈の追加] ダイアログ ボックスが表示されます。
. リストから注釈を選択します。
. [値] をクリックし、選択した注釈の種類に応じて次のいずれかを実行します。
+
** 注釈タイプがリスト、日付、またはブール値の場合は、リストから値を選択します。
** 注釈タイプがテキストの場合は、値を入力します。


. *保存*をクリックします。


注釈を割り当てた後にその値を変更する場合は、注釈フィールドをクリックして別の値を選択します。注釈がリスト タイプで、[新しい値をオンザフライで追加] オプションが選択されている場合は、既存の値を選択するだけでなく、新しい値を入力することもできます。



== 注釈ルールを使用して注釈を割り当てる

定義した基準に基づいてアセットに注釈を自動的に割り当てるには、注釈ルールを構成します。  Data Infrastructure Insights は、これらのルールに基づいてアセットに注釈を割り当てます。  Data Infrastructure Insightsには 2 つのデフォルトの注釈ルールも用意されており、ニーズに合わせて変更したり、使用しない場合は削除したりできます。



=== アノテーション ルールの作成

個々のアセットに手動で注釈を適用する代わりに、注釈ルールを使用して複数のアセットに注釈を自動的に適用できます。  Insight が注釈ルールを評価する際、個々のアセット ページに手動で設定された注釈は、ルールベースの注釈よりも優先されます。

.開始する前に
注釈ルールのクエリを作成しておく必要があります。

.タスク概要
ルールの作成中に注釈タイプを編集できますが、事前にタイプを定義しておく必要があります。

.手順
. *管理 > 注釈ルール*をクリックします
+
「注釈ルール」ページには、既存の注釈ルールのリストが表示されます。

. *+ 追加*をクリックします。
. 次の手順を実行します。
+
.. *名前* ボックスに、ルールを説明する一意の名前を入力します。
+
この名前は「注釈ルール」ページに表示されます。

.. *クエリ*をクリックし、アセットに注釈を適用するために使用するクエリを選択します。
.. *注釈*をクリックし、適用する注釈を選択します。
.. *値*をクリックし、注釈の値を選択します。
+
たとえば、注釈として「誕生日」を選択した場合は、値に日付を指定します。

.. *保存*をクリックします
.. すべてのルールをすぐに実行する場合は、[すべてのルールを実行] をクリックします。それ以外の場合は、ルールは定期的にスケジュールされた間隔で実行されます。



