---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: Dell EMC Data Domain データコレクタの設定。 
---
= Dell EMC Data Domain データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータコレクタは、 Dell EMC Data Domain 重複排除ストレージシステムからインベントリとパフォーマンスの情報を収集します。このデータコレクタを設定するには、特定の設定手順と使用に関する推奨事項に従う必要があります。



== 用語

Data Infrastructure Insightsは、Data Domainデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| アレイ | ストレージ 


| FCポート | ポート 


| File System の略 | 内部ボリューム 


| クォータ | クォータ 


| NFS 共有および CIFS 共有 | ファイル共有 
|===
注意：これらは一般的な用語のマッピングのみであり、このデータ照合のすべてのケースを表しているわけではありません。



== 要件

このデータコレクタを設定するには、次の情報が必要です。

* Data Domain デバイスの IP アドレス
* Data Domain ストレージに対する読み取り専用のユーザ名とパスワード
* SSHポート22




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| IPアドレス | Data Domain ストレージアレイの IP アドレスまたは完全修飾ドメイン名 


| ユーザ名 | Data Domain ストレージアレイのユーザ名 


| パスワード | Data Domain ストレージアレイのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは20です。 


| SSHポート | SSH サービスポート 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
