---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Dell EMC RecoverPoint データコレクタの構成 
---
= Dell EMC RecoverPoint データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC RecoverPoint データコレクタの主な用途は、 RecoverPoint ストレージアプライアンスによって促進されるボリューム間レプリケーション関係を検出することです。このコレクタは、 RecoverPoint アプライアンス自体も検出します。Dell/EMC では、 VM 用の VMware バックアップ解決策 「 RecoverPoint for VMS 」を販売していますが、このコレクタではサポートされていません

データコレクタを設定するには、ストレージプロセッサの IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。

EMC RecoverPoint データコレクタは、 RecoverPoint が他のストレージアレイ間で調整するボリューム間レプリケーション関係を収集します。Data Infrastructure Insightsは、各RecoverPointクラスタのストレージアレイを表示し、そのクラスタ上のノードとストレージポートのインベントリデータを収集します。ストレージプールまたはボリュームのデータは収集されません。



== 要件

このデータコレクタを設定するには、次の情報が必要です。

* ストレージプロセッサの IP アドレスまたは完全修飾ドメイン名
* 読み取り専用のユーザ名とパスワード
* ポート 443 経由での REST API へのアクセス




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| RecoverPoint のアドレス | RecoverPoint クラスタの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | RecoverPoint クラスタのユーザ名 


| パスワード | RecoverPoint クラスタのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| TCPポート | RecoverPoint クラスタへの接続に使用する TCP ポート 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは20分です。 


| 除外クラスタ | ポーリング時に対象から除外するクラスタの ID または名前をカンマで区切ったリスト。 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
