---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Brocade FOS REST データ コレクターを構成します。 
---
= Brocade FOS REST データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Brocade FOS REST コレクターを使用して、FabricOS (FOS) ファームウェア 8.2 以降を実行しているBrocadeスイッチ デバイスのインベントリとパフォーマンスを検出します。初期の 8.2 FOS リリースには REST API バグが含まれている可能性があるので注意してください。プラットフォームがサポートする最新の FOS リリースを実行することを強くお勧めします。

注意: FOS のデフォルトの「ユーザー」レベルでは、Data Infrastructure Insightsがデバイスの論理的側面をすべて表示するには機能が不十分です。スイッチに設定されているすべての仮想ファブリックに対する権限に加えて、「シャーシ ロール」が有効になっているユーザー アカウントが必要です。

以下は、FOS デバイスへの SSH セッションでData Infrastructure Insightsを使用するための「最小権限」ユーザー アカウントを作成する方法の例です。

userConfig --add NetAppCIUser -r user -l 1-128 -c user -p Qwerty!

これにより、パスワードが「Qwerty!」であるユーザー「NetAppCIUser」が作成されます。このユーザーには、128 個のすべての仮想ファブリック ( -l ) にわたる「ユーザー」ロール (-r) が与えられます。このユーザーには、ユーザー レベルのアクセスが割り当てられた、必要な「シャーシ」ロール (-c) も追加で付与されます。

デフォルトでは、このコレクターは、スイッチが属するすべてのファブリックに含まれるすべての FOS デバイスを検出しようとします。

注意: FOS のデフォルトの読み取り専用ユーザー「ユーザー」には、すべての仮想ファブリックに対する表示権限はなく、「シャーシ ロール」権限もありません。つまり、FOS デバイスの物理構成と論理構成の両方を理解する必要があるData Infrastructure Insightsで「ユーザー」を使用しても成功する可能性は低くなります。



== 用語

Data Infrastructure Insights は、 Brocade FOS REST データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| スイッチ | スイッチ 


| ポート | ポート 


| 仮想ファブリック、物理ファブリック | ファブリック 


| ゾーン | ゾーン 


| 論理スイッチ | 論理スイッチ 


| LSANゾーン | IVRゾーン 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* ファブリック内のすべてのスイッチへの TCP 接続が必要です。このデータ コレクター タイプは、ファブリック内の各デバイスに対して HTTP と HTTPS の両方をシームレスに試行します。  [ファブリック内のすべてのスイッチを検出する] チェック ボックスをオンにすると、 Data Infrastructure Insights はファブリック内のすべてのスイッチを識別します。ただし、これらの追加スイッチを検出するには、それらのスイッチへの TCP 接続が必要です。
* ファブリック内のすべてのスイッチでグローバルに同じアカウントが必要です。アクセスを確認するには、デバイスの Web インターフェースを使用できます。




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| スイッチIP | FOSスイッチのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | スイッチのユーザー名 


| パスワード | スイッチのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 除外されたデバイス | ポーリングから除外するデバイスの IPv4 アドレスのコンマ区切りリスト。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは 60 です。 


| ファブリック内のすべてのスイッチを検出する | ファブリック内のすべてのスイッチを検出する場合に選択します。 


| HBA を優先するかゾーン エイリアスを優先するかを選択する | HBA エイリアスとゾーン エイリアスのどちらを優先するかを選択します。 


| 接続の種類 | HTTP または HTTPS。 


| この設定は、デバイスごとにCIが最初に使用しようとするプロトコルを変更するだけであることに注意してください。CIは、デフォルトで失敗した場合、自動的に反対のプロトコルを試みます。 | TCPポートの上書き 


| デフォルトを使用しない場合はポートを指定します。 | パフォーマンスポーリング間隔（秒） 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| テスト機能でプロトコルにアクセスできないという警告が表示される | 特定のBrocade FOS 8.2+ デバイスは、HTTP または HTTPS でのみ通信しようとします。スイッチにデジタル証明書がインストールされている場合、暗号化されていない HTTP または HTTPS を使用して通信しようとすると、スイッチは HTTP エラーをスローします。テスト機能は、HTTP と HTTPS の両方で通信​​を試行します。テストで 1 つのプロトコルが成功したことが示された場合は、コレクターを安全に保存でき、他のプロトコルが失敗したことを心配する必要はありません。コレクターは収集中に両方のプロトコルを試行し、どちらも機能しない場合にのみ失敗します。 


| エラー: 401 不正アクセスによりインベントリが失敗しました...無効なセッション キーです... | これは、HTTP 基本認証を適切にサポートしていない 8.2.1c などの非常に初期の 8.2 FOS リリースに特有のバグです。  8.2 または 9.* 以降のリリースにアップグレードします 


| エラー: 「Data Infrastructure Insights が無効なシャーシ ロールを受信しました」 | このデータ ソースで構成されたユーザーにシャーシ ロール権限が付与されていることを確認します。 


| エラー:「シャーシの IP アドレスが一致しません」 | シャーシ IP アドレスを使用するようにデータ ソース構成を変更します。 


| 在庫が403 Forbiddenで失敗する | これは単に資格情報が正しくないこと、または不十分な権限を持つロールを使用しようとしていることを示している可能性があります。「ユーザー」レベルのユーザーには、必要な「シャーシ ロール」権限や、デフォルト以外の仮想ファブリックへの表示アクセス権がないことを覚えておいてください。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
