---
sidebar: sidebar 
permalink: task_dc_brocade_bna.html 
keywords: data collector, Brocade, BNA 
summary: Brocade BNA コレクターを構成します。 
---
= Brocade Network Advisor データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Brocade Network Advisor データ コレクターを使用して、 Brocadeスイッチからインベントリとパフォーマンス データを取得します。



== 用語

Data Infrastructure Insights は、 Brocade Network Advisor データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| スイッチ | スイッチ 


| ポート | ポート 


| 仮想ファブリック、物理ファブリック | ファブリック 


| 論理スイッチ | 論理スイッチ 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次のものが必要です。

* Data Infrastructure Insights取得ユニットは、BNA サーバー上の TCP ポート 443 への接続を開始します。  BNA サーバーはバージョン 14.2.1 以上を実行している必要があります。
* Brocade Network Advisor サーバーの IP アドレス
* 管理者アカウントのユーザー名とパスワード
* ポート要件: HTTP/HTTPS 443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| Brocadeネットワークアドバイザーサーバー IP | ネットワークアドバイザーサーバーのIPアドレス 


| ユーザー名 | スイッチのユーザー名 


| ユーザー名 | 管理者ユーザー名 


| パスワード | 管理者のパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 接続タイプ | HTTPS（デフォルトポート443）またはHTTP（デフォルトポート80） 


| 接続ポートのオーバーライド | 空白の場合は、接続タイプフィールドのデフォルトのポートを使用します。それ以外の場合は、使用する接続ポートを入力します。 


| パスワード | スイッチのパスワード 


| インベントリポーリング間隔（分） | デフォルトは40です 


| レポートアクセスゲートウェイ | アクセスゲートウェイモードにデバイスを含めるにはチェックを入れます 


| パフォーマンスポーリング間隔（秒） | デフォルトは1800です 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| 1 つ以上のノードが Access Gateway ポートにログインしている、またはデータ コレクターが Access Gateway デバイスの検出に失敗したというメッセージが表示されます。 | NPV デバイスが正しく動作していること、および接続されているすべての WWN が想定されていることを確認します。 NPV デバイスを直接取得しないでください。代わりに、コア ファブリック スイッチを取得すると、NPV デバイス データが収集されます。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
