---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: IBM SAN ボリューム コントローラー データ コレクターを構成します。 
---
= IBM SANボリュームコントローラデータコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM SAN ボリューム コントローラー (SVC) データ コレクターは、SSH を使用してインベントリとパフォーマンス データを収集し、SVC オペレーティング システムを実行するさまざまなデバイスをサポートします。

サポートされているデバイスのリストには、SVC、v7000、v5000、v3700 などのモデルが含まれています。サポートされているモデルとファームウェア バージョンについては、 Data Infrastructure Insightsサポート マトリックスを参照してください。



== 用語

Data Infrastructure Insights は、 IBM SVC データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ドライブ | ディスク 


| クラスタ | ストレージ 


| ノード | ストレージ ノード 


| Mdiskグループ | ストレージ プール 


| 仮想ディスク | Volume 


| Mディスク | バックエンドLUNとパス 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



=== 在庫要件

* 各SVCクラスタのIPアドレス
* ポート22が利用可能
* 読み取り専用のユーザー名とパスワード




=== パフォーマンス要件

* SVC コンソールは、すべての SVC クラスターに必須であり、SVC 検出基盤パッケージに必要です。
* 資格情報には、クラスター ノードから構成ノードにパフォーマンス ファイルをコピーする場合にのみ管理アクセス レベルが必要です。
* SSHでSVCクラスターに接続し、次のコマンドを実行してデータ収集を有効にします: _svctask startstats -interval 1_
+
注: または、SVC 管理ユーザー インターフェイスを使用してデータ収集を有効にします。





== 構成

[cols="2*"]
|===
| フィールド | 説明 


| クラスターIPアドレス | SVCストレージのIPアドレスまたは完全修飾ドメイン名 


| インベントリユーザー名 | SVC CLI のユーザー名 


| インベントリパスワード | SVC CLIのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは40分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。デフォルトは300秒です。 


| ダンプされた統計ファイルをクリーンアップするには | ダンプされた統計ファイルをクリーンアップするには、このチェックボックスを選択します 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー:「コマンドは構成ノードで実行されなかったため、開始できません。」 | コマンドは構成ノードで実行する必要があります。 
|===
このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー:「コマンドは構成ノードで実行されなかったため、開始できません。」 | コマンドは構成ノードで実行する必要があります。 
|===
このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
