---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Oracle ZFS データ コレクターを構成します。 
---
= Oracle ZFS Storage Appliance データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Oracle ZFS Storage Appliance データ コレクターを使用して、インベントリおよびパフォーマンス データを収集します。



== 用語

Data Infrastructure Insights は、 Oracle ZFS データ コレクターを使用してインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク（SSD） | ディスク 


| クラスタ | ストレージ 


| コントローラ | ストレージ ノード 


| LUN | Volume 


| LUN マップ | ボリュームマップ 


| イニシエーター、ターゲット | ボリュームマスク 


| 共有 | 内部容積 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ ソースのすべてのケースを反映しているわけではありません。



== 要件

* ZFS コントローラ 1 と ZFS コントローラ 2 のホスト名
* 管理者のユーザ名とパスワード
* ポート要件: 215 HTTP/HTTPS




== 必要なパフォーマンスメトリック

Oracle ZFS アプライアンスは、ストレージ管理者にパフォーマンス統計をキャプチャするための大きな柔軟性を提供します。  Data Infrastructure Insights、高可用性ペアの各コントローラーが次のメトリックをキャプチャするように構成されている必要があります。

* smb2.ops[共有]
* nfs3.ops[共有]
* nfs4.ops[共有]
* nfs4-1.ops[共有]


コントローラーがこれらのいずれかまたはすべてをキャプチャできない場合、 Data Infrastructure Insightsは「内部ボリューム」のワークロードを把握しないか、または過少に報告する可能性があります。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| ZFSコントローラ1のホスト名 | ストレージコントローラ1のホスト名 


| ZFSコントローラ2のホスト名 | ストレージコントローラ2のホスト名 


| ユーザ名 | ストレージ システム管理者ユーザー アカウントのユーザー名 


| パスワード | 管理者ユーザーアカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 接続タイプ | HTTPSまたはHTTP、デフォルトのポートも表示します 


| 接続ポートのオーバーライド | 空白の場合は、接続タイプフィールドのデフォルトのポートを使用します。それ以外の場合は、使用する接続ポートを入力します。 


| インベントリポーリング間隔 | デフォルトは60秒です 


| パフォーマンスポーリング間隔（秒） | デフォルトは 300 です。 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2a, 2a"]
|===
| 問題： | これを試してください: 


 a| 
「ログイン資格情報が無効です」
 a| 
Zfsユーザーアカウントとパスワードを検証する



 a| 
「リクエストはステータス 404 で失敗しました \https://.....:215/api/access/v1」
 a| 
ZFS アレイが古すぎて、REST API をサポートできない可能性があります。  AK 2013.1.3.0 は、REST API 対応の最初の ZFS OS リリースであり、すべての ZFS アプライアンスがこのリリースにアップグレードできるわけではありません。



 a| 
「構成エラー」と「REST サービスが無効です」というエラー メッセージ
 a| 
このデバイスで REST サービスが有効になっていることを確認します。



 a| 
「構成エラー」とエラーメッセージ「コマンドを実行する権限のないユーザー」
 a| 
このエラーは、構成されたユーザーに特定のロール (たとえば、「advanced_analytics」) が含まれていないことが原因である可能性があります。

読み取り専用ロールを持つユーザーに Analytics スコープを適用すると、エラーが削除される可能性があります。次の手順を実行します。

. ZFsシステムでは、「構成」->「ユーザー」画面で、マウスをロールの上に移動し、ダブルクリックして編集を許可します。
. 「スコープ」ドロップダウン メニューから「分析」を選択します。可能なプロパティのリストが表示されます。
. 一番上のチェックボックスをクリックすると、3 つのプロパティがすべて選択されます。
. 右側の「追加」ボタンをクリックします。
. ポップアップ ウィンドウの右上にある [適用] ボタンをクリックします。ポップアップウィンドウが閉じます。


|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
