---
sidebar: sidebar 
permalink: task_defining_annotations.html 
keywords: annotations, monitor, notes, tags 
summary: 注釈を使用してデータを追跡します。 
---
= 注釈の定義
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
企業の要件に合わせてデータを追跡するためにData Infrastructure Insightsをカスタマイズする場合、注釈と呼ばれる特殊なメモを定義し、それを資産に割り当てることができます。

資産の耐用年数、データセンター、建物の場所、ストレージ層、ボリューム サービス レベルなどの情報を資産に注釈として割り当てることができます。

注釈を使用して環境を監視するには、次の高レベルのタスクが含まれます。

* すべての注釈タイプの定義を作成または編集します。
* アセット ページを表示し、各アセットを 1 つ以上の注釈に関連付けます。
+
たとえば、資産がリースされており、そのリースが 2 か月以内に期限切れになる場合は、資産に耐用年数終了の注釈を適用することが考えられます。これにより、他の人がその資産を長期間使用することを防ぐことができます。

* 同じタイプの複数のアセットに注釈を自動的に適用するためのルールを作成します。
* 注釈によってアセットをフィルタリングします。




== デフォルトの注釈タイプ

Data Infrastructure Insightsには、いくつかのデフォルトの注釈タイプが用意されています。これらの注釈は、データをフィルタリングまたはグループ化するために使用できます。

次のようなデフォルトの注釈タイプにアセットを関連付けることができます。

* 資産のライフサイクル（誕生日、終了、使用終了など）
* データセンター、建物、フロアなどのデバイスの位置情報
* 資産の分類（品質（階層）、接続デバイス（スイッチレベル）、サービスレベルなど）
* ステータス（ホット（高使用率）など）


次の表は、Data Infrastructure Insightsが提供する注釈タイプを示しています。

[cols="30,53, 16"]
|===


| 注釈の種類 | 説明 | タイプ 


| エイリアス | リソースのユーザーフレンドリーな名前 | 文章 


| コンピューティング リソース グループ | ホストおよび VM ファイルシステム データ コレクターによって使用されるグループ割り当て | リスト 


| データセンター | 物理的な場所 | リスト 


| ホット | 定期的に頻繁に使用されるデバイス、または容量の限界に達しているデバイス | ブーリアン 


| メモ | リソースに関連付けられたコメント | テスト 


| サービス レベル | リソースに割り当てることができる、サポートされているサービス レベルのセット。内部ボリューム、qtree、ボリュームの順序付けられたオプション リストを提供します。サービス レベルを編集して、さまざまなレベルのパフォーマンス ポリシーを設定します。 | リスト 


| 日没 | このしきい値を超えると、そのデバイスに新しい割り当てを行うことができなくなります。計画された移行やその他の保留中のネットワーク変更に役立ちます。 | 日付 


| スイッチレベル | スイッチのカテゴリを設定するための定義済みオプション。通常、これらの指定はデバイスの寿命の間は保持されますが、編集することもできます。スイッチのみ使用可能です。 | リスト 


| 階層 | 環境内でさまざまなレベルのサービスを定義するために使用できます。ティアでは、必要な速度などのレベルのタイプを定義できます (たとえば、ゴールドまたはシルバー)。この機能は、内部ボリューム、qtree、ストレージ アレイ、ストレージ プール、およびボリュームでのみ使用できます。 | リスト 


| 違反の重大度 | 違反 (ホスト ポートの欠落や冗長性の欠落など) の重要度の最高から最低の階層でのランク (たとえば、メジャー)。 | リスト 
|===

NOTE: エイリアス、データ センター、ホット、サービス レベル、サンセット、スイッチ レベル、層、違反の重大度はシステム レベルの注釈であり、削除または名前変更はできません。変更できるのは割り当てられた値のみです。



== カスタム注釈の作成

注釈を使用すると、ビジネスニーズに合ったカスタムのビジネス固有のデータをアセットに追加できます。 Data Infrastructure Insightsでは一連のデフォルトの注釈が提供されますが、他の方法でデータを表示したい場合もあります。カスタム注釈のデータは、ストレージの製造元、ボリューム数、パフォーマンス統計など、すでに収集されているデバイス データを補足します。注釈を使用して追加したデータは、Data Infrastructure Insightsによって検出されません。

.手順
. Data Infrastructure Insightsサイト メニューで、*管理 > 注釈* をクリックします。
+
「注釈」ページには注釈のリストが表示されます。

. *+追加*をクリック
. 注釈の*名前*と*説明*を入力します。
+
これらのフィールドには最大 255 文字を入力できます。

. *タイプ*をクリックし、この注釈で許可されるデータのタイプを表す次のオプションのいずれかを選択します。


.注釈の種類
* ブール値: はい/いいえの選択肢を持つドロップダウンリストを作成します。例えば、「直接接続」という注釈はブール値です。
* 日付: 日付を保持するフィールドを作成します。たとえば、注釈を日付にする場合は、これを選択します。
* リスト: 次のいずれかを作成します。
+
** ドロップダウン固定リスト
+
他のユーザーがデバイス上でこの注釈タイプを割り当てている場合、リストにさらに値を追加することはできません。

** ドロップダウンの柔軟なリスト
+
このリストを作成するときに [オンザフライで新しい値を追加する] オプションを選択すると、他のユーザーがデバイスでこの注釈タイプを割り当てるときに、リストにさらに値を追加できます。



* 数値: 注釈を割り当てるユーザーが数値を入力できるフィールドを作成します。たとえば、注釈タイプが「階」の場合、ユーザーは「数値」の値タイプを選択し、階数を入力できます。
* テキスト: 自由形式のテキストを入力できるフィールドを作成します。たとえば、注釈タイプとして「言語」を入力し、値タイプとして「テキスト」を選択し、値として言語を入力します。



NOTE: タイプを設定して変更を保存した後は、注釈のタイプを変更することはできません。タイプを変更する必要がある場合は、注釈を削除して新しい注釈を作成する必要があります。

. 注釈タイプとしてリストを選択した場合は、次の操作を行います。
+
.. アセット ページ上で注釈に値を追加して柔軟なリストを作成できるようにするには、[新しい値を即座に追加] を選択します。
+
たとえば、アセット ページにいて、そのアセットに Detroit、Tampa、Boston という値を持つ City 注釈が付いているとします。 *オンザフライで新しい値を追加*オプションを選択した場合は、注釈ページに移動して値を追加するのではなく、アセット ページで直接、サンフランシスコやシカゴなどの都市に値を追加できます。このオプションを選択しないと、注釈を適用するときに新しい注釈値を追加できず、固定リストが作成されます。

.. *値*フィールドと*説明*フィールドに値と説明を入力します。
.. 追加の値を追加するには、[*+追加+*] をクリックします。
.. 値を削除するには、ゴミ箱アイコンをクリックします。


. *保存*をクリックします
+
注釈は「注釈」ページのリストに表示されます。



.ブール注釈に関する注意
ブール型注釈でフィルタリングする場合、フィルタリング対象となる次の値が表示されることがあります。

* *任意*: 「はい」、「いいえ」に設定された結果、またはまったく設定されていない結果を含む、すべての結果が返されます。
* *はい*: 「はい」の結果のみを返します。DII では、ほとんどの表で「はい」にチェックマークが表示されることに注意してください。値は「True」、「On」などに設定できます。DII はこれらすべてを「Yes」として扱います。
* *いいえ*: 「いいえ」の結果のみを返します。DII では、ほとんどの表で「いいえ」が「X」として表示されることに注意してください。値は「False」、「Off」などに設定できますが、DII はこれらすべてを「No」として扱います。
* *なし*: アノテーションがまったく設定されていない結果のみを返します。「Null」値とも呼ばれます。


.終了後の操作
UI では、注釈はすぐに使用できるようになります。
