---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: HDS データ コレクターを構成します。 
---
= 日立HCPデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、HCP 管理 API を使用して Hitachi Content Platform (HCP) をサポートします。


NOTE: Hitachi Content Platform は、管理対象ユニットとは異なる Raw TB レートで計測されます。フォーマットされていないHCP容量40TBごとに1として課金されます。link:concept_subscribing_to_cloud_insights.html#pricing["管理ユニット（MU）"] 。



== 用語

Data Infrastructure Insights は、 Hitachi HCP データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| HCPクラスター | ストレージ 


| テナント | ストレージ プール 


|  | ネームスペース 


| 内部容積 | ノード 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 在庫要件

インベントリ データを収集するには、次のものが必要です。

* HCPサーバーのIPアドレス
* HCP ソフトウェアおよびピア権限の読み取り専用ユーザー名とパスワード




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| HCPホスト | HCPホストのIPアドレスまたは完全修飾ドメイン名 


| HCPポート | デフォルトは9090です 


| HCPユーザーID | HCP ホストのユーザー名。 


| HCP パスワード | HCP ホストに使用されるパスワード。 


| HCP認証タイプ | HCP_LOCALまたはACTIVE_DIRECTORYを選択してください 
|===


== 高度な設定

|===


| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは 60 です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。デフォルトは 900 です。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
