---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'HP Enterprise Alletra 6000 (旧 Nimble) データ コレクターを構成します。' 
---
= HPE Alletra 6000 データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
HP Enterprise Alletra 6000 (旧 Nimble) データ コレクターは、Alletra 6000 ストレージ アレイのインベントリおよびパフォーマンス データをサポートします。



== 用語

Data Infrastructure Insights は、このコレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| アレイ | ストレージ 


| ディスク | ディスク 


| Volume | Volume 


| プール | ストレージ プール 


| イニシエータ | ストレージホストエイリアス 


| コントローラ | ストレージ ノード 


| Fibre Channel インターフェイス | コントローラ 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

ストレージ アレイからインベントリおよび構成データを収集するには、次のものが必要です。

* アレイはインストールおよび構成されており、完全修飾ドメイン名 (FQDN) またはアレイ管理 IP アドレスを通じてクライアントからアクセスできる必要があります。
* アレイでは NimbleOS 2.3.x 以降が実行されている必要があります。
* 少なくとも「オペレータ」レベルのロールを持つアレイへの有効なユーザー名とパスワードが必要です。  「ゲスト」ロールには、イニシエーターの構成を理解するための十分なアクセス権がありません。
* アレイ上でポート 5392 が開いている必要があります。


ストレージ アレイからパフォーマンス データを収集するには、次のものが必要です。

* アレイはNimbleOS 4.0.0以降を実行している必要があります
* アレイにはボリュームが構成されている必要があります。  NimbleOS が持つ唯一のパフォーマンス API はボリューム用であり、統計Data Infrastructure Insightsレポートはボリュームの統計から派生します。




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| アレイ管理IPアドレス | 完全修飾ドメイン名 (FQDN) またはアレイ管理 IP アドレス。 


| ユーザー名 | アレイのユーザー名 


| パスワード | アレイのパスワード 
|===


== 高度な設定

|===


| フィールド | 説明 


| ポート | Nimble REST API で使用されるポート。デフォルトは 5392 です。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 
|===
注: デフォルトのパフォーマンス ポーリング間隔は 300 秒であり、変更することはできません。これは、HPE Alletra 6000 でサポートされている唯一の間隔です。
