---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: IBM CS データ コレクターを構成します。 
---
= IBM CS データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、このデータ コレクターを使用して、IBM CS ストレージ システムのインベントリとパフォーマンス データを検出します。



== 用語

Data Infrastructure Insights は、 IBM CS データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ プール | ストレージ プール 


| Container | 内部容積 


| Container | ファイル共有 


| NFS 共有 | 共有 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* クラスタの外部データサービスIPアドレス
* 管理者のユーザ名とパスワード
* ポート9440




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| Prism外部IPアドレス | クラスタの外部データサービスIPアドレス 


| ユーザ名 | 管理者アカウントのユーザー名 


| パスワード | 管理者アカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCP ポート | IBM CS アレイに接続するために使用される TCP ポート。デフォルトは 9440 です。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 


| パフォーマンスポーリング間隔(秒) | パフォーマンス ポーリングの間隔。デフォルトは300秒です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
