---
sidebar: sidebar 
permalink: task_cs_getting_started.html 
keywords: collectors, data collectors, configure, introduction, browsers, Cloud Secure 
summary: ユーザー アクティビティを監視し、セキュリティの脅威を検出するために、Workload Security エージェントとデータ コレクターを展開します。 
---
= ワークロードセキュリティ入門
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Workload Security は、ユーザー アクティビティを監視し、ストレージ環境における潜在的なセキュリティ脅威を検出するのに役立ちます。監視を開始する前に、エージェント、データ コレクター、およびディレクトリ サービスを構成して、包括的なセキュリティ監視の基盤を確立する必要があります。

Workload Security システムはエージェントを使用して、ストレージ システムからのアクセス データとディレクトリ サービス サーバーからのユーザー情報を収集します。

データの収集を開始する前に、以下を構成する必要があります。

[cols="2*"]
|===


| Task | 関連情報 


| エージェントを構成する  a| 
link:concept_cs_agent_requirements.html["エージェントの要件"]

link:task_cs_add_agent.html["エージェントを追加"]



| ユーザーディレクトリコネクタを構成する | link:task_config_user_dir_connect.html["ユーザーディレクトリコネクタの追加"] 


| データコレクターを構成する | *ワークロード セキュリティ > コレクター* をクリックし、設定するデータ コレクターをクリックします。コレクター情報については、ドキュメントのデータ コレクター ベンダー リファレンス セクションを参照してください。 


| ユーザーアカウントを作成する | link:concept_user_roles.html["ユーザーアカウントの管理"] 
|===
Workload Security は他のツールとも統合できます。例えば、link:http://docs.netapp.com/us-en/cloudinsights/CloudInsights_CloudSecure_Splunk_integration_guide.pdf["このガイドをご覧ください"] Splunk との統合について。
