---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: NetApp StorageGRIDデータコレクターを構成する 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRIDデータコレクター
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp StorageGRIDデータ コレクターは、 StorageGRID構成からのインベントリとパフォーマンスの収集をサポートします。

[NOTE]
====
基盤となるハードウェア トポロジと構成に関係なく、すべてのStorageGRIDシステムにわたって DII 権限に対する一貫した計測を提供するために、 Data Infrastructure Insights は、物理ディスク レイアウトに基づく RAW 容量ではなく、使用可能な合計容量 (storagegrid_storage_utilization_total_space_bytes) を使用します。

容量ベースのライセンス モデルを使用しているお客様の場合、 StorageGRIDは「オブジェクト」ストレージとして計測されます。

従来の (MU) ライセンス モデルを使用しているお客様の場合、 StorageGRIDはセカンダリ ストレージとして 40TiB から 1 MU のレートで計測されます。

====


== 用語

Data Infrastructure Insights は、 NetApp StorageGRIDコレクターから次のインベントリ情報を取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| StorageGRID | ストレージ 


| ノード | ノード 


| テナント | ストレージ プール 


| バケット | 内部容積 
|===


== 要件

このデータ ソースを構成するための要件は次のとおりです。

* StorageGRIDホスト IP アドレス
* メトリッククエリとテナントアクセスのロールが割り当てられたユーザーのユーザー名とパスワード
* ポート 443（または設定されている場合は 8443）




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| StorageGRIDホスト IP アドレス | StorageGRIDアプライアンスの管理仮想IPアドレス 


| ユーザー名 | StorageGRIDアプライアンスにログインするために使用する名前 


| パスワード | StorageGRIDアプライアンスにログインするために使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは60分です 


| パフォーマンスポーリング間隔（秒） | デフォルトは900秒です 
|===


== シングルサインオン（SSO）

そのlink:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]ファームウェア バージョンには対応する API バージョンがあり、3.0 API 以降のバージョンではシングル サインオン (SSO) ログインがサポートされています。

|===


| ファームウェア バージョン | APIバージョン | シングルサインオン（SSO）をサポート 


| 11.1 | 2 | いいえ 


| 11.2 | 3.0 | はい 


| 11.5 | 3.3 | はい 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
