---
sidebar: sidebar 
permalink: task_dc_na_solidfire.html 
summary: NetApp SolidFireデータコレクターを構成する 
keywords: data collector, queries, create 
---
= NetApp SolidFireオールフラッシュアレイ データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp SolidFireオールフラッシュ アレイ データ コレクターは、iSCSI とファイバー チャネルの両方のSolidFire構成からのインベントリとパフォーマンスの収集をサポートします。

SolidFireデータ コレクターはSolidFire REST API を利用します。データ コレクターが存在する取得ユニットは、 SolidFireクラスター管理 IP アドレスの TCP ポート 443 への HTTPS 接続を開始できる必要があります。データ コレクターには、 SolidFireクラスターで REST API クエリを実行できる資格情報が必要です。



== 用語

Data Infrastructure Insights は、 NetApp SolidFire All-Flash Array データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ドライブ | ディスク 


| クラスタ | ストレージ 


| ノード | ストレージ ノード 


| Volume | Volume 


| ファイバーチャネルポート | ポート 


| ボリュームアクセスグループ、LUN割り当て | ボリュームマップ 


| iSCSI セッション | ボリュームマスク 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するための要件は次のとおりです。

* 管理仮想IPアドレス
* 読み取り専用のユーザー名と資格情報
* ポート443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| 管理仮想 IP アドレス (MVIP) | SolidFireクラスタの管理仮想IPアドレス 


| ユーザー名 | SolidFireクラスタにログインするために使用する名前 


| パスワード | SolidFireクラスタにログインするために使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 接続タイプ | 接続タイプを選択 


| 通信ポート | NetApp API に使用されるポート 


| インベントリポーリング間隔（分） | デフォルトは20分です 


| パフォーマンスポーリング間隔（秒） | デフォルトは300秒です 
|===


== トラブルシューティング

SolidFire がエラーを報告すると、 Data Infrastructure Insightsに次のように表示されます。

_データを取得しようとしたときに、 SolidFireデバイスからエラー メッセージが受信されました。呼び出しは <method> (<parameterString> ) でした。デバイスからのエラーメッセージは次のとおりです (デバイスのマニュアルを確認してください): <メッセージ>_

各値の意味は次のとおりです。

* <method> は、GET や PUT などの HTTP メソッドです。
* <parameterString> は、REST 呼び出しに含まれていたパラメータのコンマ区切りリストです。
* <message> は、デバイスがエラー メッセージとして返した内容です。


このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
