---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: クエリを使用して、複数のアプリケーションやアノテーションをオブジェクトに割り当てたり、オブジェクトから複数のアプリケーションやアノテーションを削除したりできます。 
keywords: query, queries, application, annotation, multiple 
---
= アセットに対する複数のアプリケーションの割り当てと削除
:hardbreaks:
:allow-uri-read: 


[role="lead"]
アセットに対して複数のアプリケーションを割り当てたりアセットから削除したりするには、クエリを使用します。手動でアプリケーションを割り当てlink:task_create_application.html["アプリケーション"]たり削除したりする必要はありません。


NOTE: これらの手順を使用して、同じ方法で追加または削除できますlink:task_defining_annotations.html["アノテーション"]。

.開始する前に
編集するすべてのアセットを検索するクエリを作成しておく必要があります。

.手順
. [エクスプローラ]*をクリックし、*[メトリッククエリ]*を選択します。
+
[ クエリ ] ページが表示されます。

. アセットを検索するクエリの名前をクリックします。
+
クエリに関連付けられているアセットのリストが表示されます。

. リストで目的のアセットを選択するか、一番上のチェックボックスをクリックして「すべて」を選択します。
+
[Bulk Actions]ドロップダウンが表示されます。

. 選択したアセットにアプリケーションを追加するには、[Bulk Actions]をクリックし、*[Add Application]*を選択します。
. 1 つ以上のアプリケーションを選択します。
+
ホスト、内部ボリューム、 qtree 、および仮想マシンについては複数のアプリケーションを選択できますが、 ボリュームまたは共有に選択できるアプリケーションは 1 つだけです。

. [ 保存（ Save ） ] をクリックします。
. アセットに割り当てられているアプリケーションを削除するには、[Bulk Actions]をクリックして*[Remove Application]*を選択します。
. 削除する 1 つ以上のアプリケーションを選択します。
. [ 削除（ Delete ） ] をクリックします。


新しく割り当てたアプリケーションは、別のアセットから派生したアプリケーションよりも優先されます。たとえば、ホストから継承したアプリケーションがあるボリュームに新しいアプリケーションを割り当てた場合、派生したアプリケーションよりも新しいアプリケーションが優先されます。

一括追加の場合は_Save_(保存)、一括削除の場合は_Remove_(削除)をクリックすると、処理に時間がかかることがData Infrastructure Insightsから通知されます。このメッセージは無視してもかまいません。操作はバックグラウンドで続行されます。


NOTE: 関連するアセットが大量にある環境では、それらのアセットへのアプリケーションの割り当ての継承に数分かかることがあります。関連するアセットが多数ある場合は、継承の時間を長くしてください。
