---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 データコレクター 
---
= IBM TotalStorage DS4000 データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、IBM DS4000 ストレージ システムからインベントリとパフォーマンス情報を取得します。可能な構成は 2 つ (ファームウェア 6.x とファームウェア 7.x+) あり、両方とも同じ値を持ちます。



== 用語

Data Infrastructure Insights は、 IBM DS4000 データ コレクターから次のインベントリ情報を取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| ボリューム グループ | ディスクグループ 


| ストレージ アレイ | ストレージ 


| コントローラ | ストレージ ノード 


| ボリューム グループ | ストレージ プール 


| Volume | Volume 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* 各 DS5 または FAStT アレイの IP アドレス
* アレイ上の両方のコントローラのIPアドレスをpingしてアクセスを検証する
* ポート要件: 2463




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| アレイSANtricityコントローラIPのコンマ区切りリスト | アレイコントローラのIPアドレスおよび/または完全修飾ドメイン名 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは30分です 


| パフォーマンスポーリング間隔は最大3600秒 | デフォルトは300秒です 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
