---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: HDS Ops Center データコレクタの設定 
---
= Hitachi Ops Center データコレクタ
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このデータコレクタは、 Hitachi Ops Center の統合されたアプリケーションスイートを使用して、複数のストレージデバイスのインベントリとパフォーマンスのデータにアクセスします。インベントリと容量を検出するには、 Operations Center のインストールに「 Common Services 」と「 Administrator 」の両方のコンポーネントを含める必要があります。パフォーマンス収集では、さらに「 Analyzer 」を導入する必要があります。



== 用語

Data Infrastructure Insightsは、このデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ストレージシステム | ストレージ 


| ボリューム | ボリューム 


| パリティグループ | ストレージプール（ RAID ）、ディスクグループ 


| ディスク | ディスク 


| ストレージプール | ストレージプール（シン、スナップ） 


| 外部パリティグループ | ストレージプール（バックエンド）、ディスクグループ 


| ポート | ストレージノード→コントローラノード→ポートの順にクリックします 


| ホストグループ | ボリュームのマッピングとマスキング 


| ボリュームペア | ストレージ同期 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== インベントリの要件

インベントリデータを収集するには、次の情報が必要です。

* 「Common Services」コンポーネントをホストするOps CenterサーバのIPアドレスまたはホスト名
* ルート/ sysadminユーザアカウントとパスワード。Ops Centerコンポーネントをホストするすべてのサーバに存在します。HDSでは、Ops Center 10.8以降まで、LDAP/SSOユーザによるREST APIサポートは実装されていませんでした




== パフォーマンス要件

パフォーマンスデータを収集するには、次の要件を満たしている必要があります。

HDS Ops Centerの「Analyzer」モジュールをインストールし、Operations Centerの「Analyzer」モジュールにデータを供給する必要があります



== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| Hitachi Ops Center の IP アドレス | 「 Common Services 」コンポーネントをホストする Ops Center サーバの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | Ops Center サーバのユーザ名。 


| パスワード | Ops Center サーバのパスワード。 
|===


== 高度な設定

|===


| フィールド | 製品説明 


| 接続タイプ | デフォルトは HTTPS （ポート 443 ）です 


| TCP ポートを上書きします | デフォルト以外の場合に使用するポートを指定します 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは40です。 


| 「除外」または「含める」を選択してリストを指定します | 下のリストに表示されたアレイをデータの収集時に対象に含めるか除外するかを指定します。 


| デバイスリストをフィルタリングします | 対象に含めるか除外するデバイスのシリアル番号をカンマで区切ったリスト 


| パフォーマンスポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは300です。 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
