---
sidebar: sidebar 
permalink: task_dc_netapp_eseries_rest.html 
keywords: data collector, ontap, clustered ontap, REST 
summary: NetApp EシリーズRESTデータコレクタの設定 
---
= NetApp EシリーズRESTデータコレクタ
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp EシリーズRESTデータコレクタは、インベントリとパフォーマンスのデータを収集します。コレクタは、同じ設定を使用して同じデータを報告するファームウェア 7.x 以上をサポートしています。RESTコレクタは、ストレージプールの暗号化ステータスと関連するディスクおよびボリュームの暗号化ステータスを監視し、ストレージノードのCPU利用率をパフォーマンスカウンタとして提供します。これは、従来のSANtricity Eシリーズコレクタでは提供されていない機能です。



== 用語

Insightでは、RESTを使用して、NetApp Eシリーズから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| ボリュームグループ | ディスクグループ 


| ストレージアレイ | ストレージ 


| コントローラ | ストレージノード 


| ボリュームグループ | ストレージプール 


| ボリューム | ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* アレイの各コントローラの IP アドレス
* このコレクタは、*ネイティブのREST API機能*を備えたEシリーズモデルアレイのみをサポートします。Eシリーズ部門には、古いEシリーズアレイ向けにオフアレイでインストール可能なREST APIディストリビューションが付属しています。このコレクタではこのシナリオはサポートされません。古いアレイを使用している場合は、引き続きData Infrastructure Insightsのlink:task_dc_na_eseries.html["EシリーズSANtricity API"]コレクタを使用する必要があります。
* [Eシリーズ Controller IP Addresses]フィールドでは、2つのIP /ホスト名をカンマで区切って指定できます。1つ目のIP /ホスト名にアクセスできない場合、コレクタは2つ目のIP /ホスト名をインテリジェントに試行します。
* HTTPSポート：デフォルトは8443です。




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| EシリーズコントローラのIPアドレス | アレイコントローラのIPアドレスまたは完全修飾ドメイン名をカンマで区切って指定 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | デフォルトは30分です 


| パフォーマンスポーリング間隔（最大 3600 秒） | デフォルトは300秒です 
|===


== E シリーズの用語（ランディングページ）

NetApp E シリーズのアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* Model –デバイスのモデル名。
* Vendor ：新しいデータソースを設定する場合に表示されるベンダー名と同じです
* Serial Number –アレイのシリアル番号。NetApp clustered Data ONTAP などのクラスタアーキテクチャストレージシステムでは、このシリアル番号は個々の「ストレージノード」のシリアル番号よりも便利でない場合があります
* IP –一般に、データソースで設定されている IP またはホスト名です
* マイクロコードバージョン–ファームウェア
* raw 容量–システム内のすべての物理ディスクの合計 2 進数で、役割に関係なく加算されます
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。理想的なのは、Data Infrastructure Insightsがこの価値を直接提供していることですが、そうではないことがよくあります。Data Infrastructure Insightsでは、この機能を提供するアレイの代わりに、通常、個 々 のボリュームの統計に基づいてIOPSの加重計算を実行します。
* スループット–アレイのホスト側のスループットの合計Data Infrastructure Insightsはアレイから直接調達するのが理想的で、利用できない場合はボリュームのスループットを合計してこの値を算出
* 管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。インベントリレポートの一部として、Data Infrastructure Insightsデータソースによってプログラムによって作成されます。  




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「シン・プロビジョニング」または「 RAID グループ」です。
* ノード：プールが特定のストレージノードに属するようなストレージアレイのアーキテクチャの場合、その名前は、そのストレージアレイのランディングページへのハイパーリンクとして表示されます
* Flash Pool を使用します。値はありますか、いいえです
* 冗長性– RAID レベルまたは保護方式。E シリーズでは、 DDP プールの場合は「 RAID 7 」と報告されます
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。これらの値には、 E シリーズの「予約済み」容量が含まれ、 E シリーズのユーザインターフェイスで表示される値よりも数値と割合が高くなります
* オーバーコミット容量–効率化テクノロジを使用して、ストレージプールの論理容量を超えるボリュームまたは内部ボリュームの合計容量を割り当てている場合、この割合の値は 0% を超えます。
* スナップショット–スナップショット専用のセグメント領域にストレージプールアーキテクチャが容量の一部を割り当てている場合に使用されるスナップショット容量と合計容量
* 利用率–このストレージプールに容量を追加しているディスクのビジー率の最大値を示した割合。ディスク利用率にアレイのパフォーマンスとの間に大きな相関関係があるとは限りません。ホストベースのワークロードがない場合は、ディスクのリビルドや重複排除処理などが原因で、利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、ボリュームワークロードとして表示されずにディスク使用率が向上する場合があります。
* IOPS –このストレージプールに容量の要因となっているすべてのディスクの合計 IOPS 。特定のプラットフォームのディスク IOPS がない場合、この値は、このストレージプールにあるすべてのボリュームのボリューム IOPS の合計から取得されます
* Throughput –このストレージプールの容量の要因となっているすべてのディスクの合計スループット。特定のプラットフォームでディスクスループットを使用できない場合は、このストレージプールに配置されているすべてのボリュームの合計ボリューム数がこの値に基づいて算出されます




=== ストレージノード

* Storage –このノードが属するストレージアレイ。必須
* HA パートナー–通常、一方のノードだけにフェイルオーバーするプラットフォームでは、この画面が表示されます
* State –ノードの健常性。アレイが正常な状態でデータソースでインベントリを作成できる場合にのみ使用できます
* model - ノードのモデル名
* Version ：デバイスのバージョン名。
* シリアル番号–ノードのシリアル番号
* メモリ–ベース 2 のメモリがあればそれ
* 利用率–通常は CPU 利用率番号、または NetApp ONTAP の場合はコントローラに負荷がかかる指標。現在、 NetApp E シリーズでは利用率を利用できません
* IOPS –このコントローラのホスト主導の IOPS を表す数値。理想的なソースはアレイから直接取得され、使用できない場合は、このノードにのみ所属するボリュームのすべての IOPS を合計して算出されます。
* Latency –このコントローラのホストのレイテンシまたは応答時間を表す数値。使用できない場合はアレイから直接ソースを取得し、このノードにのみ所属するボリュームから IOPS の重み付き計算を実行することを推奨します。
* Throughput –このコントローラのホストで実行されるスループットを示す数値です。理想的なソースはアレイから直接取得され、使用できない場合は、このノードにのみ所属するボリュームのすべてのスループットを合計して算出されます。
* プロセッサ– CPU 数




== トラブルシューティング

このデータコレクタの詳細については、ページまたはを参照してlink:concept_requesting_support.html["サポート"]link:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]ください。
