---
sidebar: sidebar 
permalink: task_dc_na_storagegrid.html 
summary: NetApp StorageGRID のデータコレクタを設定する 
keywords: data collector, queries, create, storagegrid 
---
= NetApp StorageGRID データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp StorageGRID データコレクタでは、 StorageGRID 構成からのインベントリやパフォーマンスの収集がサポートされます。

[NOTE]
====
基盤となるハードウェア トポロジと構成に関係なく、すべてのStorageGRIDシステムにわたって DII 権限に対する一貫した計測を提供するために、 Data Infrastructure Insights は、物理ディスク レイアウトに基づく RAW 容量ではなく、使用可能な合計容量 (storagegrid_storage_utilization_total_space_bytes) を使用します。

容量ベースのライセンス モデルを使用しているお客様の場合、 StorageGRIDは「オブジェクト」ストレージとして計測されます。

従来の (MU) ライセンス モデルを使用しているお客様の場合、 StorageGRIDはセカンダリ ストレージとして 40TiB から 1 MU のレートで計測されます。

====


== 用語

Data Infrastructure Insightsでは、NetApp StorageGRIDコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| StorageGRID | ストレージ 


| ノード | ノード 


| テナント | ストレージプール 


| バケット | 内部ボリューム 
|===


== 要件

このデータソースの設定に関する要件は次のとおりです。

* StorageGRID ホストの IP アドレス
* Metric Query ロールとテナントアクセスロールが割り当てられているユーザのユーザ名とパスワード
* ポート443




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| StorageGRID ホストの IP アドレス | StorageGRID アプライアンスの管理仮想 IP アドレス 


| ユーザー名 | StorageGRID アプライアンスへのログインに使用する名前 


| パスワード | StorageGRID アプライアンスへのログインに使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | デフォルトは60分です 


| パフォーマンスポーリング間隔（秒） | デフォルトは900秒です 
|===


== シングルサインオン（ SSO ）

link:https://docs.netapp.com/sgws-112/index.jsp["StorageGRID"]ファームウェアバージョンには対応するAPIバージョンがあり、3.0 API以降のバージョンではシングルサインオン（SSO）ログインがサポートされます。

|===


| ファームウェアバージョン | APIバージョン | シングルサインオン（ SSO ）のサポート 


| 11.1 | 2 | いいえ 


| 11.2 | 3.0 | はい 


| 11.5 | 3.3 | はい 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
