---
sidebar: sidebar 
permalink: task_modify_delete_query.html 
summary: 条件や列を変更することで既存のクエリを修正でき、更新、名前変更、新規バージョン作成のための柔軟な保存オプションに加え、不要になったクエリを削除するオプションも用意されています。 
keywords: query, queries, modify, edit, delete, remove 
---
= クエリの変更または削除
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
検索条件の変更、列の追加または削除、柔軟な保存オプションの選択などにより、クエリを効果的に管理できます。既存のクエリを更新したり、新しいバージョンを作成したり、不要になったクエリを削除したりすることで、クエリライブラリを整理し、最新の状態に保つことができます。



[[modifying-a-query]]
== クエリの変更

.手順
. *探索*をクリックし、*すべてのメトリッククエリ*を選択します。
+
クエリ ページが表示されます。

. クエリ名をクリック
. クエリに条件を追加するには、列アイコンをクリックし、リストからメトリックまたは属性を選択します。


必要な変更をすべて行ったら、次のいずれかを実行します。

* *[保存]* ボタンをクリックして、最初に使用した名前でクエリを保存します。
* *保存*ボタンの横にあるドロップダウンをクリックし、*名前を付けて保存*を選択して、クエリを別の名前で保存します。これによって元のクエリが上書きされることはありません。
* *保存*ボタンの横にあるドロップダウンをクリックし、*名前の変更*を選択して、最初に使用したクエリ名を変更します。これにより、元のクエリが上書きされます。
* *保存*ボタンの横にあるドロップダウンをクリックし、*変更を破棄*を選択して、クエリを最後に保存した変更に戻します。




[[deleting-a-query]]
== クエリの削除

クエリを削除するには、[*クエリ*] をクリックし、[*すべてのクエリを表示*] を選択して、次のいずれかを実行します。

. クエリの右側にある「3 つのドット」メニューをクリックし、「削除」をクリックします。
. クエリ名をクリックし、[保存] ドロップダウン メニューから [削除] を選択します。

