---
sidebar: sidebar 
permalink: task_dc_ibm_ds4000.html 
keywords: data collector, IBM, DS4000 
summary: IBM TotalStorage DS4000 データコレクタ 
---
= IBM TotalStorage DS4000 データコレクタ
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このデータコレクタは 'IBM DS4000 ストレージ・システムからインベントリおよびパフォーマンス情報を取得します可能な構成は 2 種類（ファームウェア 6.x とファームウェア 7.x 以降）で、値はどちらも同じです。



== 用語

Data Infrastructure Insightsは、IBM DS4000データコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| ボリュームグループ | ディスクグループ 


| ストレージアレイ | ストレージ 


| コントローラ | ストレージノード 


| ボリュームグループ | ストレージプール 


| ボリューム | ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* DS5 または FAStT の各アレイの IP アドレス
* アレイの両方のコントローラの IP アドレスに ping を実行してアクセスを検証します
* ポートの要件：2463




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| アレイ SANtricity コントローラの IP をカンマで区切ったリスト | アレイコントローラの IP アドレスまたは完全修飾ドメイン名 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | デフォルトは30分です 


| パフォーマンスポーリング間隔（最大 3600 秒） | デフォルトは300秒です 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
