---
sidebar: sidebar 
permalink: task_dc_emc_vnx_unified.html 
keywords: data collector, VNX, EMC, Dell 
summary: VNXデータコレクタの設定 
---
= Dell EMC VNX Unified データコレクタの設定
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Dell EMC VNX Unified （ SSH ）データコレクタを設定するには、 Control Station の IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。



== 用語

Data Infrastructure Insightsは、このデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| ディスクフォルダ | ディスクグループ 


| ファイルシステム | 内部ボリューム 


| ストレージ | ストレージ 


| ストレージプロセッサ | ストレージノード 


| ストレージプール、 RAID グループ | ストレージプール 


| LUN | ボリューム 


| データムーバー | コントローラ 


| データムーバーにマウントされたファイルシステム | ファイル共有 


| CIFS および NFS エクスポート | 共有 


| ディスクボリューム | バックエンド LUN 
|===


== 要件

VNX （ SSH ）データコレクタを構成するには、次のものが必要です。

* VNX IP アドレスと資格情報を Celerra Control Station に追加します。
* 読み取り専用のユーザ名とパスワード
* データコレクタは 'DART OS NAS ヘッドを使用して ' バックエンド・アレイに対して NaviCLI/naviseccli コマンドを実行できます




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| VNX IP アドレス | VNX Control Station の IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNX Control Station のユーザー名 


| パスワード | VNX Control Station のパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは40分です。 


| パフォーマンスポーリング間隔（秒）。 | パフォーマンスのポーリング間隔デフォルトは300秒です。 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
