---
sidebar: sidebar 
permalink: task_dc_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: HDS Ops Center データ コレクターを構成します。 
---
= 日立オプスセンターデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、Hitachi Ops Center の統合アプリケーション スイートを使用して、複数のストレージ デバイスのインベントリおよびパフォーマンス データにアクセスします。インベントリと容量の検出のために、Ops Center インストールには「Common Services」コンポーネントと「Administrator」コンポーネントの両方が含まれている必要があります。パフォーマンス収集には、「Analyzer」を追加で導入する必要があります。



== 用語

Data Infrastructure Insights は、このデータ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ システム | ストレージ 


| Volume | Volume 


| パリティグループ | ストレージプール（RAID）、ディスクグループ 


| ディスク | ディスク 


| ストレージ プール | ストレージプール（Thin、SNAP） 


| 外部パリティグループ | ストレージプール（バックエンド）、ディスクグループ 


| ポート | ストレージノード → コントローラノード → ポート 


| ホストグループ | ボリュームマッピングとマスキング 


| ボリュームペア | ストレージ同期 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 在庫要件

インベントリ データを収集するには、次のものが必要です。

* 「共通サービス」コンポーネントをホストする Ops Center サーバーの IP アドレスまたはホスト名
* Ops Center コンポーネントをホストするすべてのサーバーに存在する root/sysadmin ユーザー アカウントとパスワード。  HDS は、Ops Center 10.8 以降まで、LDAP/SSO ユーザーによる使用のための REST API サポートを実装していませんでした。




== パフォーマンス要件

パフォーマンス データを収集するには、次の要件を満たす必要があります。

HDS Ops Center「アナライザ」モジュールをインストールする必要があります。ストレージアレイはOps Center「アナライザ」モジュールにデータを供給する必要があります。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| 日立オプスセンターIPアドレス | 「共通サービス」コンポーネントをホストする Ops Center サーバーの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | Ops Center サーバーのユーザー名。 


| パスワード | Ops Center サーバーに使用されるパスワード。 
|===


== 高度な設定

|===


| フィールド | 説明 


| 接続タイプ | HTTPS（ポート443）がデフォルトです 


| TCPポートの上書き | デフォルト以外の場合に使用するポートを指定します 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは 40 です。 


| リストを指定するには「除外」または「含める」を選択します | データを収集するときに、以下の配列リストを含めるか除外するかを指定します。 


| フィルターデバイスリスト | 含めるまたは除外するデバイスのシリアル番号のコンマ区切りリスト 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。デフォルトは 300 です。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
