---
sidebar: sidebar 
permalink: task_dc_ibm_cs.html 
keywords: data collector, IBM CS, CS Series 
summary: IBM CS データコレクタの設定。 
---
= IBM CS データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsは、このデータコレクタを使用して、IBM CSストレージシステムのインベントリデータとパフォーマンスデータを検出します。



== 用語

Data Infrastructure Insightsは、IBM CSデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ストレージプール | ストレージプール 


| コンテナ | 内部ボリューム 


| コンテナ | ファイル共有 


| NFS共有 | 共有 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* クラスタの外部データサービスの IP アドレス
* 管理者のユーザ名とパスワード
* ポート9440




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| プリズム外部 IP アドレス | クラスタの外部データサービスの IP アドレス 


| ユーザ名 | 管理者アカウントのユーザ名 


| パスワード | 管理者アカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| TCP ポート | IBM CS アレイへの接続に使用する TCP ポート。デフォルトは9440です。 


| インベントリのポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは60分です。 


| パフォーマンスのポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは300秒です。 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
