---
sidebar: sidebar 
permalink: task_dc_na_ontap_afx.html 
keywords: data collector, ontap, afx 
summary: ONTAP AFXコレクター 
---
= NetApp ONTAP AFX データコレクター
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このデータ コレクターは、REST API 呼び出しを使用して、 ONTAP 9.16.0 以降を実行しているストレージ システムからインベントリ、EMS ログ、およびパフォーマンス データを取得します。



== 要件

このデータ コレクターを構成して使用するための要件は次のとおりです。

* 必要なアクセス レベルを持つユーザー アカウントにアクセスできる必要があります。新しい REST ユーザー/ロールを作成する場合は、管理者権限が必要であることに注意してください。
+
** 機能的には、 Data Infrastructure Insights は主に読み取り要求を行いますが、 Data Infrastructure Insights をONTAPアレイに登録するには、いくつかの書き込み権限が必要です。すぐ下の「権限に関する注意」を参照してください。


* ONTAPバージョン 9.16.0 以上。
* ポート要件: 443




== 権限に関する注意事項

Data Infrastructure InsightsのONTAPダッシュボードの多くは高度なONTAPカウンターに依存しているため、データ コレクターの詳細設定セクションで *高度なカウンター データ収集を有効にする* を有効のままにしておく必要があります。

クラスタ レベルでData Infrastructure Insightsのローカル アカウントを作成するには、クラスタ管理管理者のユーザー名とパスワードを使用してONTAPにログインし、 ONTAPサーバーで次のコマンドを実行します。

. 開始する前に、_管理者_アカウントでONTAPにサインインし、_診断レベルのコマンド_を有効にする必要があります。
. タイプが _admin_ である vserver の名前を取得します。後続のコマンドではこの名前を使用します。
+
 vserver show -type admin
. 次のコマンドを使用してロールを作成します。
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
....
. 次のコマンドを使用して読み取り専用ユーザーを作成します。作成コマンドを実行すると、このユーザーのパスワードを入力するよう求められます。
+
 security login create -username ci_user -application http -authentication-method password -role ci_readonly


AD/LDAPアカウントを使用する場合、コマンドは

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
結果として得られるロールとユーザー ログインは次のようになります。実際の出力は異なる場合があります。

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== 移住

以前のONTAP (ontapi) データ コレクターから新しいONTAP REST コレクターに移行するには、次の手順を実行します。

. REST コレクターを追加します。以前のコレクターに設定されたユーザーとは異なるユーザーの情報を入力することをお勧めします。たとえば、上記の「権限」セクションに記載されているユーザーを使用します。
. 前のコレクターを一時停止して、データの収集を継続しないようにします。
. 新しい REST コレクターが少なくとも 30 分間データを取得するようにします。この期間中に「正常」と見えないデータはすべて無視します。
. 休止期間後、REST コレクターが引き続きデータを取得し、データが安定するはずです。


必要に応じて、同じプロセスを使用して、前のコレクターに戻ることができます。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| ONTAP管理IPアドレス | NetAppクラスタの IP アドレスまたは完全修飾ドメイン名。クラスター管理 IP/FQDN である必要があります。 


| ONTAP RESTユーザー名 | NetAppクラスタのユーザー名 


| ONTAP REST パスワード | NetAppクラスタのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは 60 分です。 


| パフォーマンスポーリング間隔（秒） | デフォルトは60秒です。 


| 高度なカウンターデータ収集 | ポーリングにONTAPアドバンスド カウンタ データを含めるには、これを選択します。デフォルトは有効です。 


| EMSイベント収集を有効にする | ONTAP EMS ログ イベント データを含めるにはこれを選択します。デフォルトは有効です。 


| EMSポーリング間隔（秒） | デフォルトは60秒です。 
|===


== 用語

Data Infrastructure Insights は、 ONTAPデータ コレクターからインベントリ、ログ、パフォーマンス データを取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| クラスタ | ストレージ 


| ノード | ストレージノード 


| ボリューム/ FlexVol/ FlexGroup | 内部ボリューム 


| Qtree/フレックスツリー | Qtree (タイプ: Explixit/Default) 


| S3 バケット | Qtree (タイプ: バケット) 


| ストレージポッド/ストレージ可用性ゾーン | ストレージプール 


| 共有 | 共有 


| クォータ | クォータ 


| SVM (ストレージ仮想マシン) | Storage Virtual Machine 
|===


== ONTAPデータ管理用語

次の用語は、 ONTAP Data Management ストレージ アセットのランディング ページに表示されるオブジェクトまたは参照に適用されます。これらの条件の多くは他のデータ収集者にも適用されます。



=== ストレージ

* モデル – このクラスター内の一意の個別のノード モデル名のカンマ区切りリスト。クラスター内のすべてのノードが同じモデル タイプである場合、モデル名が 1 つだけ表示されます。
* ベンダー – 新しいデータ ソースを構成する場合に表示されるのと同じベンダー名。
* シリアル番号 – アレイUUID
* IP – 通常は、データ ソースで構成されている IP またはホスト名になります。
* マイクロコード バージョン - ファームウェア。
* 生の容量 – 役割に関係なく、システム内のすべての物理ディスクの 2 を底とする合計。
* レイテンシ – 読み取りと書き込みの両方において、ホスト側のワークロードが経験している状況を表します。理想的には、 Data Infrastructure Insightsがこの値を直接取得しますが、多くの場合そうではありません。アレイがこれを提供する代わりに、 Data Infrastructure Insightsは通常、個々の内部ボリュームの統計から導き出された IOPS 加重計算を実行します。
* スループット – 内部ボリュームから集計されます。管理 – これにはデバイスの管理インターフェイスへのハイパーリンクが含まれる場合があります。インベントリレポートの一部として、 Data Infrastructure Insightsデータ ソースによってプログラムによって作成されます。




=== ストレージ プール

* ストレージ – このプールが存在するストレージ アレイ。必須。
* タイプ – 可能性のある列挙リストからの説明的な値。最も一般的なのは「アグリゲート」または「RAID グループ」です。
* ノード – このストレージ アレイのアーキテクチャで、プールが特定のストレージ ノードに属している場合、その名前は独自のランディング ページへのハイパーリンクとしてここに表示されます。
* フラッシュ プールの使用 – はい/いいえの値 – この SATA/SAS ベースのプールには、キャッシュ アクセラレーションに使用される SSD がありますか?
* 冗長性 – RAID レベルまたは保護スキーム。  RAID_DP はデュアル パリティ、RAID_TP はトリプル パリティです。
* 容量 – ここでの値は、論理的に使用されている容量、使用可能な容量、論理的な合計容量、およびこれらの間で使用されている割合です。
* 過剰コミット容量 – 効率化テクノロジを使用して、ストレージ プールの論理容量よりも大きいボリュームまたは内部ボリューム容量の合計を割り当てた場合、ここでのパーセンテージ値は 0% より大きくなります。
* スナップショット – ストレージ プール アーキテクチャが容量の一部をスナップショット専用のセグメント領域に割り当てている場合の、スナップショットの使用済み容量と合計容量。  MetroCluster構成のONTAPではこの問題が発生する可能性が高くなりますが、他のONTAP構成ではこの問題は発生しにくくなります。
* 使用率 – このストレージ プールに容量を提供しているディスクのうち最も高いディスク使用率を示すパーセンテージ値。ディスク使用率は、必ずしもアレイのパフォーマンスと強い相関関係があるわけではありません。ホスト駆動型のワークロードがない場合、ディスクの再構築、重複排除アクティビティなどにより、使用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームまたはボリュームのワークロードとして表示されずにディスク使用率が向上する場合があります。
* IOPS – このストレージ プールに容量を提供しているすべてのディスクの合計 IOPS。スループット – このストレージ プールに容量を提供しているすべてのディスクの合計スループット。




=== ストレージ ノード

* ストレージ – このノードが属するストレージ アレイ。必須。
* HA パートナー - ノードが他の 1 つのノードにのみフェールオーバーするプラットフォームでは、通常ここに表示されます。
* 状態 – ノードの健全性。アレイがデータ ソースによってインベントリされるのに十分正常な場合にのみ使用できます。
* モデル – ノードのモデル名。
* バージョン – デバイスのバージョン名。
* シリアル番号 – ノードのシリアル番号。
* メモリ – 使用可能な場合は 2 進メモリ。
* 使用率 – ONTAPでは、これは独自のアルゴリズムによるコントローラ ストレス インデックスです。すべてのパフォーマンス ポーリングでは、 WAFLディスク競合または平均 CPU 使用率のいずれか大きい方の 0 ～ 100% の数値が報告されます。継続的に 50% を超える値が観測される場合は、サイズ不足を示しています。つまり、書き込みワークロードを吸収するのに十分な大きさのコントローラー/ノードがないか、回転ディスクが足りない可能性があります。
* IOPS – ノード オブジェクトに対するONTAP REST 呼び出しから直接導出されます。
* レイテンシ – ノード オブジェクトに対するONTAP REST 呼び出しから直接導出されます。
* スループット – ノード オブジェクトに対するONTAP REST 呼び出しから直接導出されます。
* プロセッサ – CPU 数。




== ONTAP電力メトリクス

いくつかのONTAPモデルでは、監視やアラートに使用できるData Infrastructure Insightsの電力メトリックが提供されます。以下のサポートされているモデルとサポートされていないモデルのリストは包括的なものではありませんが、何らかのガイダンスを提供します。一般に、モデルがリストにあるモデルと同じファミリーに属している場合、サポートは同じです。

対応モデル:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

サポートされていないモデル:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:

[cols="2*"]
|===
| 問題： | これを試してください: 


| ONTAP REST データコレクターを作成しようとすると、次のようなエラーが表示されます: 構成: 10.193.70.14: 10.193.70.14 のONTAP REST API は使用できません: 10.193.70.14 が GET /api/cluster に失敗しました: 400 不正な要求 | これは、REST API 機能がない古いONTAPアレイ (たとえば、 ONTAP 9.6) が原因である可能性があります。  ONTAP 9.14.1 は、 ONTAP REST コレクターでサポートされる最小のONTAPバージョンです。  REST ONTAPより前のリリースでは、「400 Bad Request」応答が予想されます。  REST をサポートしているが 9.14.1 以降ではないONTAPバージョンの場合、次のような類似のメッセージが表示されることがあります: 構成: 10.193.98.84: 10.193.98.84 のONTAP REST API は使用できません: 10.193.98.84: 10.193.98.84 のONTAP REST API は使用できます: cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-11ee-8ff3-005056b364a7 ただし、最小バージョン 9.14.1 ではありません。 


| ONTAP ontapi コレクターがデータを表示する場所に、空または「0」のメトリックが表示されます。 | ONTAP REST は、 ONTAPシステムでのみ内部的に使用されるメトリックを報告しません。たとえば、システム アグリゲートはONTAP REST によって収集されず、「データ」タイプの SVM のみが収集されます。ゼロまたは空のデータを報告する可能性があるONTAP REST メトリックのその他の例: InternalVolumes: REST は vol0 を報告しなくなりました。集計: REST は aggr0 を報告しなくなりました。ストレージ: ほとんどのメトリックは内部ボリューム メトリックのロールアップであり、上記の影響を受けます。ストレージ仮想マシン: REST は、「データ」以外のタイプ (「クラスター」、「管理」、「ノード」など) の SVM を報告しなくなりました。また、デフォルトのパフォーマンス ポーリング期間が 15 分から 5 分に変更されたため、データがあるグラフの外観が変わる場合があります。ポーリングの頻度が高ければ、プロットするデータ ポイントの数も多くなります。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
