---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 大量の I/O 密度を照会する際に、ルートボリュームを除外する。 
keywords: NetApp, root volume, high I/O, 
---
= I/O 密度レポートに内部データボリュームのみが記載されていることを確認する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
ネットアップのルートボリュームには、ストレージシステムを管理するためのディレクトリと構成ファイルが格納されています。大量の I/O 密度を照会する際に、これらのルートボリュームを除外する。

環境を監視する際には、どの内部データボリュームが高い I/O 密度を生成しているかを特定することが重要です。データボリュームのみを正確に特定するには、NetApp内部ボリュームをI/O密度の監視に使用するクエリから分離する必要があります。

本書では、NetAppルートアグリゲートを簡単に特定し、それらを内部ボリュームのクエリの結果から分離する方法、およびシステムに追加される新しいNetAppルートアグリゲートを除外するルールを作成する方法について説明します。I/O 密度レポートに内部データボリュームだけの情報を出力するには、 Insight の次の機能を使用します。

* Insight で監視しているネットアップのルートアグリゲートを特定するクエリを作成する。
* NetAppの各ルートアグリゲートにアノテーションが割り当てられます。
* 新しいネットアップのルートアグリゲートにアノテーションを適用するためのアノテーションルールが作成されます。


このガイドで説明する手順は、他のベンダーのストレージシステムにも適用できます。ストレージシステムを管理するためのディレクトリおよび構成ファイルが格納されたボリュームを特定し、同様の手順を使用してこれらのボリュームを除外する必要があります。



== NetAppルートアグリゲートを特定するクエリの作成

クエリは、ユーザが選択した条件に基づいて、細かいレベルまで検索する機能です。クエリを使用すると、NetAppルートアグリゲートを含むテナントの内部ボリュームを検索できます。

.手順
. テナント上のNetAppルートアグリゲートを特定するクエリを作成します。*[Queries]>[New Query]>[Select Resource Type]*（？）をクリックします。
. [ ストレージプール ] をクリックします
. ルートアグリゲートの名前を入力します
+
この例では、名前に「 aggr0 」を使用します。アグリゲートの作成時には、次の要件に従って名前を指定する必要があります。

+
.. 先頭の文字にはアルファベットまたはアンダースコア（ _ ）を使用する必要があります。
.. アルファベット、数字、アンダースコアのみを使用できます。
.. 250 文字以内で指定します。アグリゲートの名前は通常、 aggr0 、 aggr_0 などの形式にします。テナント上のすべてのNetAppルートアグリゲートを特定するには、反復的なプロセスが必要になる場合があります。


. [ 保存（ Save ） ] をクリックし、新しい照会の名前を入力する。
+
前述したように、これは反復的なプロセスである可能性があり、すべてのNetAppルートアグリゲートを特定するために複数のクエリが必要になる場合があります。





== クエリで返されるルートボリューム用のアノテーションを作成します

アノテーションはアセットに割り当てる特殊なメモで、アノテーションによってアセットをフィルタすることができます。作成するアノテーションは、テナントのNetAppルートアグリゲートを特定し、特定のレポートに含まれないようにするために使用します。

.開始する前に
「 High I/O Density 」レポートから除外するルートアグリゲートをすべて特定しておく必要があります。

.手順
. [Data Infrastructure Insights]メニューで、*[Manage]>[Annotations]*をクリックします。
. [ 追加（ Add ） ] をクリックします。
+
.. アノテーションの名前として「 * RootAggr 」と入力します
.. アノテーションの概要として「 * Remove root aggregate from "High I/O Density" report * 」と入力します
.. アノテーションのタイプとして「 * Boolean * 」と入力します


. [ 保存（ Save ） ] をクリックします。




== I/O 密度に関するレポートから特定のアグリゲートを自動的に除外するためのアノテーションルールの作成

アノテーションを個々のアセットに手動で適用する代わりに、アノテーションルールを使用して複数のアセットに自動的にアノテーションを適用することができます。アノテーションルールは、ユーザが作成するクエリに基づいてシステム上で実行されるもので、新しいアセットを既存のアセットセットに追加します。これらのアセットセットをレポートから除外すると、新しいアセットも自動的に除外されます。

.開始する前に
テナントで特定したNetAppルートアグリゲートを識別するクエリを作成して保存しておく必要があります。

.手順
. [Data Infrastructure Insights ]ツールバーで、*[管理]>[アノテーションルール]*をクリックします。
. [追加]*をクリックします。[Add Rule]ダイアログが表示されます。
+
.. [Name]ボックスに、ルールを説明する一意の名前「*"RootAggrExclude"*」を入力します
.. [Query]をクリックし、アノテーションルールを適用するためにInsightで使用するクエリ*「Aggregate0」*を選択します
.. [Annotation]をクリックし、*「Root agg exclude」*を選択します
.. 「 * Value * 」をクリックし、「 * True * 」と入力します



