---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECSデータコレクタの設定 
---
= EMC ECSデータコレクタの設定
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータコレクタは、EMC ECSストレージシステムからインベントリデータとパフォーマンスデータを取得します。データコレクタを設定するには、ECSクラスタのIPアドレスまたはホスト名、およびユーザ名とパスワードが必要です。


NOTE: Dell EMC ECSでは、raw TBから管理ユニットへの異なるレートが使用されます。フォーマットされていないECS容量が40TBにつき1として課金されますlink:concept_subscribing_to_cloud_insights.html#pricing["管理ユニット (MU)"]。



== 用語

Data Infrastructure Insightsは、ECSデータコレクタから次のインベントリ情報を取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| クラスタ | ストレージ 


| テナント | ストレージプール 


| バケット | 内部ボリューム 


| ディスク | ディスク 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* ECSクラスタのIPアドレスまたはホスト名
* ECSシステムのユーザ名とパスワード
* ポート4443（HTTPS）。ECSシステムのTCPポート4443へのアウトバウンド接続が必要です。




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| ECSホスト | ECS システムの IP アドレスまたは完全修飾ドメイン名 


| ECS ホストポート | ECS ホストとの通信に使用されるポート 


| ECSユーザーID | ECSのユーザID 


| パスワード | ECS のパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | デフォルトは360分です。 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



==== インベントリ

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー：ユーザ認証に失敗しました。 | このデバイスのクレデンシャルが正しいことを確認してください。 
|===


==== パフォーマンス

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー：十分なデータが収集されていません。 | •ログファイルの収集タイムスタンプを確認し、それに応じてポーリング間隔を変更する•長い時間を待つ 


| エラー：パフォーマンスのポーリング間隔が長すぎます。 | ログファイル $ ｛ logfile ｝ の収集タイムスタンプを確認し、それに応じてポーリング間隔を変更してください 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
