---
sidebar: sidebar 
permalink: task_dc_rubrik_cdm.html 
keywords: data collector, Rubrik, 
summary: Rubrik CDM データ コレクターを構成します。 
---
= Rubrik CDM データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Rubrik データ コレクターを使用して、Rubrik ストレージ アプライアンスからインベントリ データとパフォーマンス データを取得します。



== 用語

Data Infrastructure Insights は、 Rubrik データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| クラスタ | ストレージ、ストレージプール 


| ノード | ストレージ ノード 


| ディスク | ディスク 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ ソースのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次のものが必要です。

* Data Infrastructure Insights取得ユニットは、Rubrik クラスターへの TCP ポート 443 への接続を開始します。クラスターごとに 1 つのコレクター。
* Rubrik クラスターの IP アドレス。
* クラスターへのユーザー名とパスワード。
* Rubrik クラスターの IP アドレスまたはホスト名。
* 基本認証の場合、クラスターへのユーザー名とパスワード。サービスアカウントベースの認証を使用する場合は、サービスアカウント、シークレット、組織IDが必要です。
* ポート要件: HTTPS 443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| IP | Rubrik クラスタの IP アドレス 


| ユーザー名 / サービスアカウント | クラスターのユーザー名 


| パスワード/シークレット | クラスターのパスワード 


| サービスアカウントの組織ID | これは、「Organization:::nnnnnn-nnnn.....」のような完全な文字列である必要があります。 
|===


== 高度な設定

[cols="2*"]
|===
| インベントリポーリング間隔（分） | デフォルトは60です 


| パフォーマンスポーリング間隔（秒） | デフォルトは300です 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| 複数のストレージが作成されたというメッセージが表示されました。 | クラスターが正しく構成され、コレクターが単一のクラスターを指していることを確認します。 


| ポーリングが 400 [Bad Request] で失敗しました....ManagedId が無効です.... | 組織 ID フィールドに値を入力しましたが、Rubrik からのエラー メッセージで「ManagedId」と表示されているにもかかわらず、Rubrik クラスターではそれが有効な組織 ID であると認識されません。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
