---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Dell EMC PowerStore データコレクタの設定 
---
= Dell EMC PowerStore データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC PowerStore データ・コレクタは 'EMC PowerStore ストレージからインベントリ情報を収集しますデータコレクタを設定するには、ストレージプロセッサの IP アドレス、および読み取り専用のユーザ名とパスワードが必要です。

EMC PowerStore データ・コレクタは 'PowerStore が他のストレージ・アレイ間で調整するボリューム間レプリケーション関係を収集しますData Infrastructure Insightsには、各PowerStoreクラスタのストレージアレイが表示され、そのクラスタのノードとストレージポートのインベントリデータが収集されます。ストレージプールまたはボリュームのデータは収集されません。



== 用語

Data Infrastructure Insightsは、このデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ホスト | ホスト 


| host_volume_mapping | host_volume_mapping 


| ハードウェア（「 extra_details 」オブジェクトにドライブが含まれています）：ドライブ | ディスク 


| アプライアンス | ストレージプール 


| クラスタ | ストレージアレイ 


| ノード | ストレージノード 


| FC ポート | ポート 


| ボリューム | ボリューム 


| 内部ボリューム | ファイルシステム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

このデータコレクタを設定するには、次の情報が必要です。

* ストレージプロセッサの IP アドレスまたは完全修飾ドメイン名
* 読み取り専用のユーザ名とパスワード




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| PowerStore ゲートウェイ | PowerStore ストレージの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | PowerStore のユーザー名 


| パスワード | PowerStore のパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| HTTPSポート | デフォルトは443です 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは60分です。 
|===
Cloud Insight の PowerStore パフォーマンスコレクションは、 PowerStore の 5 分間のきめ細かいソースデータを利用しています。そのため、Data Infrastructure Insightsは5分ごとにそのデータをポーリングします。このポーリングは設定できません。



== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
