---
sidebar: sidebar 
permalink: task_dc_redhat_virtualization.html 
keywords: data collector, Red Hat Virtualization 
summary: Red Hat Virtualization データコレクターを構成します。 
---
= Red Hat Virtualization データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Red Hat Virtualization データコレクターを使用して、仮想化された Linux および Microsoft Windows ワークロードからインベントリ データを収集します。



== 用語

Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | 仮想ディスク 


| ホスト | ホスト 


| 仮想マシン | 仮想マシン 


| ストレージドメイン | データ ストア 


| 論理ユニット | LUN 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* REST API 経由のポート 443 経由の RHEV サーバーの IP アドレス
* 読み取り専用のユーザー名とパスワード
* RHEV バージョン 3.0 以上




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| RHEV サーバの IP アドレス | ストレージシステムのIPアドレス 


| ユーザ名 | 管理者権限を持つユーザー名 


| 管理者権限アカウントのパスワード | パスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| HTTPS通信ポート | RHEVへのHTTPS通信に使用するポート 


| インベントリポーリング間隔（分） | デフォルトは20分です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
