---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: HP Enterprise Alletra 6000 （旧 Nimble ）データコレクタの設定 
---
= HPE Alletra 6000 データコレクタ
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
HP Enterprise Alletra 6000 （以前の Nimble ）データコレクタは、 Alletra 6000 ストレージアレイのインベントリデータとパフォーマンスデータをサポートしています。



== 用語

Data Infrastructure Insightsでは、このコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| アレイ | ストレージ 


| ディスク | ディスク 


| ボリューム | ボリューム 


| プール | ストレージプール 


| イニシエータ | ストレージホストのエイリアス 


| コントローラ | ストレージノード 


| Fibre Channel インターフェイス | コントローラ 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

ストレージアレイからインベントリデータと構成データを収集するには、次の情報が必要です。

* アレイがインストールおよび設定されていて、クライアントから完全修飾ドメイン名（ FQDN ）またはアレイ管理 IP アドレスを使用して到達できる必要があります。
* アレイで NimbleOS 2.3.x 以降が実行されている必要があります。
* アレイに対する有効なユーザ名とパスワードが「 Operator 」レベル以上のロールで設定されている必要があります。「ゲスト」ロールには、イニシエータの設定を理解するための十分なアクセス権がありません。
* アレイのポート 5392 が開いている必要があります。


ストレージアレイからパフォーマンスデータを収集するには、次の情報が必要です。

* アレイが NimbleOS 4.0.0 以降を実行している必要があります
* アレイにはボリュームが設定されている必要があります。NimbleOSのパフォーマンスAPIはボリュームのみで、Data Infrastructure Insightsの統計はボリュームの統計から取得されます。




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| アレイ管理 IP アドレス | Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）またはアレイ管理 IP アドレスです。 


| ユーザー名 | アレイのユーザ名 


| パスワード | アレイのパスワード 
|===


== 高度な設定

|===


| フィールド | 製品説明 


| ポート | Nimble REST API が使用するポート。デフォルトは5392です。 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは60分です。 
|===
注：デフォルトのパフォーマンスのポーリング間隔は 300 秒で、変更することはできません。HPE Alletra 6000 でサポートされている唯一の間隔です。
