---
sidebar: sidebar 
permalink: task_dc_oracle_zfs.html 
keywords: data collector, Oracle, ZFS, storage applicance 
summary: Oracle ZFS データコレクタを設定しています 
---
= Oracle ZFS Storage Appliance データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsは、Oracle ZFS Storage Applianceデータコレクタを使用してインベントリとパフォーマンスのデータを収集します。



== 用語

Data Infrastructure Insightsは、Oracle ZFSデータコレクタを使用してインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク（SSD） | ディスク 


| クラスタ | ストレージ 


| コントローラ | ストレージノード 


| LUN | ボリューム 


| LUN マップ | ボリュームマップ 


| イニシエータ、ターゲット | ボリュームマスク 


| 共有 | 内部ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータソースのすべてのケースを表しているとは限りません。



== 要件

* ZFS Controller-1 および ZFS Controller-2 のホスト名
* 管理者のユーザ名とパスワード
* ポート要件： 215 HTTP/HTTPS




== 必要なパフォーマンス指標

Oracle ZFSアプライアンスを使用すると、ストレージ管理者はパフォーマンス統計をキャプチャするための柔軟性を大幅に高めることができます。Data Infrastructure Insightsでは、次の指標を取得するようにハイアベイラビリティペアの_each_controllerを設定する必要があります。

* smb2。ops [共有]
* nfs3.ops [共有]
* nfs4.ops [共有]
* nfs4-1.ops [共有]


コントローラがこれらの一部またはすべてをキャプチャしていないと、「内部ボリューム」のワークロードがData Infrastructure Insightsに含まれていないか、アンダーレポートになる可能性があります。



== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| ZFS Controller-1 Hostname（ZFSコントローラ2ホスト名）の略 | ストレージコントローラ1のホスト名 


| ZFS Controller-2 Hostname（ZFSコントローラ2ホスト名）の略 | ストレージコントローラ2のホスト名 


| ユーザ名 | ストレージシステム管理者ユーザアカウントのユーザ名 


| パスワード | 管理者ユーザアカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| 接続タイプ | HTTPS または HTTP では、デフォルトのポートも表示されます 


| 接続ポートを上書きします | 空白の場合は、 [Connection Type] フィールドでデフォルトのポートを使用します。それ以外の場合は、使用する接続ポートを入力します 


| インベントリのポーリング間隔 | デフォルトは60秒です 


| パフォーマンスポーリング間隔（秒） | デフォルトは300です。 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== インベントリ

[cols="2a, 2a"]
|===
| 問題 | 次の操作を実行します 


 a| 
" 無効なログイン資格情報 "
 a| 
ZFS ユーザーアカウントとパスワードを検証します



 a| 
"要求はステータス404 \https://.....:215/api/access/v1"で失敗しました。
 a| 
ZFSアレイが古すぎてREST APIをサポートできない可能性があります。AK 2013.1.3.0はREST API対応の最初のZFS OSリリースであり、すべてのZFSアプライアンスをアップグレードできるわけではありません。



 a| 
「 Configuration error 」というエラーメッセージが表示され、「 REST Service is disabled 」というメッセージが表示されます。
 a| 
このデバイスで REST サービスが有効になっていることを確認します。



 a| 
「 Configuration error 」と表示され、「 User Unauthorized for command 」というエラーメッセージが表示される。
 a| 
このエラーは、特定のロール（「advanced_analytics」など）が設定済みのユーザに含まれていないことが原因で発生する可能性があります。

読み取り専用ロールを持つユーザーにAnalyticsスコープを適用すると、エラーが削除される場合があります。次の手順を実行します。

. ZFSシステムの[Configuration]->[Users]画面で'ロールの上にマウスを移動し'ダブルクリックして編集を許可します
. [Scope]ドロップダウンメニューから[Analytics]を選択します。使用可能なプロパティのリストが表示されます。
. 一番上のチェックボックスをクリックすると、3つのプロパティがすべて選択されます。
. 右側の[追加]ボタンをクリックします。
. ポップアップウィンドウの右上にある[適用]ボタンをクリックします。ポップアップウィンドウが閉じます。


|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
