---
sidebar: sidebar 
permalink: task_dc_na_cdot.html 
keywords: data collector, ontap, ontap, CDOT 
summary: ONTAPデータコレクター 
---
= NetApp ONTAPデータ管理ソフトウェア データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、 ONTAPアカウントからの読み取り専用 API 呼び出しを使用して、 ONTAPを実行しているストレージ システムからインベントリおよびパフォーマンス データを取得します。このデータ コレクターは、サポートを高速化するために、クラスター アプリケーション レジストリにレコードも作成します。



== 用語

Data Infrastructure Insights は、 ONTAPデータ コレクターからインベントリとパフォーマンス データを取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| レイドグループ | ディスクグループ 


| クラスタ | ストレージ 


| ノード | ストレージ ノード 


| Aggregate | ストレージ プール 


| LUN | Volume 


| Volume | 内部容積 
|===


== ONTAPデータ管理用語

次の用語は、 ONTAP Data Management ストレージ アセットのランディング ページに表示されるオブジェクトまたは参照に適用されます。これらの条件の多くは他のデータ収集者にも適用されます。



=== ストレージ

* モデル – このクラスター内の一意の個別のノード モデル名のカンマ区切りリスト。クラスター内のすべてのノードが同じモデル タイプである場合、モデル名が 1 つだけ表示されます。
* ベンダー – 新しいデータ ソースを構成する場合に表示されるのと同じベンダー名。
* シリアル番号 – アレイのシリアル番号。  ONTAP Data Management などのクラスタ アーキテクチャ ストレージ システムでは、このシリアル番号は、個々の「ストレージ ノード」のシリアル番号よりも役に立たない場合があります。
* IP – 通常は、データ ソースで構成されている IP またはホスト名になります。
* マイクロコード バージョン - ファームウェア。
* 生の容量 – 役割に関係なく、システム内のすべての物理ディスクの 2 を底とする合計。
* レイテンシ – 読み取りと書き込みの両方において、ホスト側のワークロードが経験している状況を表します。理想的には、 Data Infrastructure Insightsがこの値を直接取得しますが、多くの場合そうではありません。アレイがこれを提供する代わりに、 Data Infrastructure Insightsは通常、個々の内部ボリュームの統計から導き出された IOPS 加重計算を実行します。
* スループット – 内部ボリュームから集計されます。管理 – これにはデバイスの管理インターフェイスへのハイパーリンクが含まれる場合があります。インベントリレポートの一部として、 Data Infrastructure Insightsデータ ソースによってプログラムによって作成されます。




=== ストレージ プール

* ストレージ – このプールが存在するストレージ アレイ。必須。
* タイプ – 可能性のある列挙リストからの説明的な値。最も一般的なのは「アグリゲート」または「RAID グループ」です。
* ノード – このストレージ アレイのアーキテクチャで、プールが特定のストレージ ノードに属している場合、その名前は独自のランディング ページへのハイパーリンクとしてここに表示されます。
* フラッシュ プールの使用 – はい/いいえの値 – この SATA/SAS ベースのプールには、キャッシュ アクセラレーションに使用される SSD がありますか?
* 冗長性 – RAID レベルまたは保護スキーム。  RAID_DP はデュアル パリティ、RAID_TP はトリプル パリティです。
* 容量 – ここでの値は、論理的に使用されている容量、使用可能な容量、論理的な合計容量、およびこれらの間で使用されている割合です。
* 過剰コミット容量 – 効率化テクノロジを使用して、ストレージ プールの論理容量よりも大きいボリュームまたは内部ボリューム容量の合計を割り当てた場合、ここでのパーセンテージ値は 0% より大きくなります。
* スナップショット – ストレージ プール アーキテクチャが容量の一部をスナップショット専用のセグメント領域に割り当てている場合の、スナップショットの使用済み容量と合計容量。  MetroCluster構成のONTAPではこの問題が発生する可能性が高くなりますが、他のONTAP構成ではこの問題は発生しにくくなります。
* 使用率 – このストレージ プールに容量を提供しているディスクのうち最も高いディスク使用率を示すパーセンテージ値。ディスク使用率は、必ずしもアレイのパフォーマンスと強い相関関係があるわけではありません。ホスト駆動型のワークロードがない場合、ディスクの再構築、重複排除アクティビティなどにより、使用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームまたはボリュームのワークロードとして表示されずにディスク使用率が向上する場合があります。
* IOPS – このストレージ プールに容量を提供しているすべてのディスクの合計 IOPS。スループット – このストレージ プールに容量を提供しているすべてのディスクの合計スループット。




=== ストレージ ノード

* ストレージ – このノードが属するストレージ アレイ。必須。
* HA パートナー - ノードが他の 1 つのノードにのみフェールオーバーするプラットフォームでは、通常ここに表示されます。
* 状態 – ノードの健全性。アレイがデータ ソースによってインベントリされるのに十分正常な場合にのみ使用できます。
* モデル – ノードのモデル名。
* バージョン – デバイスのバージョン名。
* シリアル番号 – ノードのシリアル番号。
* メモリ – 使用可能な場合は 2 進メモリ。
* 使用率 – ONTAPでは、これは独自のアルゴリズムによるコントローラ ストレス インデックスです。すべてのパフォーマンス ポーリングでは、 WAFLディスク競合または平均 CPU 使用率のいずれか大きい方の 0 ～ 100% の数値が報告されます。継続的に 50% を超える値が観測される場合は、サイズ不足を示しています。つまり、書き込みワークロードを吸収するのに十分な大きさのコントローラー/ノードがないか、回転ディスクが足りない可能性があります。
* IOPS – ノード オブジェクト上のONTAP ZAPI 呼び出しから直接導出されます。
* レイテンシ – ノード オブジェクトに対するONTAP ZAPI 呼び出しから直接導出されます。
* スループット – ノード オブジェクトに対するONTAP ZAPI 呼び出しから直接導出されます。
* プロセッサ – CPU 数。




== 要件

このデータ コレクターを構成して使用するための要件は次のとおりです。

* 読み取り専用 API 呼び出し用に設定された管理者アカウントへのアクセス権が必要です。
* アカウントの詳細にはユーザー名とパスワードが含まれます。
* ポート要件: 80 または 443
* アカウント権限:
+
** デフォルトの Vserver への ontapi アプリケーションへの読み取り専用ロール名
** オプションで追加の書き込み権限が必要になる場合があります。以下の権限に関する注意事項を参照してください。


* ONTAPライセンス要件:
+
** ファイバーチャネル検出には FCP ライセンスとマップ/マスクされたボリュームが必要です






=== ONTAPスイッチメトリックの収集に必要な権限

Data Infrastructure Insightsは、コレクターのオプションとしてONTAPクラスタスイッチデータを収集する機能を持っています。<<advanced-configuration,詳細設定>>設定。  Data Infrastructure Insightsコレクターでこれを有効にすることに加えて、 ONTAPシステム自体も*設定*して提供する必要があります。link:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["スイッチ情報"] 、正しいことを確認する<<a-note-about-permissions,権限>>スイッチ データをData Infrastructure Insightsに送信できるようにするために、設定されています。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| NetApp管理 IP | NetAppクラスタのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | NetAppクラスタのユーザー名 


| パスワード | NetAppクラスタのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| 接続の種類 | HTTP (デフォルト ポート 80) または HTTPS (デフォルト ポート 443) を選択します。デフォルトはHTTPSです 


| 通信ポートのオーバーライド | デフォルトを使用しない場合は別のポートを指定します 


| インベントリポーリング間隔（分） | デフォルトは 60 分です。 


| HTTPSのTLSの場合 | HTTPS を使用する場合はプロトコルとして TLS のみを許可する 


| ネットグループを自動的に検索する | エクスポートポリシールールの自動ネットグループ検索を有効にする 


| ネットグループの拡張 | ネットグループの拡大戦略。 _file_ または _shell_ を選択します。デフォルトは _shell_ です。 


| HTTP読み取りタイムアウト秒数 | デフォルトは30です 


| 応答を UTF-8 として強制する | データコレクターコードに、CLIからの応答をUTF-8として解釈するように強制します。 


| パフォーマンスポーリング間隔（秒） | デフォルトは 900 秒です。 


| 高度なカウンターデータ収集 | ONTAP統合を有効にします。ポーリングにONTAPアドバンスド カウンタ データを含めるには、これを選択します。リストから必要なカウンターを選択します。 


| クラスタスイッチメトリック | Data Infrastructure Insights がクラスター スイッチ データを収集できるようにします。 Data Infrastructure Insights側でこれを有効にすることに加えて、 ONTAPシステムも設定する必要があることに注意してください。link:https://docs.netapp.com/us-en/ontap-cli-98/system-switch-ethernet-create.html["スイッチ情報"] 、正しいことを確認する<<a-note-about-permissions,権限>>スイッチ データをData Infrastructure Insightsに送信できるようにするために、設定されています。以下の「権限に関する注意事項」を参照してください。 
|===


== ONTAP電力メトリクス

いくつかのONTAPモデルでは、監視やアラートに使用できるData Infrastructure Insightsの電力メトリックが提供されます。


NOTE: これらのリストは包括的なものではなく、変更される可能性があります。一般に、モデルがリストにあるモデルと同じファミリーに属する場合、サポートは同じになるはずですが、必ずしも同じになるとは限りません。ご使用のモデルが電力メトリックをサポートしているかどうか不明な場合は、 ONTAPサポートにお問い合わせください。

対応モデル:

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

サポートされていないモデル:

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS/ AFF 8020 FAS/ AFF 8040 FAS/ AFF 8060 FAS/ AFF 8080



== 権限に関する注意事項

Data Infrastructure InsightsのONTAPダッシュボードの多くは高度なONTAPカウンターに依存しているため、データ コレクターの詳細設定セクションで *高度なカウンター データ収集* を有効にする必要があります。

また、 ONTAP API への書き込み権限が有効になっていることも確認する必要があります。通常、これには必要な権限を持つクラスター レベルのアカウントが必要です。

クラスタ レベルでData Infrastructure Insightsのローカル アカウントを作成するには、クラスタ管理管理者のユーザー名とパスワードを使用してONTAPにログインし、 ONTAPサーバーで次のコマンドを実行します。

. 開始する前に、_管理者_アカウントでONTAPにサインインし、_診断レベルのコマンド_を有効にする必要があります。
. 次のコマンドを使用して読み取り専用ロールを作成します。
+
....
security login role create -role ci_readonly -cmddirname DEFAULT -access readonly
security login role create -role ci_readonly -cmddirname security -access readonly
security login role create -role ci_readonly -access all -cmddirname {cluster application-record create}
....
. 次のコマンドを使用して読み取り専用ユーザーを作成します。作成コマンドを実行すると、このユーザーのパスワードを入力するよう求められます。
+
 security login create -username ci_user -application ontapi -authentication-method password -role ci_readonly


AD/LDAPアカウントを使用する場合、コマンドは

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application ontapi -authentication-method domain -role ci_readonly
クラスタ スイッチ データを収集する場合:

....
security login rest-role create -role ci_readonly_rest -api /api/network/ethernet -access readonly
security login create -user-or-group-name ci_user -application http -authmethod password -role ci_readonly_rest
....
結果として得られるロールとユーザー ログインは次のようになります。実際の出力は異なる場合があります。

....
Role Command/ Access
Vserver Name Directory Query Level
---------- ------------- --------- ------------------ --------
cluster1 ci_readonly DEFAULT read only
cluster1 ci_readonly security readonly
....
....
cluster1:security login> show
Vserver: cluster1
Authentication Acct
UserName    Application   Method      Role Name      Locked
---------   -------      ----------- -------------- --------
ci_user     ontapi      password    ci_readonly   no
....

NOTE: ONTAPアクセス制御が正しく設定されていない場合、 Data Infrastructure Insights REST 呼び出しが失敗し、デバイスのデータにギャップが生じる可能性があります。たとえば、 Data Infrastructure Insightsコレクターで有効にしたが、 ONTAPで権限を設定していない場合、取得は失敗します。さらに、ロールが以前にONTAPで定義されていて、Rest API 機能を追加する場合は、ロールに _http_ が追加されていることを確認してください。



== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| 401 HTTP 応答または 13003 ZAPI エラー コードを受信し、ZAPI が「権限が不十分です」または「このコマンドは許可されていません」を返します。 | ユーザー名とパスワード、およびユーザー権限/許可を確認します。 


| クラスタバージョンは 8.1 未満です | クラスターの最小サポートバージョンは 8.1 です。サポートされている最小バージョンにアップグレードします。 


| ZAPI は「クラスタ ロールが cluster_mgmt LIF ではありません」を返します | AU はクラスター管理 IP と通信する必要があります。  IPを確認し、必要に応じて別のIPに変更します 


| エラー:「7 モード ファイラーはサポートされていません」 | このデータ コレクターを使用して 7 モード ファイラーを検出すると、この問題が発生する可能性があります。代わりに、IP を変更して cdot クラスターを指すようにします。 


| 再試行後にZAPIコマンドが失敗する | AU はクラスターとの通信に問題があります。ネットワーク、ポート番号、IP アドレスを確認します。ユーザーは、AU マシンのコマンド ラインからコマンドを実行することも試みる必要があります。 


| AUはHTTP経由でZAPIに接続できませんでした | ZAPI ポートがプレーンテキストを受け入れるかどうかを確認します。  AU が SSL ソケットにプレーンテキストを送信しようとすると、通信は失敗します。 


| SSLException により通信が失敗しました | AU は、ファイラー上のプレーンテキスト ポートに SSL を送信しようとしています。  ZAPI ポートが SSL を受け入れるかどうかを確認するか、別のポートを使用します。 


| 追加の接続エラー: ZAPI 応答にエラー コード 13001、「データベースが開いていません」が含まれています。ZAPI エラー コードは 60 で、応答には「API が時間どおりに終了しませんでした」が含まれています。ZAPI 応答には「initialize_session() が NULL 環境を返しました」が含まれています。ZAPI エラー コードは 14007 で、応答には「ノードが正常ではありません」が含まれています。 | ネットワーク、ポート番号、IP アドレスを確認します。ユーザーは、AU マシンのコマンド ラインからコマンドを実行することも試みる必要があります。 
|===


=== パフォーマンス

[cols="2*"]
|===
| 問題： | これを試してください: 


| 「ZAPIからパフォーマンスを収集できませんでした」というエラー | これは通常、 perf stat が実行されていないことが原因です。各ノードで次のコマンドを試してください: > _system node systemshell -node * -command "spmctl -h cmd –stop; spmctl -h cmd –exec"_ 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
