---
sidebar: sidebar 
permalink: task_dc_brocade_rest.html 
keywords: data collector, Brocade, FC switch, FOS, Rest 
summary: Brocade FOS RESTデータコレクタを設定しています。 
---
= Brocade FOS RESTデータコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsでは、Brocade FOS RESTコレクタを使用して、FabricOS（FOS）ファームウェア8.2以降を実行しているBrocadeスイッチデバイスのインベントリとパフォーマンスを検出します。

注意：FOSのデフォルトの「ユーザー」レベルでは、Data Infrastructure Insightsでデバイスのすべての論理的側面を表示するには不十分です。「シャーシロール」が有効になっているユーザーアカウントと、スイッチに設定されているすべての仮想ファブリックに対する権限が必要です。

FOSデバイスへのSSHセッションでData Infrastructure Insightsを使用するための「最小権限」ユーザアカウントを作成する方法の例を次に示します。

userconfig -- add NetAppCIUser -r user -l 1-128 -c user -p QWERTY！

これにより、ユーザ「NetAppCIUser」、パスワード「QWERTY！」が作成されます。このユーザには、128個の可能なすべての仮想ファブリック（-l）で「ユーザ」ロール（-r）が割り当てられます。このユーザには、必要な「シャーシ」ロール（-c）が追加で割り当てられ、ユーザレベルのアクセス権が割り当てられています。

デフォルトでは、このコレクタは、スイッチが属するすべてのファブリックの一部であるすべてのFOSデバイスの検出を試みます。

注意：FOSのデフォルトの読み取り専用ユーザ「user」には、すべての仮想ファブリックに対する表示権限がなく、「chassis role」権限もありません。これは、FOSデバイスの物理構成と論理構成の両方を理解する必要があるData Infrastructure Insightsで「ユーザ」を使用して成功する可能性が低いことを意味します。



== 用語

Data Infrastructure Insightsでは、Brocade FOS RESTデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| スイッチ | スイッチ 


| ポート | ポート 


| 仮想ファブリック、物理ファブリック | ファブリック 


| ゾーン | ゾーン 


| Logical Switch の略 | Logical Switch の略 


| LSANゾーン | IVRゾーン 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* ファブリック内のすべてのスイッチへのTCP接続が確立されている必要があります。このデータコレクタタイプは、ファブリック内の各デバイスに対してHTTPとHTTPSの両方をシームレスに試行します。[Discover all switches in the fabric_]チェックボックスを選択すると、Data Infrastructure Insightsはファブリック内のすべてのスイッチを識別しますが、検出するにはこれらの追加スイッチへのTCP接続が必要です。
* ファブリック内のすべてのスイッチで、同じアカウントがグローバルに必要です。デバイスのWebインターフェイスを使用してアクセスを確認できます。




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| スイッチのIP | FOSスイッチのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | スイッチのユーザ名 


| パスワード | スイッチのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| 除外されたデバイス | ポーリングの対象から除外するデバイスのIPv4アドレスをカンマで区切ったリスト。 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは60です。 


| ファブリック内のすべてのスイッチを検出します | ファブリック内のすべてのスイッチを検出する場合に選択します。 


| HBAとゾーンのエイリアスを優先 | HBAとゾーンエイリアスのどちらを優先するかを選択します。 


| 接続タイプ | HTTPまたはHTTPS。 


| この設定は、デバイスごとに最初に使用するプロトコルCIが変更されるだけであることに注意してください。デフォルトが失敗した場合、CIは自動的に反対のプロトコルを試行します。 | TCP ポートを上書きします 


| デフォルトを使用しない場合は、ポートを指定します。 | パフォーマンスポーリング間隔（秒） 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== インベントリ

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| テスト機能は、プロトコルにアクセスできないことを警告します。 | 特定のBrocade FOS 8.2以降のデバイスは、HTTPまたはHTTPSでのみ通信します。スイッチにデジタル証明書がインストールされている場合、暗号化されていないHTTPとHTTPSで通信しようとすると、スイッチはHTTPエラーをスローします。テスト機能はHTTPとHTTPSの両方との通信を試行します。一方のプロトコルが成功したことをテストで確認した場合、もう一方のプロトコルが失敗したことを心配する必要はありません。コレクタは収集中に両方のプロトコルを試行し、どちらも機能しない場合にのみ失敗します。 


| エラー：「Data Infrastructure Insights Received Invalid Chassis Role」 | このデータソースで設定されているユーザにシャーシのロールの権限が付与されていることを確認します。 


| エラー：「シャーシの IP アドレスが一致しません」 | シャーシの IP アドレスを使用するようにデータソース構成を変更します。 


| 403 Forbiddenでインベントリが失敗する | これは、単に不正な資格情報であるか、十分に強力でないロールを使用しようとしていることを示している可能性があります。「ユーザー」レベルのユーザーには、必要な「シャーシロール」権限がないか、デフォルト以外の仮想ファブリックへのアクセスを表示する権限がないことに注意してください。 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
