---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: ECS データ コレクターを構成します。 
---
= EMC ECS データコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、EMC ECS ストレージ システムからインベントリとパフォーマンス データを取得します。構成には、データ コレクターに ECS クラスターの IP アドレスまたはホスト名とユーザー名およびパスワードが必要です。


NOTE: Dell EMC ECS は、管理対象ユニットとは異なる Raw TB レートで計測されます。フォーマットされていないECS容量40TBごとに1として課金されます。link:concept_subscribing_to_cloud_insights.html#pricing["管理ユニット（MU）"] 。



== 用語

Data Infrastructure Insights は、 ECS データ コレクターから次のインベントリ情報を取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| クラスタ | ストレージ 


| テナント | ストレージ プール 


| バケット | 内部容積 


| ディスク | ディスク 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* ECS クラスタの IP アドレスまたはホスト名
* ECSシステムのユーザー名とパスワード
* ポート 4443 (HTTPS)。  ECS システムの TCP ポート 4443 への送信接続が必要です。




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| ECSホスト | ECS システムの IP アドレスまたは完全修飾ドメイン名 


| ECS ホストポート | ECSホストとの通信に使用するポート 


| ECS ユーザーID | ECSのユーザーID 


| パスワード | ECS で使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは360分です。 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー: ユーザー認証に失敗しました。 | このデバイスの資格情報が正しいことを確認してください。 
|===


=== パフォーマンス

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー: 十分なデータが収集されませんでした。 | * ログファイルの収集タイムスタンプを確認し、それに応じてポーリング間隔を変更します。* より長い時間待機します。 


| エラー: パフォーマンス ポーリング間隔が長すぎます。 | ログファイル ${logfile} の収集タイムスタンプを確認し、それに応じてポーリング間隔を変更します。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
