---
sidebar: sidebar 
permalink: task_dc_na_ontap_rest.html 
keywords: data collector, ontap, ontap, CDOT, REST 
summary: ONTAP RESTデータコレクタ 
---
= NetApp ONTAP RESTデータコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータコレクタは、REST API呼び出しを使用して、ONTAP 9.14.1以降を実行するストレージシステムからインベントリ、EMSログ、パフォーマンスデータを取得します。以前のリリースのONTAPシステムでは、ZAPIベースの「NetApp ONTAPデータ管理ソフトウェア」コレクタタイプを使用します。


NOTE: ONTAP RESTコレクタは、以前のONTAPIベースのコレクタの代わりに使用できます。そのため、収集または報告される指標が異なる場合があります。ONTAPIとRESTの違いの詳細については、のドキュメントを参照してくださいlink:https://docs.netapp.com/us-en/ontap-restmap-9141/index.html["ONTAP 9.14.1 ONTAPI-REST間のマッピング"]。



== 要件

このデータコレクタを設定して使用するための要件は次のとおりです。

* 必要なレベルのアクセス権を持つユーザアカウントへのアクセス権が必要です。新しいRESTユーザ/ロールを作成する場合はAdmin権限が必要です。
+
** 機能的には、Data Infrastructure Insightsは主に読み取り要求を行いますが、Data Infrastructure InsightsをONTAPアレイに登録するには書き込み権限が必要です。下記の「Permissions_immediately」を参照してください。


* ONTAPバージョン9.14.1以降。
* ポートの要件：443




== アクセス権に関する注意事項

データインフラストラクチャインサイトのONTAPダッシュボードの多くは、高度なONTAPカウンタに依存しているため、データコレクタの[高度な設定]セクションで[高度なカウンタデータ収集を有効にする]*を有効にしておく必要があります。

クラスタレベルでData Infrastructure Insights用のローカルアカウントを作成するには、クラスタ管理者のユーザ名とパスワードを使用してONTAPにログインし、ONTAPサーバで次のコマンドを実行します。

. 作業を開始する前に、 _Administrator_account および _diagnostic-level コマンド _ を使用して ONTAP にサインインする必要があります。
. タイプが_admin_のSVMの名前を取得します。この名前は以降のコマンドで使用します。
+
 vserver show -type admin
. 次のコマンドを使用してロールを作成します。
+
....
security login rest-role create -role {role name} -api /api -access readonly
security login rest-role create -role {role name} -api /api/cluster/agents -access all
vserver services web access create -name spi -role {role name} -vserver {vserver name as retrieved above}
security login create -user-or-group-name {username} -application http -authentication-method password -role {role name}
....
. 次のコマンドを使用して、読み取り専用ユーザを作成します。create コマンドを実行すると、このユーザのパスワードを入力するように求められます。
+
 security login create -username ci_user -application http -authentication-method password -role ci_readonly


AD / LDAP アカウントを使用する場合は、コマンドをに設定します

 security login create -user-or-group-name DOMAIN\aduser/adgroup -application http -authentication-method domain -role ci_readonly
作成されるロールとユーザログインは次のようになります。実際の出力は以下のように異なる場合があります

[listing]
----
security login rest-role show -vserver <vserver name> -role restRole

               Role                                    Access
Vserver        Name            API                     Level
----------     -------------   -------------------     ------
<vserver name> restRole        /api                    readonly
                               /api/cluster/agents     all
2 entries were displayed.

security login show -vserver <vserver name> -user-or-group-name restUser

Vserver: <vserver name>
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
restUser       http        password      restRole         no     none
----


== 移行

以前のONTAP（ONTAPI）データコレクタから新しいONTAP RESTコレクタに移行するには、次の手順を実行します。

. RESTコレクタを追加します。以前のコレクタ用に設定されたユーザとは別のユーザの情報を入力することを推奨します。たとえば、上記の「権限」セクションに記載されているユーザを使用します。
. 前のコレクタを一時停止して、データの収集を継続しないようにします。
. 新しいRESTコレクタで少なくとも30分間データを取得します。この期間中に「正常」に表示されないデータはすべて無視してください。
. 残りの期間が経過すると、RESTコレクタがデータを取得し続けるため、データが安定します。


必要に応じて、この同じプロセスを使用して前のコレクタに戻ることができます。



== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| ONTAP管理IPアドレス | NetAppクラスタのIPアドレスまたは完全修飾ドメイン名。クラスタ管理IP / FQDNを指定する必要があります。 


| ONTAP RESTユーザ名 | ネットアップクラスタのユーザ名 


| ONTAP RESTパスワード | ネットアップクラスタのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | デフォルトは60分です。 


| パフォーマンスポーリング間隔（秒） | デフォルトは60秒です。 


| 高度なカウンタデータ収集 | ONTAP 詳細カウンタデータをポーリングに含める場合に選択します。デフォルトは有効です。 


| EMSイベント収集を有効にする | ONTAP EMSログイベントデータを含める場合に選択します。デフォルトは有効です。 


| EMSポーリング間隔（秒） | デフォルトは60秒です。 
|===


== 用語

Data Infrastructure Insightsは、ONTAPデータコレクタからインベントリ、ログ、パフォーマンスデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| RAID グループ | ディスクグループ 


| クラスタ | ストレージ 


| ノード | ストレージノード 


| アグリゲート | ストレージプール 


| LUN | ボリューム 


| ボリューム | 内部ボリューム 


| Storage Virtual Machine / SVM | Storage Virtual Machine 
|===


== ONTAP データ管理の用語

ONTAP データ管理ストレージのアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* model –このクラスタ内で一意のディスクリートノードのモデル名をカンマで区切って指定します。クラスタ内のすべてのノードのモデルタイプが同じ場合、表示されるモデル名は 1 つだけです。
* Vendor –新しいデータソースを設定する場合に表示されるベンダー名と同じです。
* シリアル番号–アレイUUID
* IP –一般に、データソースで設定されている IP またはホスト名です。
* マイクロコードバージョン–ファームウェア。
* raw 容量–システム内のすべての物理ディスクの合計 2 進数で、役割に関係なく加算されます。
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。理想的なのは、Data Infrastructure Insightsがこの価値を直接提供していることですが、そうではないことがよくあります。Data Infrastructure Insightsでは、この機能を提供するアレイの代わりに、個 々 の内部ボリュームの統計に基づいてIOPSの加重計算を実行します。
* スループット–内部ボリュームから集約されたもの。管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。インベントリレポートの一部として、Data Infrastructure Insightsデータソースによってプログラムによって作成されます。




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須。
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「集約」または「 RAID グループ」です。
* ノード：プールが特定のストレージノードに属するようなストレージアレイのアーキテクチャの場合、その名前は、そのストレージアレイのランディングページへのハイパーリンクとして表示されます
* Flash Pool を使用–値はあり / いいえ–この SATA / SAS ベースのプールでは、 SSD をキャッシュ高速化に使用していますか？
* 冗長性– RAID レベルまたは保護方式。raid_dp はデュアルパリティ、 raid_dp はトリプルパリティです。
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。
* オーバーコミット容量–効率化テクノロジを使用して、ストレージプールの論理容量よりも大きいボリュームまたは内部ボリュームの容量の合計を割り当てている場合、この割合は 0% よりも大きくなります。
* スナップショット–スナップショット専用のセグメント領域にストレージプールアーキテクチャが容量の一部を割り当てている場合に使用されるスナップショット容量と合計容量。MetroCluster 構成の ONTAP はこのような構成を示しますが、それ以外の ONTAP 構成はそうではありません。
* 利用率–このストレージプールに容量を追加しているディスクのビジー率の最大値を示した割合。ディスク利用率にアレイのパフォーマンスとの間に大きな相関関係があるとは限りません。ホストベースのワークロードがない場合は、ディスクのリビルドや重複排除処理などが原因で、利用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、内部ボリュームやボリュームのワークロードとしては表示されずにディスク使用率が向上する場合があります。
* IOPS –このストレージプールに容量の要因となっているすべてのディスクの合計 IOPS 。Throughput –このストレージプールの容量の要因となっているすべてのディスクの合計スループット。




=== ストレージノード

* Storage –このノードが属するストレージアレイ。必須。
* HA パートナー–通常、一方のノードだけにフェイルオーバーするプラットフォームでは、この画面が表示されます。
* State –ノードの健常性。アレイが正常な状態でデータソースでインベントリを作成できる場合にのみ使用できます。
* model - ノードのモデル名。
* Version ：デバイスのバージョン名。
* シリアル番号–ノードのシリアル番号。
* メモリ–ベース 2 のメモリがあればそれ。
* 使用率– ONTAP では、これは独自のアルゴリズムのコントローラ応力インデックスです。パフォーマンスポーリングが行われるたびに、 WAFL ディスクの競合率または平均 CPU 利用率の値が 0 ～ 100% の範囲で報告されます。継続的に測定される値が 50% を超えている場合は、サイジングが不十分であることを示します。コントローラやノードのサイズが十分でないか、書き込みワークロードを吸収するのに十分な回転式ディスクが足りない可能性があります。
* IOPS–ノードオブジェクトに対するONTAP REST呼び出しから直接導出されます。
* レイテンシ–ノードオブジェクトに対するONTAP REST呼び出しから直接導出されます。
* スループット–ノードオブジェクトに対するONTAP REST呼び出しから直接導出されます。
* プロセッサ– CPU 数。




== ONTAPの電力メトリック

いくつかのONTAPモデルは、監視やアラートに使用できるデータインフラインサイトの電力指標を提供します。以下のサポートされているモデルとサポートされていないモデルのリストは包括的ではありませんが、いくつかのガイダンスを提供する必要があります。一般的に、モデルがリストのものと同じファミリーに属している場合、サポートは同じである必要があります。

サポートされるモデル：

A200 A220 A250 A300 A320 A400 A700 A700s A800 A900 C190 FAS2240-4 FAS2552 FAS2650 FAS2720 FAS2750 FAS8200 FAS8300 FAS8700 FAS9000

サポートされていないモデル：

FAS2620 FAS3250 FAS3270 FAS500f FAS6280 FAS / AFF 8020 FAS / AFF 8040 FAS / AFF 8060 FAS / AFF 8080



== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| ONTAP RESTデータコレクタを作成しようとすると、次のようなエラーが表示されます。Configuration：10.193.70.14：ONTAP REST API at 10.193.70.14 is not available：10.193.70.14 failed to get /api/cluster：400 Bad Request | これは、古いONTAPアレイ（ONTAP 9.6など）にREST API機能がないことが原因である可能性があります。ONTAP 9.14.1は、ONTAP RESTコレクタでサポートされるONTAPの最小バージョンです。REST ONTAPより前のリリースでは、「400 Bad Request」応答が想定されます。RESTをサポートしているが9.14.1以降ではないバージョンのONTAPでは、次のようなメッセージが表示されることがあります。Configuration: 10.193.98.84：ONTAP REST API at 10.193.98.84 is not available: 10.193.98.84：ONTAP REST API at 10.193.98.84 is available: cheryl5-cluster-2 9.10.1 a3cb3247-3d3c-1120ee-836560050ff3 


| ONTAP ONTAPIコレクタにデータが表示される場合、空または「0」の指標が表示されます。 | ONTAP RESTでは、ONTAPシステムの内部でのみ使用される指標はレポートされません。たとえば、システムアグリゲートはONTAP RESTでは収集されず、タイプが「data」のSVMのみが収集されます。ゼロまたは空のデータを報告する可能性のあるONTAP RESTメトリックの他の例: InternalVolumes : RESTはvol0を報告しなくなりました。Aggregates：RESTでaggr0が報告されなくなりました。ストレージ：ほとんどの指標は内部ボリュームの指標を集計したもので、上記の影響を受けます。Storage Virtual Machine：RESTでは、「data」以外のタイプのSVM（「cluster」、「mgmt」、「node」など）は報告されなくなりました。また、デフォルトのパフォーマンスポーリング期間が15分から5分に変更されたため、データを含むグラフの表示が変更されることもあります。ポーリングの頻度が高いほど、プロットするデータポイントが増えます。 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
