---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: NetApp ONTAP Data Collector 向けの Amazon FSX 
---
= NetApp ONTAP データコレクタ用の Amazon FSX
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
このデータコレクタは、 Amazon FSX for NetApp ONTAP からインベントリデータとパフォーマンスデータを取得します。このデータコレクタは、Data Infrastructure Insightsサービスのリージョン全体で段階的に利用できるようになります。Data Infrastructure Insights環境にこのコレクタのアイコンが表示されない場合は、営業担当者にお問い合わせください。


NOTE: このData Infrastructure Insightsコレクタには、_Filesystem-Scoped_roleを持つONTAPユーザが必要です。link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["ロールとルール"]使用可能なオプションについては、AWSのドキュメントを参照してください。現時点では、AWSはFilesystem Scopeを使用するユーザロールの1種類（_fsxadmin_）のみをサポートしています。これは、Data Infrastructure Insightsコレクタに使用する適切なロールです。また、ユーザには、http、ontapi、sshの3つのアプリケーションすべてが割り当てられている必要があります。



== 用語

Data Infrastructure Insightsは、FSx - NetAppデータコレクタからインベントリとパフォーマンスのデータを取得します。取得したアセットのタイプごとに、そのアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| クラスタ | ストレージ 


| LUN | ボリューム 


| ボリューム | 内部ボリューム 
|===


== FSX - ネットアップの用語

FSx-NetApp ストレージアセットランディングページにあるオブジェクトや参考資料に関連する用語を次に示します。これらの用語の多くは、他のデータコレクタにも適用されます。



=== ストレージ

* model –このクラスタ内で一意のディスクリートモデル名をカンマで区切って指定します。
* ベンダー–AWS
* Serial Number –アレイのシリアル番号。
* IP –一般に、データソースで設定されている IP またはホスト名です。
* 物理容量–FSXファイルシステムに割り当てられているすべてのSSDストレージの2つの合計。
* レイテンシ–読み取りと書き込みの両方について、ワークロードが直面しているホストの状況が表示されます。理想的なのは、Data Infrastructure Insightsがこの価値を直接提供していることですが、そうではないことがよくあります。Data Infrastructure Insightsでは、この機能を提供するアレイの代わりに、個 々 の内部ボリュームの統計に基づいてIOPSの加重計算を実行します。
* スループット–内部ボリュームから集約されたもの。管理–デバイスの管理インターフェイスのハイパーリンクが含まれている可能性があります。インベントリレポートの一部として、Data Infrastructure Insightsデータソースによってプログラムによって作成されます。




=== ストレージプール

* storage –このプールのストレージアレイの場所。必須。
* Type –可能性のリストから説明的な値を入力します。最も一般的な構成は、「集約」または「 RAID グループ」です。
* 容量–使用済みの論理容量、使用可能な容量、および合計論理容量の値と、これらの要素で使用されている割合の値が表示されます。
* IOPS–このストレージプールに割り当てられているすべてのボリュームの合計IOPS。
* Throughput–このストレージプールに割り当てられているすべてのボリュームの合計スループット。




== 要件

このデータコレクタを設定して使用するための要件は次のとおりです。

* 「fsxadmin」ロールのアカウントにアクセスできる必要があります。このアカウントには、ssh、ontapi、httpの3つのアプリケーションが割り当てられています。
* アカウントの詳細には、ユーザ名とパスワードが含まれます。
* ポートの要件：443




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| ネットアップ管理 IP | NetAppクラスタのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | ネットアップクラスタのユーザ名 


| パスワード | ネットアップクラスタのパスワード 
|===


== Advanced Metricsの2つのパラメータ

このデータコレクタは、NetApp ONTAP ストレージのFSXから次の高度な指標を収集します。

* FPolicy
* NFSv3
* NFSv3：ノード
* NFSv4
* nfsv4_1
* nfsv4_1：ノード
* NFSv4：ノード
* policy_groupを開きます
* qtree
* ボリューム
* Workload _volume


FSx CLIコマンドとAPIコマンドは、Data Infrastructure Insights ZAPIで収集されない一部の容量値を取得するため、Data Infrastructure Insightsでは特定の容量値（ストレージプールの値など）がFSx自体と異なる場合があることに注意してください。



== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== インベントリ

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| 401 HTTP 応答または 13003 ZAPI エラーコードを受信し、 ZAPI から「 Insufficient privileges 」または「 Not authorized for this command 」が返される | ユーザ名とパスワード、およびユーザの権限と権限を確認してください。 


| ZAPI から「 cluster role is not cluster_mgmt LIF 」が返される | AU はクラスタ管理 IP と通信する必要があります。IP を確認し、必要に応じて別の IP に変更してください 


| ZAPI コマンドの再試行後に失敗する | AU でクラスタとの通信に問題があります。ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 


| AU が HTTP 経由で ZAPI に接続できませんでした | ZAPI ポートでプレーンテキストが受け入れるかどうかを確認します。AU が SSL ソケットにプレーンテキストを送信しようとすると、通信に失敗します。 


| SSLException で通信が失敗します | AU が Filer 上のプレーンテキストポートに SSL を送信しようとしています。ZAPI ポートで SSL を受け入れるか、別のポートを使用するかを確認します。 


| その他の接続エラー： ZAPI 応答にはエラーコード 13001 、「 database is not open 」 ZAPI エラーコード 60 があり、応答に「 API did not finished on time 」という応答が含まれています。 ZAPI エラーコード 14007 では「 initialize_session() returned NULL environment 」が返され、応答に「 Node is not healthy 」が含まれます。 | ネットワーク、ポート番号、および IP アドレスを確認してください。また、 AU マシンのコマンドラインからもコマンドを実行しようとします。 
|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
