---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: DELL EMC PowerStore データ コレクターを構成します。 
---
= Dell EMC PowerStoreデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC PowerStore データ コレクターは、EMC PowerStore ストレージからインベントリ情報を収集します。構成の場合、データ コレクターには、ストレージ プロセッサの IP アドレスと読み取り専用のユーザー名とパスワードが必要です。

EMC PowerStore データ コレクターは、PowerStore が他のストレージ アレイ間で調整するボリューム間のレプリケーション関係を収集します。 Data Infrastructure Insights は、各 PowerStore クラスターのストレージ アレイを表示し、そのクラスター上のノードとストレージ ポートのインベントリ データを収集します。ストレージ プールまたはボリューム データは収集されません。



== 用語

Data Infrastructure Insights は、このデータ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ホスト | ホスト 


| ホストボリュームマッピング | ホストボリュームマッピング 


| ハードウェア（「extra_details」オブジェクトの下にドライブがあります）: ドライブ | ディスク 


| アプライアンス | ストレージプール 


| クラスタ | ストレージ アレイ 


| ノード | ストレージノード 


| fc_ポート | ポート 


| 音量 | Volume 


| 内部ボリューム | ファイルシステム 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次の情報が必要です。

* ストレージプロセッサのIPアドレスまたは完全修飾ドメイン名
* 読み取り専用のユーザー名とパスワード




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| PowerStoreゲートウェイ | PowerStoreストレージのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | PowerStoreのユーザー名 


| パスワード | PowerStoreで使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| HTTPSポート | デフォルトは443です 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 
|===
Cloud Insight の PowerStore パフォーマンス収集では、PowerStore の 5 分単位のソース データが使用されます。そのため、 Data Infrastructure Insights は5 分ごとにそのデータをポーリングしますが、これは構成できません。



== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
