---
sidebar: sidebar 
permalink: task_dc_na_eseries.html 
keywords: data collector, ontap, clustered ontap, e-series, santricity 
summary: NetApp E シリーズ データ コレクターを構成します。 
---
= NetApp Eシリーズ レガシー Santricity API データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetApp E シリーズ レガシー Santricity API データ コレクターは、インベントリとパフォーマンス データを収集します。コレクターは、同じ構成を使用して同じデータを報告するファームウェア 7.x+ をサポートします。



== 用語

Cloud Insights は、 NetApp E シリーズ データ コレクターから次のインベントリ情報を取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| ボリューム グループ | ディスクグループ 


| ストレージ アレイ | ストレージ 


| コントローラ | ストレージ ノード 


| ボリューム グループ | ストレージ プール 


| Volume | Volume 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== Eシリーズ用語集（ランディングページ）

次の用語は、 NetApp E シリーズ アセット ランディング ページに表示されるオブジェクトまたは参照に適用されます。これらの条件の多くは、他のデータ収集者にも適用されます。



=== ストレージ

* モデル – デバイスのモデル名。
* ベンダー – 新しいデータソースを構成する場合に表示されるのと同じベンダー名
* シリアル番号 – アレイのシリアル番号。  NetApp Clustered Data Ontapのようなクラスタアーキテクチャストレージシステムでは、このシリアル番号は個々の「ストレージノード」のシリアル番号ほど役に立たない場合があります。
* IP – 通常はデータソースで設定されたIPまたはホスト名になります
* マイクロコードバージョン – ファームウェア
* 生の容量 – システム内のすべての物理ディスクの2を底とする合計（役割に関係なく）
* レイテンシ – 読み取りと書き込みの両方において、ホスト側のワークロードが経験している状況を表します。理想的には、 Data Infrastructure Insightsがこの値を直接取得しますが、多くの場合そうではありません。アレイがこれを提供する代わりに、 Data Infrastructure Insights は通常、個々のボリュームの統計から導き出された IOPS 加重計算を実行します。
* スループット – アレイのホスト側スループットの合計。理想的にはアレイから直接取得されますが、利用できない場合は、Data Infrastructure Insightsがボリュームのスループットを合計してこの値を導き出します。
* 管理 – これにはデバイスの管理インターフェイスへのハイパーリンクが含まれる場合があります。在庫レポートの一部として、Data Infrastructure Insightsサイト データソースによってプログラム的に作成されます。  




=== ストレージ プール

* ストレージ – このプールが存在するストレージ アレイ。必須
* タイプ – 可能性のある列挙リストからの説明的な値。最も一般的なのは「シンプロビジョニング」または「RAIDグループ」です。
* ノード – このストレージアレイのアーキテクチャで、プールが特定のストレージノードに属している場合、その名前は独自のランディングページへのハイパーリンクとしてここに表示されます。
* フラッシュプールを使用する – はい/いいえの値
* 冗長性 – RAID レベルまたは保護スキーム。  EシリーズはDDPプールに対して「RAID 7」を報告します
* 容量 – ここでの値は、論理的に使用されている容量、使用可能な容量、論理的な合計容量、およびこれらの間で使用されている割合です。これらの値にはEシリーズの「保存」容量が含まれており、数値とパーセンテージはEシリーズのユーザーインターフェースに表示されるものよりも高くなります。
* 過剰コミット容量 – 効率化テクノロジを使用して、ストレージ プールの論理容量よりも大きいボリュームまたは内部ボリューム容量の合計を割り当てた場合、ここでのパーセンテージ値は 0% より大きくなります。
* スナップショット – ストレージプールアーキテクチャがスナップショット専用のセグメント領域に容量の一部を割り当てている場合、使用されているスナップショット容量と合計容量
* 使用率 – このストレージ プールに容量を提供しているディスクのうち最も高いディスク使用率を示すパーセンテージ値。ディスク使用率は、必ずしもアレイのパフォーマンスと強い相関関係があるわけではありません。ホスト駆動型のワークロードがない場合、ディスクの再構築、重複排除アクティビティなどにより、使用率が高くなる可能性があります。また、多くのアレイのレプリケーション実装では、ボリュームのワークロードとして表示されずにディスク使用率が向上する場合があります。
* IOPS – このストレージ プールに容量を提供しているすべてのディスクの合計 IOPS。特定のプラットフォームでディスクIOPSが利用できない場合、この値は、このストレージプールにあるすべてのボリュームのボリュームIOPSの合計から取得されます。
* スループット – このストレージ プールに容量を提供しているすべてのディスクの合計スループット。特定のプラットフォームでディスクスループットが利用できない場合、この値は、このストレージプールにあるすべてのボリュームのボリュームスループットの合計から取得されます。




=== ストレージ ノード

* ストレージ – このノードが属するストレージ アレイ。必須
* HAパートナー – ノードが他の1つのノードにのみフェイルオーバーするプラットフォームでは、通常ここに表示されます。
* 状態 – ノードの健全性。アレイがデータソースによってインベントリされるのに十分健全な場合にのみ使用可能
* モデル – ノードのモデル名
* バージョン – デバイスのバージョン名。
* シリアル番号 – ノードのシリアル番号
* メモリ – 利用可能な場合は2進メモリ
* 使用率 – 通常は CPU 使用率の数値ですが、 NetApp Ontap の場合はコントローラのストレス インデックスです。  NetApp Eシリーズでは現在利用できません
* IOPS – このコントローラー上のホスト駆動 IOPS を表す数値。理想的にはアレイから直接取得されますが、利用できない場合は、このノードに排他的に属するボリュームのすべての IOP を合計することによって計算されます。
* レイテンシ – このコントローラー上の典型的なホストレイテンシまたは応答時間を表す数値。理想的にはアレイから直接取得されますが、利用できない場合は、このノードに排他的に属するボリュームから IOPS 加重計算を実行して計算されます。
* スループット – このコントローラー上のホスト駆動スループットを表す数値。理想的にはアレイから直接取得されますが、利用できない場合は、このノードに排他的に属するボリュームのすべてのスループットを合計することによって計算されます。
* プロセッサ – CPU数




== 要件

* アレイ上の各コントローラのIPアドレス
* ポート要件 2463




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| アレイSANtricityコントローラIPのコンマ区切りリスト | アレイコントローラのIPアドレスおよび/または完全修飾ドメイン名 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは30分です 


| パフォーマンスポーリング間隔は最大3600秒 | デフォルトは300秒です 
|===


== トラブルシューティング

このデータ収集装置に関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
