---
sidebar: sidebar 
permalink: task_business_entity_annotations.html 
keywords: annotations, business entity 
summary: ビジネスエンティティ注釈は、ビジネス階層内の資産の監視とレポートに使用できます。 
---
= ビジネスエンティティ注釈
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
*ビジネス エンティティ* 注釈タイプを使用して、企業環境のビジネス エンティティを作成および管理します。



== ビジネスエンティティの作成

ビジネス エンティティを作成するには、次の手順を実行します。

. *管理 > 注釈* をクリックし、_ビジネス エンティティ_ リンクをクリックします。
+
現在定義されているビジネス エンティティのリストが表示されます。

. *+ ビジネスエンティティ*をクリックします。
. *テナント*、*事業部門*、*事業単位*、および*プロジェクト*フィールドに値を入力します。
+
ビジネス エンティティに適用されないフィールドは空白のままにしておくことができます。

. 以前にフィールドに値を入力している場合は、ドロップダウンからその値を選択できます。再度入力する必要はありません。



NOTE: 選択した値は、一意の合計ビジネス エンティティを構成する必要があります。たとえば、値が _A / B / C / D_ の順序で設定されているビジネス エンティティがすでに存在する場合、その順序で値を持つ別のビジネス エンティティを作成することはできません。ただし、これらの値を異なる順序で使用してビジネス エンティティを作成することもできます。



== オブジェクトへのビジネスエンティティの適用

ビジネス エンティティをオブジェクトに適用する最も簡単な方法は、クエリを使用することです。

. *クエリ > +新しいクエリ* をクリックし、目的のオブジェクト タイプを選択します。フィルターを適用して結果をさらに絞り込むことができます。
. チェックボックスをクリックして、ビジネス エンティティを適用するオブジェクトを選択します。
. *一括操作*をクリックし、*注釈の追加*を選択します。
. _ビジネス エンティティ_ アノテーションを選択し、リストから目的のビジネス エンティティ値を選択します。
. *保存* をクリックして、ビジネス エンティティをオブジェクトに適用します。


オブジェクトのアセット ランディング ページに移動し、[ユーザー データ] セクションの *+ 注釈) をクリックすることで、個々のオブジェクトにビジネス エンティティを適用することもできます。

また、link:task_create_annotation_rules.html["注釈ルール"]ビジネス エンティティをオブジェクトに適用します。


NOTE: オブジェクトには、関連付けられるビジネス エンティティを 1 つだけ持つことができます。



== オブジェクトからビジネスエンティティを削除する

オブジェクトからビジネス エンティティを削除するには、オブジェクトをクエリして選択し、[*一括アクション*] をクリックして、[_注釈の削除_] を選択します。ビジネス エンティティ注釈を選択し、[削除] をクリックします。
