---
sidebar: sidebar 
permalink: task_dc_huawei_oceanstor.html 
keywords: data collector, Huawei, OceanStor, Dorado 
summary: 'Huawei OceanStor (REST/HTTPS) データ コレクターを構成します。' 
---
= Huawei OceanStorデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Huawei OceanStor (REST/HTTPS) データ コレクターを使用して、Huawei OceanStor および OceanStor Dorado ストレージのインベントリとパフォーマンスを検出します。



== 用語

Data Infrastructure Insights は、 Huawei OceanStor から次のインベントリとパフォーマンス情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ プール | ストレージ プール 


| ファイルシステム | 内部容積 


| コントローラ | ストレージ ノード 


| FC ポート (マッピング済み) | ボリュームマップ 


| ホスト FC イニシエーター (マッピング済み) | ボリュームマスク 


| NFS/CIFS共有 | 共有 


| iSCSI リンク ターゲット | iSCSIターゲットノード 


| iSCSI リンク イニシエーター | iSCSI イニシエーターノード 


| ディスク | ディスク 


| LUN | Volume 
|===


== 要件

このデータ コレクターを構成するには、次の要件が必要です。

* デバイスのIPアドレス
* OceanStorデバイスマネージャーにアクセスするための資格情報
* ポート8088が利用可能である必要があります




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| OceanStorホストIPアドレス | OceanStorデバイスマネージャのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | OceanStorデバイスマネージャにログインするために使用する名前 


| パスワード | OceanStorデバイスマネージャにログインするために使用するパスワード 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 説明 


| TCPポート | OceanStor デバイス マネージャーに接続するために使用される TCP ポート。デフォルトは 8088 です。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 


| パフォーマンス ポーリング間隔 (秒)。 | デフォルトは300秒です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
