---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: アノテーションルールを作成して、複数のアセットにアノテーションを自動的に適用します。 
keywords: annotate, annotation, rules 
---
= アノテーションルールの作成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
アノテーションルールを使用すると、定義した条件に基づいて複数のアセットにアノテーションを自動的に適用できます。Data Infrastructure Insightsは、これらのルールに基づいてアセットにアノテーションを割り当てます。個々のアセットページで手動で設定したアノテーションは、 Cloud Insight でアノテーションルールが評価されるときにルールベースのアノテーションよりも優先されます。

.開始する前に
アノテーションルールのクエリを作成しておく必要があります。

.手順
. [Data Infrastructure Insights ]メニューで、*[管理]>[アノテーションルール]*をクリックします。
. 新しいアノテーションルールを追加するには、「 * + ルール * 」をクリックします。
+
[Add Rule] ダイアログが表示されます。

. 次の手順を実行します。
+
.. [* 名前 *] ボックスに、ルールを説明する一意の名前を入力します。
+
名前がアノテーションルールページに表示されます。

.. [Query]*をクリックし、Data Infrastructure Insightsがアノテーションを適用するアセットを特定するために使用するクエリを選択します。
.. [* Annotation* ] をクリックし、適用する注釈を選択します。
.. * 値 * をクリックし、アノテーションの値を選択します。
+
たとえば、 Birthday のアノテーションを選択した場合は、日付の値を指定します。

.. [ 保存（ Save ） ] をクリックします。
.. すべてのルールをすぐに実行する場合は、 * すべてのルールを実行 * をクリックします。それ以外の場合、ルールは定期的に実行されます。
+

NOTE: 大規模なData Infrastructure Insights環境で、アノテーションルールの実行に時間がかかることがあります。これは、インデクサが最初に実行され、ルールを実行する前に完了する必要があるためです。インデクサは、データ内の新規または更新されたオブジェクトやカウンタを検索またはフィルタリングする機能をData Infrastructure Insightsに提供します。ルールエンジンは、インデクサが更新を完了するまで待機してから、ルールを適用します。







== アノテーションルールの変更

アノテーションルールについて、ルールの名前、そのアノテーション、アノテーションの値、ルールに関連付けられているクエリを変更することができます。

.手順
. [Data Infrastructure Insights ]メニューで、*[管理]>[アノテーションルール]*をクリックします。
+
アノテーションルールページに、既存のアノテーションルールのリストが表示されます。

. 変更するアノテーションルールを選択します。
+
アノテーションルールは、フィルタボックスに値を入力してフィルタすることも、ページ番号をクリックして各ページで参照することもできます。

. 変更するルールのメニューアイコンをクリックします。
. [ 編集（ Edit ） ] をクリックします。
+
Edit Rule ダイアログが表示されます。

. アノテーションルールの名前、アノテーション、値、またはクエリを変更します。




== ルールの順序を変更する

アノテーションルールは、ルールリストの一番上から一番下まで処理されます。ルールの処理順序を変更するには、次の手順を実行します。

.手順
. 移動するルールのメニューアイコンをクリックします。
. 目的の場所にルールが表示されるまで、必要に応じて [ 上へ移動 ] または [ 下へ移動 ] をクリックします。


アセット上で同じアノテーションを更新する複数のルールを実行している場合は、最初のルール（上から下に実行）によってアノテーションが適用され、アセットが更新されます。2番目のルールは適用されますが、前のルールですでに設定されているアノテーションは変更されません。



== アノテーションルールの削除

使用されなくなったアノテーションルールを削除できます。

.手順
. [Data Infrastructure Insights ]メニューで、*[管理]>[アノテーションルール]*をクリックします。
+
アノテーションルールページに、既存のアノテーションルールのリストが表示されます。

. 削除するアノテーションルールを選択します。
+
アノテーションルールは、フィルタボックスに値を入力してフィルタすることも、ページ番号をクリックして各ページで参照することもできます。

. 削除するルールのメニューアイコンをクリックします。
. [ 削除（ Delete ） ] をクリックします。
+
ルールを削除するかどうかを確認するメッセージが表示されます。

. [OK] をクリックします。

