---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet,  cloud secure 
summary: Workload Security はデータ コレクターを使用して、デバイスからファイルおよびユーザー アクセス データを収集します。 
---
= Cloud Volumes ONTAPとAmazon FSx for NetApp ONTAPコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security はデータ コレクターを使用して、デバイスからファイルおよびユーザー アクセス データを収集します。



== Cloud Volumes ONTAPストレージ構成

Workload Security Agent をホストするための単一ノード/HA AWS インスタンスを構成するには、 OnCommand Cloud Volumes ONTAPドキュメントを参照してください。https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html[]

設定が完了したら、次の手順に従って SVM をセットアップします。https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== サポート対象プラットフォーム

* Cloud Volumes ONTAP は、利用可能なすべてのクラウド サービス プロバイダーでサポートされています。例: Amazon、Azure、Google Cloud。
* ONTAP Amazon FSx




== エージェントマシン構成

エージェント マシンは、クラウド サービス プロバイダーのそれぞれのサブネット内に構成する必要があります。ネットワーク アクセスの詳細については、[エージェントの要件] を参照してください。

以下は AWS でのエージェントのインストール手順です。インストールには、クラウド サービス プロバイダーに応じて、Azure または Google Cloud で同等の手順に従うことができます。

AWS では、次の手順に従って、マシンを Workload Security エージェントとして使用するように設定します。

Workload Security Agent として使用するマシンを設定するには、次の手順に従います。

.手順
. AWS コンソールにログインし、EC2 インスタンス ページに移動して、[インスタンスの起動] を選択します。
. このページに記載されている適切なバージョンの RHEL または CentOS AMI を選択します。https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Cloud ONTAPインスタンスが存在する VPC とサブネットを選択します。
. 割り当てリソースとして _t2.xlarge_ (4 個の vCPU と 16 GB の RAM) を選択します。
+
.. EC2 インスタンスを作成します。


. YUM パッケージ マネージャーを使用して必要な Linux パッケージをインストールします。
+
.. ネイティブ Linux パッケージ _wget_ および _unzip_ をインストールします。






== ワークロードセキュリティエージェントをインストールする

. Data Infrastructure Insights環境に管理者またはアカウント所有者としてログインします。
. Workload Security *Collectors* に移動し、*Agents* タブをクリックします。
. *+エージェント*をクリックし、ターゲット プラットフォームとして RHEL を指定します。
. エージェント インストール コマンドをコピーします。
. ログインしている RHEL EC2 インスタンスにエージェント インストール コマンドを貼り付けます。これにより、Workload Securityエージェントがインストールされ、link:concept_cs_agent_requirements.html["エージェントの前提条件"]満たされます。


詳細な手順については、このリンクを参照してください：https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent



== トラブルシューティング

既知の問題とその解決策を次の表に示します。

|===


| 問題 | 解決策 


| データコレクターによって「Workload Security: Amazon FxSN データコレクターのONTAPタイプを判別できませんでした」というエラーが表示されます。お客様は、新しい Amazon FSxN データコレクターを Workload Security に追加できません。エージェントからポート 443 上の FSxN クラスターへの接続がタイムアウトしています。ファイアウォールと AWS セキュリティグループには、通信を許可するために必要なルールが有効になっています。エージェントはすでにデプロイされており、同じ AWS アカウントに存在します。この同じエージェントは、残りのNetAppデバイス (すべて動作中) への接続と監視にも使用されます。 | この問題を解決するには、fsxadmin LIF ネットワーク セグメントをエージェントのセキュリティ ルールに追加します。ポートが不明な場合は、すべてのポートを許可します。 
|===