---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Nutanix のデータコレクタの設定 
---
= Nutanix NX データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsは、Nutanixデータコレクタを使用して、Nutanix NXストレージシステムのインベントリデータとパフォーマンスデータを検出します。



== 用語

Data Infrastructure Insightsは、Nutanixデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ストレージプール | ストレージプール 


| Nutanix コンテナ | 内部ボリューム 


| Nutanix コンテナ | ファイル共有 


| NFS共有 | 共有 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



== 要件

* クラスタの外部データサービスの IP アドレス
* volume_groups が使用されていないかぎり、読み取り専用のユーザ名とパスワード。この場合は、 Admin ユーザ名とパスワードが必要です
* ポート要件： HTTPS 443




== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| プリズム外部 IP アドレス | クラスタの外部データサービスの IP アドレス 


| ユーザ名 | 管理者アカウントのユーザ名 


| パスワード | 管理者アカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| TCP ポート | Nutanix アレイへの接続に使用する TCP ポート。デフォルトは9440です。 


| インベントリのポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは60分です。 


| パフォーマンスのポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは300秒です。 
|===


== トラブルシューティング

このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
