---
sidebar: sidebar 
permalink: task_create_application.html 
summary: アプリケーションを定義し、必要に応じてテナントのアセットに適用します。 
keywords: application, create application, 
---
= アプリケーションの作成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
テナントで実行されている特定のアプリケーションに関連するデータを追跡するには、Data Infrastructure Insightsでアプリケーションを定義します。

.タスクの内容
Data Infrastructure Insightsを使用すると、アプリケーションに関連付けられたアセットのデータを追跡し、使用状況やコストレポートなどを作成できます。

.手順
. [Data Infrastructure Insights ]メニューで、*[Observability]>[Enrich]>[Applications]*をクリックします。選択
+
[アプリケーションの追加]ダイアログボックスが表示されます。

. アプリケーションの一意の名前を入力します。
. アプリケーションの優先度を選択します。
. [ 保存（ Save ） ] をクリックします。


アプリケーションを定義したら、アセットに割り当てることができます。



== アセットへのアプリケーションの割り当て

この手順では、例としてアプリケーションをホストに割り当てます。アプリケーションには、ホスト、仮想マシン、ボリューム、または内部ボリュームを割り当てることができます。

.手順
. アプリケーションに割り当てるアセットを選択します。
. [* クエリ ] 、 [ 新しいクエリ ] の順にクリックし、 [ ホスト ] を検索します。
. アプリケーションに関連付けるホストの左側にあるチェックボックスをオンにします。
. [ 一括操作 ]>[ アプリケーションの追加 *] をクリックします。
. アセットを割り当てるアプリケーションを選択します。


新しく割り当てたアプリケーションは、別のアセットから派生したアプリケーションよりも優先されます。たとえば、ホストから継承したアプリケーションがあるボリュームに新しいアプリケーションを割り当てた場合、派生したアプリケーションよりも新しいアプリケーションが優先されます。


NOTE: 関連するアセットが大量にある環境では、それらのアセットへのアプリケーションの割り当ての継承に数分かかることがあります。関連するアセットが多数ある場合は、継承の時間を長くしてください。

.終了後
アプリケーションにホストを割り当てたら、残りのアセットをアプリケーションに割り当てることができます。アプリケーションのランディング・ページにアクセスするには、 * Manage > Application * をクリックして、作成したアプリケーションを選択します。
