---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: IBM Cleversafe データ コレクターを構成します。 
---
= IBM Cleversafe データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、このデータ コレクターを使用して、IBM Cleversafe ストレージ システムのインベントリとパフォーマンス データを検出します。


NOTE: IBM Cleversafe は、管理対象ユニットに対して異なる Raw TB レートで計測されます。フォーマットされていないIBM Cleversafeの容量40TBごとに1として課金されます。link:concept_subscribing_to_cloud_insights.html#pricing["管理ユニット（MU）"] 。



== 用語

Data Infrastructure Insights は、 IBM Cleversafe データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ プール | ストレージ プール 


| Container | 内部容積 


| Container | ファイル共有 


| NFS 共有 | 共有 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* クラスタの外部データサービスIPアドレス
* 管理者のユーザ名とパスワード
* ポート9440




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| マネージャーのIPまたはホスト名 | 管理ノードのIPアドレスまたはホスト名 


| ユーザ名 | スーパーユーザーまたはシステム管理者の役割を持つユーザーアカウントのユーザー名 


| パスワード | スーパーユーザーまたはシステム管理者の役割を持つユーザーアカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。 


| HTTP接続タイムアウト（秒） | HTTP タイムアウト（秒単位）。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
