---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: DELL EMC Celerra データ コレクターを構成します。 
---
= DELL EMC VNX File（旧Celerra Unified Storage System）データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、VNX ファイル ストレージ システムからインベントリ情報を取得します。このデータ コレクターを構成するには、ストレージ プロセッサの IP アドレスと読み取り専用のユーザー名とパスワードが必要です。



== 用語

Data Infrastructure Insights は、 VNX ファイル データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| Celerra ネットワーク サーバ/Celerra ストレージ プール | ストレージ プール 


| ファイルシステム | 内部容積 


| データムーバー | コントローラ 


| データムーバーにマウントされたファイルシステム | ファイル共有 


| CIFSおよびNFSエクスポート | 共有 


| ディスクボリューム | バックエンドLUN 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次のものが必要です。

* ストレージプロセッサのIPアドレス
* 読み取り専用のユーザー名とパスワード
* SSH、ポート22




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| VNXファイルのIPアドレス | VNX ファイル デバイスの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNXファイルデバイスにログインするために使用する名前 


| パスワード | VNXファイルデバイスにログインするために使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは20分です。 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー: DART の更新中は続行できません | 考えられる解決策: データ コレクターを一時停止し、DART アップグレードが完了するまで待ってから、別の取得要求を試行します。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
