---
sidebar: sidebar 
permalink: task_dc_emc_vnx_block.html 
keywords: data collector, EMC, clariion, VNX block 
summary: Dell EMC VNX Block Storage の設定（旧 CLARiX ） 
---
= Dell EMC VNX Block Storage （ NaviCLI ）データコレクタ
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insightsは、Dell EMC VNX Block Storage（NaviSec）データコレクタ（旧CLARiX）を使用してインベントリデータとパフォーマンスデータを取得します。



== 用語

Data Infrastructure Insightsは、EMC VNX Block Storageデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ディスク | ディスク 


| ストレージ | ストレージ 


| ストレージプロセッサ | ストレージノード 


| このプール 'RAID グループ | ストレージプール 


| LUN | ボリューム 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータソースのすべてのケースを表しているとは限りません。



== 要件

データを収集するには、次の要件を満たしている必要があります。

* 各 VNX ブロックストレージプロセッサの IP アドレス
* VNX ブロックストレージアレイに対する読み取り専用の Navisphere ユーザー名とパスワード
* NaviseccliがData Infrastructure Insights AUにインストールされていること
* アクセスの検証：ユーザー名とパスワードを使用して、Data Infrastructure Insights AUから各アレイに対してnaviseccliを実行します。
* ポート要件： 80 、 443
* naviseccli のバージョンは ' アレイ上の最新の FLARE コードに対応している必要があります
* パフォーマンスを収集するには、統計のログを有効にする必要があります。




== Navisphere コマンドラインインタフェースの構文

NaviSECCLI.exe -h <ip address> -user <user> -password <password> -scope <scope 、 use 0 for global scope> -port <use 443 by default> コマンド



== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| VNX Block Storage の IP アドレス | VNX ブロックストレージの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNX ブロックストレージデバイスへのログインに使用する名前。 


| パスワード | VNX ブロックストレージデバイスへのログインに使用するパスワード。 


| CLI から naviseccli.exe へのパス | _naviseccli.exe_executable を含むフォルダへの完全パス 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは40分です。 


| 適用範囲 | セキュアなクライアントの範囲デフォルトは Global です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは300秒です。 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。



=== インベントリ

[cols="2a, 2a"]
|===
| 問題 | 次の操作を実行します 


 a| 
エラー：

* エージェントが実行されてい
* naviseccliが見つかりませんでした
* コマンドを実行できませんでした

 a| 
* Navisphere CLIがCloud Insight Acquisition Unitにインストールされていることを確認する
* データコレクタ設定ウィザードで[Use secure client]オプションが選択されておらず、セキュアでないバージョンのNavisphere CLIがインストールされていません。
* データコレクタ構成でNavisphere CLIのインストールディレクトリが正しいことを確認する
* データコレクタ構成でVNXブロックストレージのIPが正しいことを確認します。
* Data Infrastructure Insights Acquisition Unitから：
+
** CMDを開きます。
** 設定したインストールディレクトリにディレクトリを変更します。
** 「navicli -h {ip} getagent」と入力して、VNXブロックストレージデバイスとの接続を試行します（{ip}を実際のIPに置き換えます）。






 a| 
エラー： 4.29 emc235848 emc241018 getAll Failed to parse host alias info
 a| 
これは ' アレイ自体のホスト・イニシエータ・データベースの問題が FLARE 29 によって破損したことが原因で発生する可能性がありますEMC ナレッジベースの記事 emc235848 、 emc241018 を参照してください。また、 https://now.netapp.com/Knowledgebase/solutionarea.asp?id=kb58128[]



 a| 
エラー：メタデータ LUN を取得できません。java -jar navicli.jar の実行中にエラーが発生しました
 a| 
* セキュアクライアントを使用するようにデータコレクタの設定を変更する（推奨）
* navicli.exeまたはnaviseccli.exeへのCLIパスにnavicli.jarをインストールします。
* 注：navicli.jarはEMC Navisphereバージョン6.26で廃止されました
* navicli.jarは\http://powerlink.emc.comから入手できます。




 a| 
エラー：ストレージプールから、設定された IP アドレスのサービスプロセッサのディスクが報告されません
 a| 
サービスプロセッサの両方の IP をカンマで区切ってデータコレクタを設定します



 a| 
エラー：リビジョン不一致エラー
 a| 
* これは通常、VNXブロックストレージデバイスのファームウェアの更新が原因で発生しますが、NaviCLI.exeのインストールは更新されません。ファームウェアが異なる複数のデバイスがあっても、インストールされている CLI が 1 つだけ（ファームウェアバージョンが異なる）の場合にも、この問題が発生する可能性があります。
* デバイスとホストの両方で同じバージョンのソフトウェアが実行されていることを確認します。
+
** Data Infrastructure Insights Acquisition Unitで、コマンドラインウィンドウを開く
** 設定したインストールディレクトリにディレクトリを変更します。
** 「navicli -h <ip> getagent」と入力して、CLARiXデバイスとの接続を確立します。
** 最初の2行でバージョン番号を探します。例：エージェントリビジョン：6.16.2(0.1)
** 最初の行のバージョンを探して比較します。例： Navisphere CLI Revision 6.07.00.04.07






 a| 
エラー：サポート対象外の構成 - Fibre Channel ポートがありません
 a| 
デバイスにファイバチャネルポートが設定されていない。現在サポートされているのは FC 構成のみです。このバージョン / ファームウェアがサポートされていることを確認してください。

|===
詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
