---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: デバイス解像度は、環境内のパフォーマンスとインベントリを正確に追跡するのに役立ちます。 
---
= デバイス解像度ルール
:hardbreaks:
:allow-uri-read: 


[role="lead"]
現在Data Infrastructure Insightsによって自動的に識別されないホスト、ストレージ、およびテープを識別するためのデバイス解決ルールを作成します。作成するルールは、現在環境内にあるデバイスを識別し、環境に追加された類似のデバイスも識別します。



== デバイス解決ルールの作成

ルールを作成するときは、まず、ルールが実行される情報のソース、情報の抽出に使用する方法、およびルールの結果に DNS ルックアップが適用されるかどうかを特定します。

[cols="2*"]
|===


| デバイスを識別するために使用されるソース | * ホストの SRM エイリアス * 埋め込まれたホスト名またはテープ名を含むストレージ エイリアス * 埋め込まれたホスト名またはテープ名を含むスイッチ エイリアス * 埋め込まれたホスト名を含むゾーン名 


| ソースからデバイス名を抽出するために使用される方法 | * そのまま（SRMから名前を抽出） * 区切り文字 * 正規表現 


| DNSルックアップ | DNSを使用してホスト名を検証するかどうかを指定します 
|===
自動解決ルール タブでルールを作成します。次の手順では、ルール作成プロセスについて説明します。

.手順
. *管理 > デバイスの解像度*をクリックします
. *自動解決ルール*タブで、*+ ホスト ルール*または*+ テープ ルール*をクリックします。
+
*解決ルール*画面が表示されます。

+

NOTE: 正規表現の作成に関するヘルプと例については、[一致条件の表示] リンクをクリックしてください。

. *タイプ* リストで、識別するデバイスを選択します。
+
_ホスト_ または _テープ_ を選択できます。

. *ソース* リストで、ホストを識別するために使用するソースを選択します。
+
選択したソースに応じて、 Data Infrastructure Insights は次の応答を表示します。

+
.. *ゾーン* には、Data Infrastructure Insightsによって識別される必要があるゾーンと WWN がリストされます。
.. *SRM* は、Data Infrastructure Insightsによって識別される必要がある未識別のエイリアスをリストします。
.. *ストレージエイリアス*は、Data Infrastructure Insightsで識別する必要があるストレージエイリアスとWWNをリストします。
.. *スイッチエイリアス*は、Data Infrastructure Insightsで識別する必要があるスイッチエイリアスをリストします。


. *方法* リストで、ホストを識別するために使用する方法を選択します。
+
|===


| ソース | 方法 


| SRM | そのまま、区切り文字、正規表現 


| ストレージエイリアス | 区切り文字、正規表現 


| エイリアスを切り替える | 区切り文字、正規表現 


| ゾーン | 区切り文字、正規表現 
|===
+
** 区切り文字を使用するルールでは、区切り文字とホスト名の最小長が必要です。ホスト名の最小長は、 Data Infrastructure Insights がホストを識別するために使用する文字数です。  Data Infrastructure Insights は、この長さ以上であるホスト名に対してのみ DNS ルックアップを実行します。
+
区切り文字を使用するルールの場合、入力文字列は区切り文字によってトークン化され、隣接するトークンのいくつかの組み合わせを作成することによってホスト名候補のリストが作成されます。リストは最大から最小の順に並べ替えられます。たとえば、入力ストリングが _vipsnq03_hba3_emc3_12ep0_ の場合、リストは次のようになります。

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12話0話
*** emc3
*** hba3


** 正規表現を使用するルールでは、正規表現、形式、大文字と小文字の区別の選択が必要です。


. すべてのルールを実行するには、[*AR を実行*] をクリックします。作成したルール (および AR の最後の完全実行以降に作成されたその他のルール) を実行するには、ボタンの下矢印をクリックします。
+
ルール実行の結果は *FC 識別* タブに表示されます。





== デバイスの解像度の自動更新を開始します

デバイス解像度の更新では、前回の完全自動デバイス解像度実行以降に追加された手動変更がコミットされます。更新を実行すると、デバイスの解像度構成に対して行われた新しい手動エントリのみをコミットして実行できます。完全なデバイス解像度の実行は実行されません。

.手順
. Data Infrastructure Insights Web UI にログインします。
. *管理 > デバイスの解像度*をクリックします
. *デバイス解像度*画面で、*AR 実行*ボタンの下向き矢印をクリックします。
. 更新を開始するには、[*更新*] をクリックします。




== ルール支援による手動識別

この機能は、特定のルールまたはルールのリスト（1 回限りの並べ替えの有無にかかわらず）を実行して、不明なホスト、ストレージ、およびテープ デバイスを解決する特殊な場合に使用されます。

.開始する前に
識別されていないデバイスがいくつかあり、他のデバイスを正常に識別したルールも複数あります。


NOTE: ソースにホスト名またはデバイス名の一部のみが含まれている場合は、正規表現ルールを使用してフォーマットし、不足しているテキストを追加します。

.手順
. Data Infrastructure Insights Web UI にログインします。
. *管理 > デバイスの解像度*をクリックします
. *ファイバーチャネル識別*タブをクリックします。
+
システムは、デバイスとその解決ステータスを表示します。

. 識別されていないデバイスを複数選択します。
. *一括アクション*をクリックし、*ホスト解像度の設定*または*テープ解像度の設定*を選択します。
+
システムは、デバイスを正常に識別したすべてのルールのリストを含む「識別」画面を表示します。

. ルールの順序を、ニーズに合った順序に変更します。
+
ルールの順序は識別画面で変更されますが、グローバルには変更されません。

. ニーズに合った方法を選択してください。


Data Infrastructure Insights は、メソッドが表示されている順序で、上位のメソッドから順にホスト解決プロセスを実行します。

適用されるルールに遭遇すると、ルール名がルール列に表示され、手動として識別されます。

関連している：link:task_device_resolution_fibre_channel.html["ファイバーチャネルデバイスの解像度"] link:task_device_resolution_ip.html["IPデバイスの解像度"] link:task_device_resolution_preferences.html["デバイスの解像度の設定"]
