---
sidebar: sidebar 
permalink: task_create_annotation_rules.html 
summary: 注釈ルールを作成して、複数のアセットに注釈を自動的に適用します。 
keywords: annotate, annotation, rules 
---
= アノテーション ルールの作成
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
注釈ルールを使用すると、定義した基準に基づいて複数のアセットに注釈を自動的に適用できます。  Data Infrastructure Insights は、これらのルールに基づいてアセットに注釈を割り当てます。  Cloud Insight が注釈ルールを評価する際、個々のアセット ページに手動で設定された注釈は、ルールベースの注釈よりも優先されます。

.開始する前に
注釈ルールのクエリを作成しておく必要があります。

.手順
. Data Infrastructure Insightsサイト メニューで、*管理 > 注釈ルール* をクリックします。
. 新しい注釈ルールを追加するには、[*+ ルール*] をクリックします。
+
「ルールの追加」ダイアログが表示されます。

. 次の手順を実行します。
+
.. *名前* ボックスに、ルールを説明する一意の名前を入力します。
+
名前は「注釈ルール」ページに表示されます。

.. *クエリ*をクリックし、注釈が適用される資産を識別するためにData Infrastructure Insightsが使用するクエリを選択します。
.. *注釈*をクリックし、適用する注釈を選択します。
.. *値*をクリックし、注釈の値を選択します。
+
たとえば、注釈として「誕生日」を選択した場合は、値に日付を指定します。

.. *保存*をクリックします
.. すべてのルールをすぐに実行する場合は、[すべてのルールを実行] をクリックします。それ以外の場合は、ルールは定期的にスケジュールされた間隔で実行されます。
+

NOTE: 大規模なData Infrastructure Insights環境では、注釈ルールの実行が完了するまでに時間がかかることがあります。これは、インデクサーが最初に実行され、ルールを実行する前に完了する必要があるためです。インデクサーにより、 Data Infrastructure Insights はデータ内の新規または更新されたオブジェクトやカウンターを検索したりフィルター処理したりできるようになります。ルール エンジンは、インデクサーが更新を完了するまで待機してから、ルールを適用します。







== 注釈ルールの変更

注釈ルールを変更して、ルールの名前、注釈、注釈の値、またはルールに関連付けられたクエリを変更できます。

.手順
. Data Infrastructure Insightsメニューで、*管理 > 注釈ルール* をクリックします。
+
「注釈ルール」ページには、既存の注釈ルールのリストが表示されます。

. 変更する注釈ルールを見つけます。
+
フィルター ボックスに値を入力して注釈ルールをフィルターしたり、ページ番号をクリックしてページごとに注釈ルールを参照したりできます。

. 変更するルールのメニューアイコンをクリックします。
. *編集*をクリック
+
ルールの編集ダイアログが表示されます。

. 注釈ルールの名前、注釈、値、またはクエリを変更します。




== ルールの順序の変更

注釈ルールは、ルール リストの上から下に向かって処理されます。ルールが処理される順序を変更するには、次の手順を実行します。

.手順
. 移動するルールのメニューアイコンをクリックします。
. ルールが目的の場所に表示されるまで、必要に応じて *上へ移動* または *下へ移動* をクリックします。


アセット上の同じ注釈を更新する複数のルールを実行する場合、最初のルール (上から下に実行) が注釈を適用してアセットを更新し、次に 2 番目のルールが適用されますが、前のルールによって既に設定されている注釈は変更されないことに注意してください。



== アノテーション ルールの削除

使用されなくなった注釈ルールを削除する必要がある場合があります。

.手順
. Data Infrastructure Insightsメニューで、*管理 > 注釈ルール* をクリックします。
+
「注釈ルール」ページには、既存の注釈ルールのリストが表示されます。

. 削除する注釈ルールを見つけます。
+
フィルター ボックスに値を入力して注釈ルールをフィルターしたり、ページ番号をクリックしてページごとに注釈ルールを参照したりできます。

. 削除するルールのメニューアイコンをクリックします。
. *削除*をクリックします
+
ルールを削除するかどうかを確認する確認メッセージが表示されます。

. [OK]をクリックします

