---
sidebar: sidebar 
permalink: task_dc_ibm_svc.html 
keywords: IBM, SVC,SAN 
summary: IBM SAN Volume Controller データコレクタの設定 
---
= IBM SAN Volume Controller データコレクタの設定
:toc: macro
:hardbreaks:
:toclevels: 2
:allow-uri-read: 
:toc: 
:toclevels: 2
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
IBM SVC データコレクタは、 SSH を使用してインベントリとパフォーマンスのデータを収集し、 SVC オペレーティングシステムを実行するさまざまなデバイスをサポートします。

サポートされるデバイスには、 SVC 、 v7000 、 v5000 、 v3700 などのモデルが含まれます。サポートされるモデルとファームウェアバージョンについては、Data Infrastructure Insightsサポートマトリックスを参照してください。



== 用語

Data Infrastructure Insightsは、IBM SVCデータコレクタから次のインベントリ情報を取得します。Data Infrastructure Insightsで取得したアセットタイプごとに、このアセットに使用される最も一般的な用語が表示されます。このデータコレクタを表示またはトラブルシューティングするときは、次の用語に注意してください。

[cols="2*"]
|===
| ベンダー / モデルの用語 | Data Infrastructure Insightsの用語 


| ドライブ | ディスク 


| クラスタ | ストレージ 


| ノード | ストレージノード 


| mdisk グループ | ストレージプール 


| 仮想ディスク | ボリューム 


| mdisk | バックエンド LUN とパス 
|===
注：これらは一般的な用語の対応のみを示したものであり、このデータコレクタのすべてのケースを表しているわけではありません。



=== インベントリの要件

* 各 SVC クラスタの IP アドレス
* ポート 22 を使用できます
* 読み取り専用のユーザ名とパスワード




=== パフォーマンス要件

* SVC コンソールはすべての SVC クラスタに必須であり、 SVC 検出基本パッケージに必要です。
* クレデンシャルには、クラスタノードから構成ノードにパフォーマンスファイルをコピーするためだけに管理アクセスレベルが必要になります。
* データ収集を有効にするには、 SSH を使用して SVC クラスタに接続し、次のコマンドを実行します。 svctask startstats -interval 1_
+
注：データ収集は SVC 管理ユーザインターフェイスを使用して有効にすることもできます。





== 構成

[cols="2*"]
|===
| フィールド | 製品説明 


| クラスタ IP アドレス | SVC ストレージの IP アドレスまたは完全修飾ドメイン名 


| Inventory User Name の略 | SVC CLIのユーザ名 


| Inventory Password （インベントリパスワード） | SVC CLIのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 製品説明 


| インベントリポーリング間隔（分） | インベントリのポーリング間隔。デフォルトは40分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンスのポーリング間隔デフォルトは300秒です。 


| ダンプされた統計情報ファイルをクリーンアップする場合 | ダンプされた統計情報ファイルをクリーンアップするには ' このチェックボックスをオンにします 
|===


== トラブルシューティング

このデータコレクタで問題が発生した場合の対処方法を次に示します。

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー： " 構成ノードで実行されていないため、コマンドを開始できません。 " | このコマンドは構成ノードで実行する必要があります。 
|===
このデータコレクタで問題が発生した場合の対処方法を次に示します。

[cols="2*"]
|===
| 問題 | 次の操作を実行します 


| エラー： " 構成ノードで実行されていないため、コマンドを開始できません。 " | このコマンドは構成ノードで実行する必要があります。 
|===
このData Collectorの詳細については、のページまたはをlink:reference_data_collector_support_matrix.html["Data Collector サポートマトリックス"]参照してlink:concept_requesting_support.html["サポート"]ください。
