---
sidebar: sidebar 
permalink: task_cloud_insights_onboarding_1.html 
summary: Data Infrastructure Insightsにサインアップし、テナントを作成します。 
keywords: onboarding, new user 
---
= Data Infrastructure Insightsインサイトオンボーディング
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Data Infrastructure Insightsの使用を開始する前に、* NetApp Console* ポータルにサインアップする必要があります。  NetApp Consoleのログイン情報をすでにお持ちの場合は、簡単な手順でData Infrastructure Insightsの無料トライアルを開始できます。



== NetApp Consoleアカウントの作成

NetAppのクラウドサービスを開始するには、link:https://console.netapp.com/["* NetApp Console*"^] *開始*をクリックします。

* まだサインアップしていない場合は、「サインアップ」を選択してください
* 有効なビジネス用メールアドレスを入力し、パスワードを選択してください。
* 会社名と氏名を入力してください。
* 利用規約に同意して、[続行] を選択します。
* コンソールで開始手順を説明します。




=== すでにNetApp Consoleログインを持っている場合はどうなりますか?

NetApp Consoleアカウントを取得したら、link:https://console.netapp.com/["* NetApp Console*"^]ポータルページ。

メールアドレスとパスワードを入力してください。次に、NetApp のクラウド オファリング ページに移動します。

Data Infrastructure Insightsの詳細を確認したり、デモをリクエストしたりするには、「分析と制御」 > 「可観測性」に移動してください。



== Data Infrastructure Insightsの無料トライアルを開始する

Data Infrastructure Insightsに初めてログインする場合は、 Data Infrastructure Insightsが提供するすべての内容を読み、_開始する準備_ができたら、[トライアルをリクエスト] をクリックして情報を入力してください。

トライアルテナントのセットアップの一環として、テナントをホストするリージョンと、テナントを AWS に配置するか Azure に配置するかを選択します。

テナントの作成が完了したら、コンソールの資格情報を使用してログインし、 Data Infrastructure Insightsの 30 日間無料トライアルを開始します。このトライアル期間中、 Data Infrastructure Insightsが提供する機能を試すことができます。

無料トライアル期間中は、link:concept_subscribing_to_cloud_insights.html["購読を開始する"]いつでもData Infrastructure Insightsにアクセスできます。サブスクライブすると、現在のサブスクリプションに基づいてData Infrastructure Insights機能を使用できます。



== Sign inて出発

テナントが作成されると、いつでもNetApp BlueXPポータルにログインして、 link:https://services.cloud.netapp.com["クラウド サービス"] ページに移動し、「*Data Infrastructure Insightsに移動*」を選択します。

ブラウザを開いて、 Data Infrastructure Insightsテナント URL に直接アクセスすることもできます。次に例を示します。

 \https://<tenant-prefix>.c01.cloudinsights.netapp.com/
簡単にアクセスしてブックマークできるように、各ユーザーの招待メールにも URL が含まれます。ユーザーがまだコンソールにログインしていない場合は、ログインするように求められます。


NOTE: 新しいユーザーは、テナント URL にアクセスする前に、コンソールへのアクセスにサインアップする必要があります。

新しいテナントに初めてログインすると、設定のガイドが表示されます。link:task_getting_started_with_cloud_insights.html["*データ収集を開始*"] 。



== ログアウト

Data Infrastructure Insightsからログアウトするには、*ユーザー名* をクリックし、*ログアウト* を選択します。コンソールのサインイン画面に戻ります。


NOTE: Data Infrastructure Insightsからログアウトすると、コンソールからもログアウトされます。コンソール サインインを使用する他のNetApp Cloud サービスからもログアウトされます。



=== 非アクティブ時のタイムアウト

デフォルトでは、コンソールは 6 時間 (360 分) にわたってアクティビティがない場合にユーザーをログアウトします。アクティビティに関係なく、ユーザーは 7 日後にログアウトされます。
