---
sidebar: sidebar 
permalink: task_dc_emc_datadomain.html 
keywords: data collector, Data Domain, EMC, DELL 
summary: DELL EMC Data Domain データ コレクターを構成します。 
---
= DELL EMC Data Domain データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、DELL EMC Data Domain 重複排除ストレージ システムからインベントリとパフォーマンス情報を収集します。このデータ コレクターを構成するには、特定の構成手順と使用上の推奨事項に従う必要があります。



== 用語

Data Infrastructure Insights は、 Data Domain データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| アレイ | ストレージ 


| FCポート | ポート 


| ファイルシステム | 内部容積 


| クォータ | クォータ 


| NFSとCIFSの共有 | ファイルシェア 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ収集ツールのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次の情報が必要です。

* Data DomainデバイスのIPアドレス
* Data Domainストレージへの読み取り専用ユーザー名とパスワード
* SSH、ポート22




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| IPアドレス | Data Domain ストレージアレイの IP アドレスまたは完全修飾ドメイン名 


| ユーザ名 | Data Domainストレージアレイのユーザー名 


| パスワード | Data Domainストレージアレイのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは 20 です。 


| SSHポート | SSHサービスポート 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
