---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Nutanix データ コレクターを構成します。 
---
= Nutanix NX データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Nutanix データ コレクターを使用して、Nutanix NX ストレージ システムのインベントリとパフォーマンス データを検出します。



== 用語

Data Infrastructure Insights は、 Nutanix データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ プール | ストレージ プール 


| Nutanixコンテナ | 内部容積 


| Nutanixコンテナ | ファイル共有 


| NFS 共有 | 共有 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* クラスタの外部データサービスIPアドレス
* 読み取り専用のユーザー名とパスワード（ボリューム グループが使用されていない場合）。ボリューム グループが使用されている場合は、管理者のユーザー名とパスワードが必要です。
* ポート要件: HTTPS 443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| Prism外部IPアドレス | クラスタの外部データサービスIPアドレス 


| ユーザ名 | 管理者アカウントのユーザー名 


| パスワード | 管理者アカウントのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCP ポート | Nutanix アレイに接続するために使用される TCP ポート。デフォルトは 9440 です。 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは60分です。 


| パフォーマンスポーリング間隔(秒) | パフォーマンス ポーリングの間隔。デフォルトは300秒です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
