---
sidebar: sidebar 
permalink: task_dc_ms_anf.html 
keywords: data collector, azure, Netapp files, anf 
summary: Azure NetApp Filesデータ コレクターを構成します。 
---
= Azure NetApp Filesデータ コレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Data Infrastructure Insights は、 Azure NetApp Filesデータ コレクターを使用して、インベントリとパフォーマンス データを取得します。



== 要件

このデータ コレクターを構成するには、次の情報が必要です。

* ポート要件: 443 HTTPS
* Azure 管理 REST IP (management.azure.com)
* Azure サービス プリンシパル クライアント ID (ユーザー アカウント)
* Azure サービス プリンシパル認証キー (ユーザー パスワード)
* Data Infrastructure Insights の検出用に Azure アカウントを設定する必要があります。
+
アカウントが適切に構成され、アプリケーションを Azure に登録すると、 Data Infrastructure Insightsを使用して Azure インスタンスを検出するために必要な資格情報が得られます。次のリンクでは、検出用のアカウントを設定する方法について説明しています。



https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[]



== 構成

以下の表に従って、データ コレクター フィールドにデータを入力します。

[cols="2*"]
|===
| フィールド | 説明 


| Azure サービス プリンシパル クライアント ID | AzureへのサインインID 


| Azure テナント ID | Azure テナント ID 


| Azure サービス プリンシパル認証キー | ログイン認証キー 


| 私は、MicrosoftがAPIリクエストに対して料金を請求することを理解しています | Insight ポーリングによって行われた API リクエストに対して Microsoft が課金することを理解していることを確認するには、これにチェックを入れます。 
|===


== 詳細設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは60です 
|===


== トラブルシューティング

* ANF データ コレクターが使用する資格情報には、ANF ボリュームを含むすべての Azure サブスクリプションへのアクセス権が必要です。
* 読者アクセスによってパフォーマンス収集が失敗する場合は、リソース グループ レベルで共同作成者アクセスを付与してみてください。


このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
