---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: 要約。 
---
= 構成されたデータコレクターの管理
:hardbreaks:
:allow-uri-read: 


[role="lead"]
「インストールされたデータ コレクター」ページでは、Data Infrastructure Insights用に構成されたデータ コレクターにアクセスできます。このページを使用して、既存のデータ コレクターを変更できます。

.手順
. Data Infrastructure Insightsサイトメニューで、*オブザーバビリティ>コレクター*をクリックします。
+
利用可能なデータ コレクター画面が表示されます。

. *インストールされたデータコレクター*をクリックします
+
インストールされているすべてのデータ コレクターのリストが表示されます。リストには、コレクターの名前、ステータス、コレクターがアクセスしている IP アドレス、デバイスから最後にデータが取得された日時が表示されます。この画面で実行できるアクションは次のとおりです。

+
** ポーリングを制御する
** データコレクターの資格情報を変更する
** クローンデータコレクター






== データコレクタのポーリングの制御

データ コレクターに変更を加えた後、変更内容を確認するためにすぐにポーリングを実行したい場合や、問題の解決に取り組んでいる間、データ コレクターでのデータ収集を 1 日、3 日、または 5 日間延期したい場合があります。

.手順
. Data Infrastructure Insightsサイトメニューで、*オブザーバビリティ>コレクター*をクリックします。
. *インストールされたデータコレクター*をクリックします
. 変更したいデータコレクターの左側のチェックボックスを選択します
. *一括アクション*をクリックし、実行する投票アクションを選択します。
+
複数のデータ コレクターに対して同時に一括アクションを実行できます。データ コレクターを選択し、[*一括アクション*] メニューから実行するアクションを選択します。





== データ収集者の情報を編集する

既存のデータ コレクターのセットアップ情報を編集できます。

.単一のデータコレクターを編集するには:
. [Data Infrastructure Insights]メニューで、*[可観測性] > [コレクター]* をクリックして、インストールされているデータ コレクターのリストを開きます。
. 変更するデータ コレクターの右側にあるオプション メニューで、[*編集*] をクリックします。
+
コレクター編集ダイアログが開きます。

. 変更を入力し、「*構成のテスト*」をクリックして新しい構成をテストするか、「*保存*」をクリックして構成を保存します。


複数のデータ コレクターを編集することもできます。

. 変更する各データ コレクターの左側にあるチェック ボックスをオンにします。
. *一括操作* ボタンをクリックし、*編集* を選択して、データ コレクターの編集ダイアログを開きます。
. 上記のようにフィールドを変更します。
+

NOTE: 選択したデータ コレクターは同じベンダーとモデルであり、同じ取得ユニット上に存在している必要があります。

+
複数のデータ コレクターを編集する場合、データ コレクター名フィールドに「混合」と表示され、編集できません。ユーザー名やパスワードなどの他のフィールドには「混合」と表示され、編集できます。選択したデータ コレクター間で同じ値を共有するフィールドには現在の値が表示され、編集できます。

+
複数のデータ コレクターを編集する場合、[テスト構成] ボタンは使用できません。





== データ収集装置のクローン作成

クローン機能を使用すると、別のデータ ソースと同じ資格情報と属性を持つデータ ソースをすばやく追加できます。クローン作成により、同じデバイス タイプの複数のインスタンスを簡単に構成できます。

.手順
. Data Infrastructure Insightsサイト メニューで、*可観測性 > コレクター* をクリックします。
. *インストールされたデータコレクター*をクリックします。
. コピーするデータ コレクターの左側にあるチェック ボックスをクリックします。
. 選択したデータ コレクターの右側にあるオプション メニューで、[*複製*] をクリックします。
+
クローン データ コレクター ダイアログが表示されます。

. 必須フィールドに新しい情報を入力します。
. *保存*をクリックします。


.終了後の操作
クローン操作では、他のすべての属性と設定がコピーされ、新しいデータ コレクターが作成されます。



== データコレクターに対する一括アクションの実行

複数のデータ コレクターの一部の情報を同時に編集できます。この機能を使用すると、複数のデータ コレクターでポーリングを開始したり、ポーリングを延期したり、ポーリングを再開したりできます。さらに、複数のデータ コレクターを削除することもできます。

.手順
. Data Infrastructure Insightsサイトメニューで、*オブザーバビリティ>コレクター*をクリックします。
. *インストールされたデータコレクター*をクリックします
. 変更するデータ コレクターの左側にあるチェック ボックスをクリックします。
. 右側のオプション メニューで、実行するオプションをクリックします。


.終了後の操作
選択した操作はデータ コレクターに対して実行されます。データ コレクターを削除することを選択した場合、アクションの確認を求めるダイアログが表示されます。
