---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: DELL EMC RecoverPoint データ コレクターを構成します。 
---
= Dell EMC RecoverPointデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
EMC RecoverPoint データ コレクターの主な使用例は、RecoverPoint ストレージ アプライアンスによって実現されるボリューム間のレプリケーション関係を検出することです。このコレクターは、Recoverpoint アプライアンス自体も検出します。  Dell/EMCはVMwareのVMwareバックアップソリューション「RecoverPoint for VMs」を販売していますが、このコレクターではサポートされていません。

構成の場合、データ コレクターには、ストレージ プロセッサの IP アドレスと読み取り専用のユーザー名とパスワードが必要です。

EMC RecoverPoint データ コレクターは、R​​ecoverPoint が他のストレージ アレイ間で調整するボリューム間のレプリケーション関係を収集します。 Data Infrastructure Insights は、各 RecoverPoint クラスターのストレージ アレイを表示し、そのクラスター上のノードとストレージ ポートのインベントリ データを収集します。ストレージ プールまたはボリューム データは収集されません。



== 要件

このデータ コレクターを構成するには、次の情報が必要です。

* ストレージプロセッサのIPアドレスまたは完全修飾ドメイン名
* 読み取り専用のユーザー名とパスワード
* ポート443経由のREST APIアクセス




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| RecoverPointのアドレス | RecoverPoint クラスタの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | RecoverPointクラスタのユーザー名 


| パスワード | RecoverPointクラスタに使用されるパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCPポート | Recoverpoint クラスタへの接続に使用される TCP ポート 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは20分です。 


| 除外されたクラスター | ポーリング時に除外するクラスター ID または名前のコンマ区切りリスト。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
