---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= 設定タブのオプションの設定
:hardbreaks:
:allow-uri-read: 


[role="lead"]
デバイス解決の設定タブでは、自動解決スケジュールを作成したり、識別に含めるか除外するストレージおよびテープ ベンダーを指定したり、DNS ルックアップ オプションを設定したりできます。



== 自動解決スケジュール

自動解決スケジュールでは、自動デバイス解決がいつ実行されるかを指定できます。

|===


| オプション | 説明 


| 間隔 | このオプションを使用して、日、時間、または分間隔で自動デバイス解決を実行します。 


| 毎日 | このオプションを使用すると、毎日特定の時間に自動デバイス解決を実行できます。 


| 手動 | 自動デバイス解決を手動でのみ実行するには、このオプションを使用します。 


| あらゆる環境の変化において | このオプションを使用すると、環境に変化があるたびに自動デバイス解決が実行されます。 
|===
_Manually_ を指定すると、夜間の自動デバイス解決は無効になります。



== DNS処理オプション

DNS 処理オプションでは、次の機能を選択できます。

* DNS ルックアップ結果処理が有効になっている場合は、解決されたデバイスに追加する DNS 名のリストを追加できます。
* IP の自動解決を選択すると、DNS ルックアップを使用して iSCSI イニシエーターおよび NFS 共有にアクセスするホストの自動ホスト解決が有効になります。指定しない場合は、FC ベースの解決のみが実行されます。
* ホスト名にアンダースコアを許可し、結果に標準のポートエイリアスの代わりに「接続先」エイリアスを使用するように選択できます。




=== 特定のストレージおよびテープベンダーを含めるか除外するか

自動解決のために特定のストレージおよびテープ ベンダーを含めたり除外したりできます。たとえば、特定のホストがレガシー ホストになり、新しい環境から除外する必要があることがわかっている場合は、特定のベンダーを除外する必要があるかもしれません。以前除外したが、今後は除外したくないベンダーを再度追加することもできます。


NOTE: テープ デバイス解決ルールは、ベンダー設定でその WWN のベンダーが [テープとしてのみ含める] に設定されている WWN に対してのみ機能します。

参照:link:concept_device_resolution_regex_examples.html["正規表現の例"]
