---
sidebar: sidebar 
permalink: task_dc_infinidat_infinibox.html 
keywords: data collector, infinidat, InfiniBox 
summary: Infinidat InfiniBox データ コレクターを構成します。 
---
= Infinidat InfiniBox データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Infinidat InfiniBox (HTTP) データ コレクターは、Infinidat InfiniBox ストレージ システムからインベントリ情報を収集するために使用されます。



== 用語

Data Infrastructure Insights は、 Infinidat InfiniBox データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ストレージ プール | ストレージ プール 


| ノード | コントローラ 


| Filesystem | 内部容積 


| Filesystem | ファイル共有 


| ファイルシステムのエクスポート | 共有 
|===


== 要件

このデータ コレクターを構成する際の要件は次のとおりです。

* InfiniBox管理ノードのIPアドレスまたはFQDN
* 管理者のユーザーIDとパスワード
* REST API経由のポート443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| InfiniBoxホスト | InfiniBox 管理ノードの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | InfiniBox管理ノードのユーザー名 


| パスワード | InfiniBox管理ノードのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| TCPポート | InfiniBox サーバーに接続するために使用される TCP ポート。デフォルトは 443 です。 


| インベントリポーリング間隔 | インベントリ ポーリングの間隔。デフォルトは60分です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
