---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, PowerFlex EMC, DELL 
summary: DELL EMC ScaleIO/PowerFlex データ コレクターを構成します。 
---
= DELL EMC ScaleIO / PowerFlex データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
ScaleIO/PowerFlex データ コレクターは、ScaleIO および PowerFlex ストレージからインベントリ情報を収集します。このデータ コレクターを構成するには、ScaleIO/PowerFlex ゲートウェイ アドレスと管理者のユーザー名とパスワードが必要です。



== 用語

Data Infrastructure Insights は、 ScaleIO/PowerFlex データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| MDM（メタデータマネージャー）クラスター | ストレージ 


| SDS (ScaleIO/PowerFlex データ サーバー) | ストレージ ノード 


| ストレージ プール | ストレージ プール 


| Volume | Volume 


| デバイス | ディスク 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

* 管理者ユーザーアカウントへの読み取り専用アクセス
* ポート要件: HTTPS ポート 443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| ScaleIO/PowerFlex ゲートウェイ | ScaleIO/PowerFlex ゲートウェイの IP アドレスまたは FQDN（カンマ (,) またはセミコロン (;) で区切る） 


| ユーザー名 | ScaleIO/PowerFlexデバイスにログインするために使用される管理者ユーザー名 


| パスワード | ScaleIO/PowerFlexデバイスにログインするために使用するパスワード 
|===


== 高度な設定

インベントリ収集を有効にするには、[インベントリ] チェックボックスをクリックします。

[cols="2*"]
|===
| フィールド | 説明 


| HTTPS ポート | 443 


| インベントリポーリング間隔（分） | デフォルトは 60 です。 


| 接続タイムアウト（秒） | デフォルトは 60 です。 
|===


== トラブルシューティング

追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
