---
sidebar: sidebar 
permalink: task_query_assign_multiple_applications.html 
summary: クエリを使用して、オブジェクトに複数のアプリケーションまたは注釈を割り当てたり、オブジェクトから複数のアプリケーションまたは注釈を削除したりします。 
keywords: query, queries, application, annotation, multiple 
---
= 資産に複数のアプリケーションを割り当てたり、資産から複数のアプリケーションを削除したりする
:hardbreaks:
:allow-uri-read: 


[role="lead"]
複数割り当て可能link:task_create_application.html["アプリケーション"]手動で複数のアプリケーションを割り当てたり削除したりする代わりに、クエリを使用して複数のアプリケーションを資産に追加したり削除したりできます。


NOTE: 以下の手順で追加または削除できますlink:task_defining_annotations.html["アノテーション"]同じように。

.開始する前に
編集するすべてのアセットを検索するクエリをすでに作成しておく必要があります。

.手順
. *探索*をクリックし、*メトリッククエリ*を選択します。
+
クエリ ページが表示されます。

. アセットを検索するクエリの名前をクリックします。
+
クエリに関連付けられたアセットのリストが表示されます。

. リストで必要なアセットを選択するか、上部のチェックボックスをクリックして「すべて」を選択します。
+
一括アクションのドロップダウンが表示されます。

. 選択したアセットにアプリケーションを追加するには、「一括操作」をクリックし、「アプリケーションの追加」を選択します。
. 1 つ以上のアプリケーションを選択します。
+
ホスト、内部ボリューム、qtree、仮想マシンに対しては複数のアプリケーションを選択できますが、ボリュームまたは共有に対しては 1 つのアプリケーションしか選択できません。

. *保存*をクリックします。
. 資産に割り当てられたアプリケーションを削除するには、「一括操作」をクリックし、「アプリケーションの削除」を選択します。
. 削除するアプリケーションを選択します。
. *削除*をクリックします。


割り当てた新しいアプリケーションは、別のアセットから派生したアセット上のアプリケーションを上書きします。たとえば、ボリュームはホストからアプリケーションを継承し、新しいアプリケーションがボリュームに割り当てられると、新しいアプリケーションは派生アプリケーションよりも優先されます。

一括追加アクションで [保存] をクリックするか、一括削除アクションで [削除] をクリックすると、 Data Infrastructure Insights、アクションに時間がかかることが通知されます。このメッセージは閉じても構いません。アクションはバックグラウンドで続行されます。


NOTE: 関連する資産が大量にある環境では、それらの資産へのアプリケーション割り当ての継承に数分かかることがあります。関連する資産が多数ある場合は、継承が発生するまでにさらに時間がかかります。
