---
sidebar: sidebar 
permalink: task_dc_emc_unisphere_rest.html 
keywords: data collector, Unisphere, EMC 
summary: Dell EMC Unisphere REST データ コレクターを構成します。 
---
= Dell EMC Unisphere RESTデータコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータ コレクターは、Dell EMC Unisphere for PowerMax / Vmax 3 管理システムからインベントリとパフォーマンス データを取得します。

Dell/EMC は Unisphere 10.0 までボリュームごとの統計を導入していなかったことに注意してください。このデータ コレクターは 9.2.0 以降をサポートしていますが、ボリューム統計が存在しないため収集できません。

1 つの Unisphere for Vmax/PowerMax インスタンスが 1 つ以上の Symmetrix Vmax 3 以上のストレージ アレイを管理している可能性があります。このコレクターは、デフォルトで、その Unisphere インスタンスに対して「ローカル」であるすべてのアレイを検出しようとします。  Unisphere インスタンスが「リモート」アレイ (つまり、SRDF レプリケーション経由で接続されたもの) を認識する場合、それらは無視されます。それらを検出するには、そのサイト内のどの Unisphere インスタンスがそれらをローカルとして認識しているかを示す追加の Unisphere コレクターを、 Data Infrastructure Insights内に作成する必要があります。

構成には、データ コレクターに Unisphere サーバーの IP アドレス/FQDN、ポート 8443 への TCP 接続、およびユーザー名とパスワードが必要です。



== 要件

* Unisphere サーバーの IP アドレス/完全修飾ドメイン名
* ユーザ名とパスワード
* ポート 8443。




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| Unisphere サーバーの IP アドレス | Unisphere サーバーの IP アドレスまたは完全修飾ドメイン名 


| ユニスフィアポート | デフォルトは8443です 


| ユーザー名 | Unisphere サーバーのユーザー名 


| パスワード | Unisphere サーバーで使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは40分です。 


| パフォーマンスポーリング間隔（秒） | パフォーマンス ポーリングの間隔。 


| リストを指定するには「除外」または「含める」を選択します | VMを含めるか除外するかを指定する 


| インベントリフィルターデバイスリスト | フィルタリングする VM のリスト (コンマ区切り、または値にコンマが使用されている場合はセミコロン区切り) 


| Unisphere パフォーマンス ポーリング間隔 (秒) | デフォルトは300秒です 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| エラー: ユーザー認証に失敗しました。 | このデバイスの資格情報が正しいことを確認してください。 


| インベントリの最近のステータス: 予期しないデータが取得されました - アレイはボリューム 0 を報告しました | 通常、承認（認証ではない）の問題を示します。資格情報が正しいこと、およびユーザー名にすべてのボリュームを一覧表示してその属性を表示する権限があることを確認してください。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
