---
sidebar: sidebar 
permalink: task_dc_na_amazon_fsx.html 
keywords: 'data collector, stout, fsx, fsx-netapp, Amazon, AWS, cluster, volume, share, LUN"' 
summary: Amazon FSx for NetApp ONTAPデータコレクター 
---
= Amazon FSx for NetApp ONTAPデータコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
このデータコレクターは、Amazon FSx for NetApp ONTAPからインベントリとパフォーマンスデータを取得します。このデータ コレクターは、Data Infrastructure Insightsサービス リージョン全体で段階的に利用可能になります。  Data Infrastructure Insights環境にこのコレクターのアイコンが表示されない場合は、営業担当者にお問い合わせください。


NOTE: このData Infrastructure Insightsコレクターには、_Filesystem-Scoped_ ロールを持つONTAPユーザーが必要です。 AWSを確認してくださいlink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/roles-and-users.html["役割とルール"]利用可能なオプションのドキュメント。現時点では、AWS はファイルシステムスコープを持つユーザーロールとして _fsxadmin_ の 1 種類のみをサポートしています。これは、 Data Infrastructure Insightsコレクターに使用する適切なロールです。ユーザーには、http、ontapi、ssh の 3 つのアプリケーションもすべて割り当てられている必要があります。



== 用語

Data Infrastructure Insights は、 FSx- NetAppデータ コレクターからインベントリとパフォーマンス データを取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| クラスタ | ストレージ 


| LUN | Volume 


| Volume | 内部容積 
|===


== FSx- NetApp用語

次の用語は、FSx- NetAppストレージ アセット ランディング ページに表示されるオブジェクトまたは参照に適用されます。これらの条件の多くは、他のデータ収集者にも適用されます。



=== ストレージ

* モデル – このクラスター内の一意の個別のモデル名のカンマ区切りリスト。
* ベンダー – AWS
* シリアル番号 – アレイのシリアル番号。
* IP – 通常は、データ ソースで構成されている IP またはホスト名になります。
* 生の容量 – FSx ファイルシステムに割り当てられたすべての SSD ストレージの 2 を底とする合計。
* レイテンシ – 読み取りと書き込みの両方において、ホスト側のワークロードが経験している状況を表します。理想的には、 Data Infrastructure Insightsがこの値を直接取得しますが、多くの場合そうではありません。アレイがこれを提供する代わりに、 Data Infrastructure Insightsは通常、個々の内部ボリュームの統計から導き出された IOPS 加重計算を実行します。
* スループット – 内部ボリュームから集計されます。管理 – これにはデバイスの管理インターフェイスへのハイパーリンクが含まれる場合があります。インベントリレポートの一部として、 Data Infrastructure Insightsデータ ソースによってプログラムによって作成されます。




=== ストレージ プール

* ストレージ – このプールが存在するストレージ アレイ。必須。
* タイプ – 可能性のある列挙リストからの説明的な値。最も一般的なのは「アグリゲート」または「RAID グループ」です。
* 容量 – ここでの値は、論理的に使用されている容量、使用可能な容量、論理的な合計容量、およびこれらの間で使用されている割合です。
* IOPS – このストレージ プールに割り当てられたすべてのボリュームの合計 IOPS。
* スループット – このストレージ プールに割り当てられたすべてのボリュームの合計スループット。




== 要件

このデータ コレクターを構成して使用するための要件は次のとおりです。

* 「fsxadmin」ロールを持つアカウントにアクセスでき、それには ssh、ontapi、http の 3 つのアプリケーションが割り当てられている必要があります。
* アカウントの詳細にはユーザー名とパスワードが含まれます。
* ポート要件: 443




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| NetApp管理 IP | NetAppクラスタのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | NetAppクラスタのユーザー名 


| パスワード | NetAppクラスタのパスワード 
|===


== 高度なメトリクス

このデータ コレクターは、FSx for NetApp ONTAPストレージから次の高度なメトリックを収集します。

* fpolicy
* nfsv3
* nfsv3:ノード
* nfsv4
* nfsv4_1
* nfsv4_1:ノード
* nfsv4:ノード
* ポリシーグループ
* qtree
* 音量
* ワークロードボリューム


FSx CLI および API コマンドは、Data Infrastructure Insights ZAPI が収集しない一部の容量値を取得するため、特定の容量値 (ストレージ プールの値など) はData Infrastructure Insightsと FSx 自体で異なる場合があることに注意してください。



== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| 401 HTTP 応答または 13003 ZAPI エラー コードを受信し、ZAPI が「権限が不十分です」または「このコマンドは許可されていません」を返します。 | ユーザー名とパスワード、およびユーザー権限/許可を確認します。 


| ZAPI は「クラスタ ロールが cluster_mgmt LIF ではありません」を返します | AU はクラスター管理 IP と通信する必要があります。  IPを確認し、必要に応じて別のIPに変更します 


| 再試行後にZAPIコマンドが失敗する | AU はクラスターとの通信に問題があります。ネットワーク、ポート番号、IP アドレスを確認します。ユーザーは、AU マシンのコマンド ラインからコマンドを実行することも試みる必要があります。 


| AUはHTTP経由でZAPIに接続できませんでした | ZAPI ポートがプレーンテキストを受け入れるかどうかを確認します。  AU が SSL ソケットにプレーンテキストを送信しようとすると、通信は失敗します。 


| SSLException により通信が失敗しました | AU は、ファイラー上のプレーンテキスト ポートに SSL を送信しようとしています。  ZAPI ポートが SSL を受け入れるかどうかを確認するか、別のポートを使用します。 


| 追加の接続エラー: ZAPI 応答にエラー コード 13001、「データベースが開いていません」が含まれています。ZAPI エラー コードは 60 で、応答には「API が時間どおりに終了しませんでした」が含まれています。ZAPI 応答には「initialize_session() が NULL 環境を返しました」が含まれています。ZAPI エラー コードは 14007 で、応答には「ノードが正常ではありません」が含まれています。 | ネットワーク、ポート番号、IP アドレスを確認します。ユーザーは、AU マシンのコマンド ラインからコマンドを実行することも試みる必要があります。 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
