---
sidebar: sidebar 
permalink: task_dc_ms_hyperv.html 
keywords: data collector, Microsoft, Hyper-V 
summary: Microsoft Hyper-V データ コレクターを構成します。 
---
= Microsoft Hyper-V データコレクター
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Microsoft Hyper-V データ コレクターは、仮想化されたサーバー コンピューティング環境からインベントリとパフォーマンス データを取得します。このデータ コレクターは、スタンドアロン Hyper-V ホストまたはクラスター全体を検出できます。スタンドアロン ホストまたはクラスターごとに 1 つのコレクターを作成します。



== 用語

Data Infrastructure Insights は、 Microsoft Hyper-V (WMI) から次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| 仮想ハードディスク | 仮想ディスク 


| ホスト | ホスト 


| 仮想マシン | 仮想マシン 


| クラスター共有ボリューム（CSV）、パーティションボリューム | データ ストア 


| インターネット SCSI デバイス、マルチパス SCSI LUN | LUN 


| ファイバーチャネルポート | ポート 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成するには、次のものが必要です。

* Hyper-V では、データ収集とリモート アクセス/管理のためにポート 5985 を開く必要があります。
* クラスターまたはスタンドアロン ハイパーバイザーの IP アドレスまたは FQDN。フローティング クラスターのホスト名または IP を使用することは、クラスター内の特定の 1 つのノードのみにコレクターを向ける場合よりも、最も信頼性の高いアプローチであると考えられます。
* クラスター内のすべてのハイパーバイザーで機能する管理レベルのユーザー アカウント。
* WinRMはすべてのハイパーバイザーで有効化され、リッスンする必要がある
* ポート要件: WMI 経由のポート 135、および Windows 2003 以前では 1024 ～ 65535、Windows 2008 では 49152 ～ 65535 に割り当てられた動的 TCP ポート。
* データコレクターがIPアドレスのみを指している場合でも、DNS解決は成功する必要がある
* 各 Hyper-V ハイパーバイザーでは、すべてのホスト上のすべての VM に対して「リソース メータリング」をオンにする必要があります。これにより、各ハイパーバイザーは、各ゲストのData Infrastructure Insightsにさらに多くのデータを利用できるようになります。これを設定しないと、ゲストごとに取得されるパフォーマンス メトリックの数が少なくなります。リソースメータリングの詳細については、Microsoft のドキュメントを参照してください。
+
link:https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V リソースメータリングの概要"]

+
link:https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["VMリソースメータリングを有効にする"]




NOTE: Hyper-V データ コレクターには Windows Acquisition Unit が必要です。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| クラスタ IP アドレスまたはフローティング クラスタ FQDN | クラスタまたはスタンドアロンの非クラスタ化ハイパーバイザの IP アドレスまたは完全修飾ドメイン名 


| ユーザー名 | ハイパーバイザーの管理者ユーザー名 


| パスワード | ハイパーバイザーのパスワード 


| DNSドメインサフィックス | 単純なホスト名と組み合わせてハイパーバイザーの FQDN を表現するホスト名サフィックス 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | デフォルトは20分です。 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
