---
sidebar: sidebar 
permalink: task_dc_ibm_powervm.html 
keywords: IBM, powerVM, 
summary: IBM PowerVM データ コレクターを構成します。 
---
= IBM PowerVM データコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
IBM PowerVM (SSH) データ コレクターは、ハードウェア管理コンソール (HMC) によって管理される IBM POWER ハードウェア インスタンス上で実行されている仮想パーティションに関する情報を収集するために使用されます。



== 用語

Data Infrastructure Insights は、 IBM POWER ハードウェア インスタンス上で実行されている仮想パーティションからインベントリ情報を取得します。取得した資産の種類ごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| hdisk | 仮想ディスク 


| 管理システム | ホスト 


| LPAR、VIOサーバー | 仮想マシン 


| ボリューム グループ | データ ストア 


| 物理ボリューム | LUN 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



== 要件

このデータ コレクターを構成して使用するには、次の要件を満たす必要があります。

* ハードウェア管理コンソール (HMC) の IP アドレス
* SSH 経由でハードウェア管理コンソール (HMC) にアクセスするためのユーザー名とパスワード
* ポート要件 SSH-22
* すべての管理システムと論理パーティション セキュリティ ドメインの表示権限
+
ユーザーには、HMC 構成の表示権限と、HMC コンソール セキュリティ グループの VPD 情報を収集する機能も必要です。また、ユーザーには、論理パーティション セキュリティ グループの下で仮想 IO サーバー コマンド アクセスが許可されている必要があります。オペレーターのロールから開始し、その後すべてのロールを削除するのがベストプラクティスです。  HMC 上の読み取り専用ユーザーには、AIX ホスト上でプロキシ コマンドを実行する権限がありません。

* IBM のベストプラクティスは、デバイスを 2 台以上の HMC で監視することです。これにより、 OnCommand Insight が重複したデバイスを報告する可能性があることに注意してください。そのため、このデータ コレクターの詳細構成の「除外デバイス」リストに冗長デバイスを追加することを強くお勧めします。




== 構成

[cols="2*"]
|===
| フィールド | 説明 


| ハードウェア管理コンソール (HMC) IP アドレス | PowerVM ハードウェア管理コンソールの IP アドレスまたは完全修飾ドメイン名 


| HMCユーザ | ハードウェア管理コンソールのユーザー名 


| パスワード | ハードウェア管理コンソールで使用するパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは20分です。 


| SSHポート | PowerVMへのSSHに使用するポート 


| パスワード | ハードウェア管理コンソールで使用するパスワード 


| 再試行回数 | 在庫再試行回数 


| デバイスを除外 | 除外するデバイス ID または表示名のコンマ区切りリスト 
|===


== トラブルシューティング

このデータコレクターに関する追加情報は、link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
