---
sidebar: sidebar 
permalink: task_dc_emc_vnxe.html 
keywords: data collector, VNXe, EMC 
summary: VNXe データ コレクターを構成します。 
---
= EMC VNXeデータコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
DELL EMC VNXe データ コレクターは、VNXe 統合ストレージ アレイのインベントリ サポートを提供します。  Data Infrastructure Insights は現在、iSCSI および NAS プロトコルをサポートしています。



== 要件

* VNXe データ コレクターは CLI ベースです。VNXe データ コレクターが存在する取得ユニットに Unisphere for VNXe CLI (uemcli.exe) をインストールする必要があります。
* uemcli.exe はトランスポート プロトコルとして HTTPS を使用するため、取得ユニットは VNXe への HTTPS 接続を開始できる必要があります。
* VNXeデバイスのIPアドレスまたは完全修飾ドメイン名
* データ コレクターが使用するには、少なくとも読み取り専用ユーザーが必要です。
* 管理ソリューション イネーブラ サーバーの IP アドレス。
* ポート443のHTTPSが必要です
* EMC VNXe データ コレクターは、インベントリに NAS および iSCSI サポートを提供します。ファイバー チャネル ボリュームは検出されますが、 Data Infrastructure Insights はFC マッピング、マスキング、またはストレージ ポートを報告しません。




== 用語

Data Infrastructure Insights は、 VNXe データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="2*"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| ディスク | ディスク 


| ストレージ アレイ | ストレージ 


| プロセッサ | ストレージ ノード 


| ストレージ プール | ストレージ プール 


| 一般的な iSCSI ブロック情報、VMware VMFS | 共有 


| レプリケーションリモートシステム | 同期 


| iSCSIノード | iSCSIターゲットノード 


| iSCSI Initiator | iSCSI ターゲット イニシエーター 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ ソースのすべてのケースを反映しているわけではありません。



== 構成

[cols="2*"]
|===
| フィールド | 説明 


| VNXeストレージ | VNXeデバイスのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | VNXeデバイスのユーザー名 


| パスワード | VNXeデバイスのパスワード 
|===


== 高度な設定

[cols="2*"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは40分です 


| CLIポート | VNXe CLI で使用されるポート 


| パフォーマンスポーリング間隔（秒） | デフォルトは 300 です。 
|===


== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



=== インベントリ

[cols="2*"]
|===
| 問題： | これを試してください: 


| 「外部ユーティリティの実行に失敗しました」というエラー メッセージが表示され、「Unisphere 実行可能ファイル uemcli が見つかりませんでした」というエラー メッセージが表示される | * IP アドレス、ユーザー名、およびパスワードが正しいことを確認します。 * Unisphere CLI がData Infrastructure Insights Acquisition Unit にインストールされていることを確認します。 * データ ソース構成で Unisphere CLI インストール ディレクトリが正しいことを確認します。 * データ ソースの構成で VNXe の IP が正しいことを確認します。 Data Infrastructure Insights Acquisition Unit から CMD を開き、構成されたインストール ディレクトリ ${INSTALLDIR.次のように入力して、VNXeデバイスとの接続を試みます: uemcli -d <Your IP> -u <Your ID> /sys/general show 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
