---
sidebar: sidebar 
permalink: task_create_application.html 
summary: アプリケーションを定義し、必要に応じてテナント上の資産に適用します。 
keywords: application, create application, 
---
= アプリケーションの作成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
テナントで実行されている特定のアプリケーションに関連付けられたデータを追跡するには、 Data Infrastructure Insightsでアプリケーションを定義できます。

.タスク概要
Data Infrastructure Insights を使用すると、使用状況やコストのレポートなど、アプリケーションに関連付けられた資産からのデータを追跡できます。

.手順
. Data Infrastructure Insightsサイト メニューで、*可観測性 > エンリッチ > アプリケーション* をクリックします。選択
+
アプリケーションの追加ダイアログ ボックスが表示されます。

. アプリケーションの一意の名前を入力します。
. アプリケーションの優先度を選択します。
. *保存*をクリックします。


アプリケーションを定義したら、それを資産に割り当てることができます。



== 資産へのアプリケーションの割り当て

この手順では、例としてアプリケーションをホストに割り当てます。アプリケーションには、ホスト、仮想マシン、ボリューム、または内部ボリュームを割り当てることができます。

.手順
. アプリケーションに割り当てる資産を見つけます。
. *クエリ > +新しいクエリ* をクリックし、ホストを検索します。
. アプリケーションに関連付けるホストの左側にあるチェックボックスをクリックします。
. *一括操作 > アプリケーションの追加*をクリックします。
. 資産を割り当てるアプリケーションを選択します。


割り当てた新しいアプリケーションは、別のアセットから派生したアセット上のアプリケーションを上書きします。たとえば、ボリュームはホストからアプリケーションを継承し、新しいアプリケーションがボリュームに割り当てられると、新しいアプリケーションは派生アプリケーションよりも優先されます。


NOTE: 関連する資産が大量にある環境では、それらの資産へのアプリケーション割り当ての継承に数分かかることがあります。関連する資産が多数ある場合は、継承が発生するまでにさらに時間がかかります。

.終了後の操作
ホストをアプリケーションに割り当てた後、残りのアセットをアプリケーションに割り当てることができます。アプリケーションのランディング ページにアクセスするには、[管理] > [アプリケーション] をクリックし、作成したアプリケーションを選択します。
