---
sidebar: sidebar 
permalink: task_dc_hds_nas.html 
keywords: data collector, HDS HNAS, HDS NAS 
summary: 'HDS NAS (HNAS) データ コレクターを構成します。' 
---
= Hitachi Vantara NASデータコレクターの構成
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Hitachi Vantara NAS データ コレクターは、HDS NAS クラスターの検出をサポートするインベントリおよび構成データ コレクターです。  Data Infrastructure Insights は、 NFS および CIFS 共有、ファイル システム (内部ボリューム)、およびスパン (ストレージ プール) の検出をサポートします。



[[terminology]]
== 用語

Data Infrastructure Insights は、 HNAS データ コレクターから次のインベントリ情報を取得します。 Data Infrastructure Insightsによって取得された資産タイプごとに、その資産に使用される最も一般的な用語が表示されます。このデータ コレクターを表示またはトラブルシューティングするときは、次の用語に留意してください。

[cols="50,50"]
|===
| ベンダー/モデル用語 | Data Infrastructure Insights用語 


| 階層 | ディスクグループ 


| クラスタ | ストレージ 


| ノード | ストレージ ノード 


| スパン | ストレージ プール 


| システムドライブ | バックエンドLun 


| ファイルシステム | 内部容積 
|===
注: これらは一般的な用語のマッピングのみであり、このデータ コレクターのすべてのケースを反映しているわけではありません。



[[requirements]]
== 要件

* デバイスのIPアドレス
* ポート22、SSHプロトコル
* ユーザー名とパスワード - 権限レベル: スーパーバイザー
* 注: このデータ コレクターは SSH ベースであるため、これをホストする AU は、HNAS 自体の TCP 22 またはクラスターが接続されているシステム管理ユニット (SMU) への SSH セッションを開始できる必要があります。




[[configuration]]
== 構成

[cols="50,50"]
|===
| フィールド | 説明 


| HNASホスト | HNAS管理ホストのIPアドレスまたは完全修飾ドメイン名 


| ユーザー名 | HNAS CLIのユーザー名 


| パスワード | HNAS CLI で使用するパスワード 
|===


[[advanced-configuration]]
== 高度な設定

[cols="50,50"]
|===
| フィールド | 説明 


| インベントリポーリング間隔（分） | インベントリ ポーリングの間隔。デフォルトは30分です。 
|===


[[troubleshooting]]
== トラブルシューティング

このデータ コレクターで問題が発生した場合に試すことができるいくつかのこと:



[[inventory]]
=== インベントリ

[cols="50,50"]
|===
| 問題： | これを試してください: 


| 「接続エラー」と「シェル チャネルの設定エラー:」または「シェル チャネルを開くエラー」というエラー メッセージが表示される | ネットワーク接続の問題または SSH の設定ミスが原因である可能性があります。代替SSHクライアントで接続を確認する 


| 「タイムアウト」または「データの取得エラー」、および「コマンド: XXX がタイムアウトしました。」というエラー メッセージが表示される。 | * 別のSSHクライアントでコマンドを試す * タイムアウトを増やす 


| 「接続エラー」または「ログイン資格情報が無効です」というエラー メッセージが表示され、「デバイスと通信できませんでした:」 | * IPアドレスを確認する * ユーザー名とパスワードを確認する * 代替SSHクライアントで接続を確認する 
|===
追加情報は以下からご覧いただけます。link:concept_requesting_support.html["サポート"]ページまたはlink:reference_data_collector_support_matrix.html["データコレクターサポートマトリックス"]。
