---
sidebar: sidebar 
permalink: task_cs_user_management.html 
keywords: Workload Security, User, Login, account, cloud secure 
summary: ワークロード セキュリティ ユーザー アカウントは、Data Infrastructure Insightsユーザー管理を通じて管理されます。 
---
= ユーザー管理
:hardbreaks:
:allow-uri-read: 


[role="lead"]
Workload Security ユーザー アカウントは、Data Infrastructure Insightsを通じて管理されます。

Data Infrastructure Insights には、アカウント所有者、管理者、ユーザー、ゲストの 4 つのユーザー アカウント レベルがあります。各アカウントには特定の権限レベルが割り当てられます。管理者権限を持つユーザー アカウントは、ユーザーを作成または変更し、各ユーザーに次のいずれかの Workload Security ロールを割り当てることができます。

|===


| ロール | ワークロードセキュリティアクセス 


| 管理者 | アラート、フォレンジック、データ コレクター、自動応答ポリシー、および Workload Security の API など、すべての Workload Security 機能を実行できます。管理者は他のユーザーを招待することもできますが、割り当てることができるのは Workload Security のロールのみです。 


| ユーザ | アラートを表示および管理し、フォレンジックを表示できます。ユーザー ロールでは、アラートのステータスを変更したり、メモを追加したり、スナップショットを手動で取得したり、ユーザー アクセスを制限したりできます。 


| ゲスト | アラートとフォレンジックを表示できます。ゲスト ロールでは、アラート ステータスを変更したり、メモを追加したり、スナップショットを手動で取得したり、ユーザー アクセスを制限したりすることはできません。 
|===
.手順
. ワークロードセキュリティにログイン
. メニューで*管理>ユーザー管理*をクリックします
+
Data Infrastructure Insights のユーザー管理ページに転送されます。

. 各ユーザーに対して希望するロールを選択します。


新しいユーザーを追加するときは、希望するロール (通常はユーザーまたはゲスト) を選択するだけです。

ユーザーアカウントとロールの詳細については、Data Infrastructure Insightsをご覧ください。link:https://docs.netapp.com/us-en/cloudinsights/concept_user_roles.html["ユーザ ロール"]ドキュメント。
