---
sidebar: sidebar 
permalink: task_io_density_report_no_root.html 
summary: 高 I/O 密度を照会する場合は、ルート ボリュームを除外する必要があります。 
keywords: NetApp, root volume, high I/O, 
---
= IO密度レポートが内部データボリュームのみを記述することを保証する
:hardbreaks:
:allow-uri-read: 


[role="lead"]
NetAppルート ボリュームには、ストレージ システムを管理するためのディレクトリと構成ファイルが含まれています。高 I/O 密度を照会する場合は、これらのルート ボリュームを除外する必要があります。

環境を監視する際には、どの内部データ ボリュームが高い I/O 密度を生成しているかを判断することがより重要です。NetAppのデータ ボリュームだけを確実に特定するためには、I/O密度の監視に使用するクエリからNetAppの内部ボリュームを分離する必要があります。

このガイドでは、NetAppのルート アグリゲートを簡単に特定し、それらを内部ボリュームのクエリの結果から分離する方法と、システムにNetAppの新しいルート アグリゲートが追加されるたびにそれらを除外するルールを作成する方法を説明します。次の Insight 機能は、I/O 密度レポートが内部データ ボリュームから取得されることを保証するために使用されます。

* Insight によって監視されるすべてのNetAppルート アグリゲートを識別するためのクエリが作成されます。
* NetAppのルート アグリゲートのそれぞれにアノテーションを割り当てる。
* 新しいNetAppルート アグリゲートに注釈を適用するための注釈ルールが作成されます。


このガイドの手順は、他のベンダーのストレージ システムにも適用できます。ストレージ システムを管理するためのディレクトリと構成ファイルが含まれているボリュームを識別し、同様の手順を使用してこれらのボリュームを除外する必要があります。



== NetAppルート アグリゲートを識別するクエリの作成

クエリは、ユーザーが選択した基準に基づいて、詳細なレベルでの検索を提供します。クエリを使用すると、テナント上のNetAppルート アグリゲートを含む内部ボリュームを検索できます。

.手順
. テナント上のNetAppルート アグリゲートを識別するためのクエリを作成します。*クエリ > 新しいクエリ > リソース タイプの選択* (?) をクリックします。
. *ストレージプール*をクリックします
. ルートアグリゲートの名前を入力します
+
この例では、名前に「aggr0」を使用します。集約を作成するときは、名前に関して次の要件のみに従う必要があります。

+
.. 文字またはアンダースコア (_) で始まる必要があります。
.. 文字、数字、アンダースコアのみを含めることができます。
.. 250文字以内で入力してください。ほとんどの場合、集約の名前は aggr0、aggr_0、または同様のものになります。テナント上のすべてのNetAppルート アグリゲートを識別するには、反復的なプロセスが必要になる場合があります。


. [*保存*] をクリックし、新しいクエリの名前を入力します。
+
前述のとおり、この作業は反復的なプロセスになる場合があり、NetAppのすべてのルート アグリゲートを特定するために複数のクエリが必要になることがあります。





== クエリによって返されるルートボリュームの注釈を作成します

注釈はアセットに割り当てる特殊なメモであり、注釈によってアセットをフィルタリングできます。作成する注釈は、テナント上のNetAppルート アグリゲートを識別し、それらが特定のレポートに含まれないようにするために使用されます。

.開始する前に
「高 I/O 密度」レポートから除外するルート アグリゲートをすべて特定しておく必要があります。

.手順
. Data Infrastructure Insightsサイトメニューで、*管理>注釈*をクリックします。
. *追加*をクリックします
+
.. 注釈の名前を入力してください: *RootAggr*
.. 注釈の説明を入力してください: *「高I/O密度」レポートからルートアグリゲートを削除します*
.. 注釈の種類を入力してください: *ブール値*


. *保存*をクリックします




== I/O密度レポートから特定の集計を除外することを自動化する注釈ルールを作成します

個々のアセットに手動で注釈を適用する代わりに、注釈ルールを使用して複数のアセットに注釈を自動的に適用できます。注釈ルールは作成したクエリに基づいており、システム上で実行されると、既存のアセット セットに新しいアセットが追加されます。これらの資産セットがレポートから除外されると、新しい資産も自動的に除外されます。

.開始する前に
テナント上で識別したNetAppルート アグリゲートを識別するクエリを作成して保存しておく必要があります。

.手順
. Data Infrastructure Insightsツールバーで、*管理 > 注釈ルール* をクリックします。
. *[追加]*をクリックします。「ルールの追加」ダイアログが表示されます。
+
.. 名前ボックスに、ルールを説明する一意の名前を入力します: *"RootAggrExclude"*
.. クエリをクリックし、Insight が注釈ルールを適用するために使用するクエリを選択します: *"Aggregate0"*
.. 注釈をクリックし、*「ルート集計除外」*を選択します。
.. *値*をクリックし、*True*を入力します。



